import {CLASSES,MONSTERS,ITEMS,QUESTS,SKILLS,BUILDINGS} from './data.js';

const SAVE_KEY='georpg_build_01';
const app=document.querySelector('#app');
const toastEl=document.querySelector('#toast');
let state=null, combat=null, gpsWatch=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const daySeed=()=>Number(new Date().toISOString().slice(0,10).replaceAll('-',''));
const seeded=(seed)=>{let x=Math.sin(seed)*10000;return x-Math.floor(x)};
const uid=()=>Math.random().toString(36).slice(2,9);

function xpNeed(lvl){return Math.floor(100+55*lvl+18*lvl*lvl)}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function load(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch{return null}}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),2300)}
function itemObj(id){return ITEMS[id]||{id,name:id,icon:'❓',type:'unknown',rarity:'common',value:0}}
function countItem(id){return state.player.inventory.filter(x=>x.id===id).reduce((a,x)=>a+(x.qty||1),0)}
function addItem(id,qty=1){const item=itemObj(id);if(['consumable','material'].includes(item.type)){const found=state.player.inventory.find(x=>x.id===id);if(found)found.qty=(found.qty||1)+qty;else state.player.inventory.push({id,qty});}else{for(let i=0;i<qty;i++)state.player.inventory.push({id,uid:uid()});}checkQuestProgress('item',id);save()}
function removeItem(id,qty=1){let left=qty;for(let i=state.player.inventory.length-1;i>=0&&left>0;i--){const x=state.player.inventory[i];if(x.id!==id)continue;const q=x.qty||1;if(q>left){x.qty=q-left;left=0}else{left-=q;state.player.inventory.splice(i,1)}}save();return left===0}
function starterWeapon(cls){return cls==='mage'?'apprenticeStaff':cls==='hunter'||cls==='ranger'?'hunterBow':cls==='berserker'?'axe':'rustySword'}

function newGame(name,cls){const c=CLASSES[cls],weapon={id:starterWeapon(cls),uid:uid()},armor={id:'leather',uid:uid()};state={version:1,created:Date.now(),player:{name:name||'Wędrowiec',class:cls,level:1,xp:0,gold:40,hp:c.hp,maxHp:c.hp,mana:c.mana,maxMana:c.mana,stats:{...c.base},statPoints:0,skillPoints:0,skills:[],inventory:[weapon,armor,{id:'potion',qty:3},{id:'herb',qty:2}],equipped:{weapon,armor,trinket:null},bestiary:{},discovered:[],dungeons:[],position:{x:0,y:0,lat:null,lng:null,gps:false},kills:0,guild:null,friends:[]},quests:{active:['q1'],done:[],progress:{}},world:{entities:generateWorld(),visited:[]},settings:{demo:true}};save();render()}

function generateWorld(){const seed=daySeed();const ents=[];for(let i=0;i<26;i++){const angle=seeded(seed+i*31)*Math.PI*2;const r=70+seeded(seed+i*73)*410;const x=Math.cos(angle)*r,y=Math.sin(angle)*r;const zone=zoneAt(x,y);let pool=MONSTERS.filter(m=>m.zone===zone|| (zone!=='green'&&m.zone==='green'));if(!pool.length)pool=MONSTERS.filter(m=>m.zone==='green');const template=pool[Math.floor(seeded(seed+i*97)*pool.length)];ents.push({id:'m'+seed+'_'+i,type:'monster',template:template.id,x,y,alive:true,respawn:0,elite:seeded(seed+i*111)>.91});}
 const dungeons=[{id:'oldCrypt',name:'Stara Krypta',icon:'🕳️',x:185,y:-125,kind:'dungeon',discovered:false},{id:'forgottenTower',name:'Zapomniana Wieża',icon:'🗼',x:-300,y:-170,kind:'dungeon',discovered:false},{id:'beastLair',name:'Legowisko Bestii',icon:'🦴',x:320,y:245,kind:'dungeon',discovered:false}];
 const points=[{id:'pasture',name:'Opuszczone Pastwisko',icon:'🐑',x:95,y:55},{id:'wolfDen',name:'Wilcza Jama',icon:'🐾',x:165,y:80},{id:'oldRuins',name:'Stare Ruiny',icon:'🏚️',x:180,y:-112},{id:'watchPoint',name:'Punkt Obserwacyjny',icon:'👁️',x:145,y:-75},{id:'goblinCamp',name:'Gobliński Obóz',icon:'⛺',x:230,y:-95},{id:'hunterTrail',name:'Ślady Myśliwego',icon:'👣',x:-150,y:130},{id:'woundedHunter',name:'Ranny Myśliwy',icon:'🧔',x:-205,y:165},{id:'hermit',name:'Chata Pustelnika',icon:'🛖',x:-255,y:-75},{id:'nightGuest',name:'Nocny Punkt Obserwacji',icon:'🌙',x:245,y:-135}];
 return [...ents,...dungeons.map(x=>({...x,type:'dungeon'})),...points.map(x=>({...x,type:'poi'}))];}

function rareZones(){const s=daySeed();return {yellow:{x:(seeded(s+1)-.5)*420,y:(seeded(s+2)-.5)*420,r:200},red:{x:(seeded(s+3)-.5)*560,y:(seeded(s+4)-.5)*560,r:100},black:{x:(seeded(s+5)-.5)*650,y:(seeded(s+6)-.5)*650,r:50}}}
function zoneAt(x,y){const z=rareZones();if(Math.hypot(x-z.black.x,y-z.black.y)<=z.black.r)return'black';if(Math.hypot(x-z.red.x,y-z.red.y)<=z.red.r)return'red';if(Math.hypot(x-z.yellow.x,y-z.yellow.y)<=z.yellow.r)return'yellow';return'green'}
function monsterTemplate(ent){return MONSTERS.find(m=>m.id===ent.template)||MONSTERS[0]}
function monsterLevel(m){const p=state?.player?.level||1;return clamp(p+rnd(-2,2),m.min,m.max)}
function attackPower(){const p=state.player;const w=p.equipped.weapon?itemObj(p.equipped.weapon.id):null;return Math.floor(5+p.stats.str*1.65+p.stats.agi*.55+(w?.power||0));}
function armorPower(){const p=state.player;const a=p.equipped.armor?itemObj(p.equipped.armor.id):null;return Math.floor(p.stats.vit*.45+(a?.armor||0));}
function critChance(){const p=state.player;const t=p.equipped.trinket?itemObj(p.equipped.trinket.id):null;return Math.min(35,5+p.stats.agi*.55+(t?.crit||0));}

function gainXp(amount){const p=state.player;p.xp+=amount;let levels=0;while(p.xp>=xpNeed(p.level)&&p.level<100){p.xp-=xpNeed(p.level);p.level++;levels++;p.statPoints+=3;p.skillPoints+=p.level%2===0?1:0;const c=CLASSES[p.class];p.maxHp+=Math.floor(9+c.base.vit*.6);p.hp=p.maxHp;p.maxMana+=Math.floor(3+c.base.int*.3);p.mana=p.maxMana;}if(levels)toast(`Awans! Osiągasz poziom ${p.level}. +${levels*3} pkt statystyk.`);save()}
function rewardQuest(q){gainXp(q.xp);state.player.gold+=q.gold;state.quests.done.push(q.id);state.quests.active=state.quests.active.filter(id=>id!==q.id);const idx=QUESTS.findIndex(x=>x.id===q.id);const next=QUESTS[idx+1];if(next&&!state.quests.done.includes(next.id)&&!state.quests.active.includes(next.id))state.quests.active.push(next.id);if(q.id==='q13'&&!countItem('blackMedallion'))addItem('blackMedallion');toast(`Quest ukończony: ${q.name} (+${q.xp} XP, +${q.gold} złota)`);save()}
function checkQuestProgress(type,target,amount=1){for(const qid of [...state.quests.active]){const q=QUESTS.find(x=>x.id===qid);if(!q)continue;const prog=state.quests.progress[qid] ||= q.steps.map(()=>0);q.steps.forEach((s,i)=>{if(s.type!==type)return;if(type==='kill'&&(s.target==='any'||s.target===target))prog[i]=Math.min(s.count||1,prog[i]+amount);else if(type==='move')prog[i]=Math.max(prog[i],amount);else if(s.target===target)prog[i]=1;});const done=q.steps.every((s,i)=>prog[i]>=(s.count||1));if(done)rewardQuest(q);}save()}

function render(){if(!state){renderCreate();return}renderShell();}
function renderCreate(){let selected='knight';app.innerHTML=`<div class="boot"><div class="card create"><h1 class="logo">GEORPG</h1><p class="sub">Build 0.1 • świat zaczyna się za progiem</p><h2>Stwórz bohatera</h2><div class="form-row"><label>Imię</label><input id="heroName" maxlength="18" value="Krzysztof" /></div><div class="class-grid">${Object.entries(CLASSES).map(([id,c])=>`<button class="class-btn ${id===selected?'active':''}" data-class="${id}"><span class="class-icon">${c.icon}</span><b>${c.name}</b><div class="tiny">${c.desc}</div></button>`).join('')}</div><div id="classDesc" class="panel-item" style="margin:12px 0"></div><button id="startGame" class="primary">Rozpocznij przygodę</button></div></div>`;
 const desc=()=>{const c=CLASSES[selected];document.querySelector('#classDesc').innerHTML=`<b>${c.icon} ${c.name}</b><div class="muted">STR ${c.base.str} • AGI ${c.base.agi} • INT ${c.base.int} • VIT ${c.base.vit}</div><div>${c.desc}</div><div class="gold">Umiejętność klasowa: ${c.skill}</div>`};desc();
 document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{selected=b.dataset.class;document.querySelectorAll('[data-class]').forEach(x=>x.classList.toggle('active',x===b));desc()});document.querySelector('#startGame').onclick=()=>newGame(document.querySelector('#heroName').value.trim(),selected);
}
function topbar(){const p=state.player,c=CLASSES[p.class],need=xpNeed(p.level);return `<header class="topbar"><div class="identity"><b>${c.icon} ${p.name}</b><div class="tiny">${c.name} • poziom ${p.level}</div></div><div class="bars"><div><div class="barwrap"><div class="bar hp" style="width:${100*p.hp/p.maxHp}%"></div><div class="barlabel">HP ${p.hp}/${p.maxHp}</div></div><div class="barwrap"><div class="bar xp" style="width:${100*p.xp/need}%"></div><div class="barlabel">XP ${p.xp}/${need}</div></div></div><div><div class="barwrap"><div class="bar mana" style="width:${100*p.mana/p.maxMana}%"></div><div class="barlabel">MANA ${p.mana}/${p.maxMana}</div></div><div class="tiny">ATK ${attackPower()} • Pancerz ${armorPower()} • Kryt ${critChance().toFixed(0)}%</div></div></div><div class="resource"><span>🪙 <strong>${p.gold}</strong></span><span>📍 ${Math.round(Math.hypot(p.position.x,p.position.y))} m</span></div></header>`}
function bottomNav(){const tabs=[['map','🗺️','Mapa'],['char','🧙','Postać'],['inv','🎒','Ekwipunek'],['quests','📜','Questy'],['bestiary','📖','Bestiariusz'],['town','🍺','Miasto'],['social','👥','Gracze'],['more','⚙️','Więcej']];return `<nav class="bottom">${tabs.map(([id,ico,name])=>`<button class="navbtn ${id==='map'?'active':''}" data-nav="${id}"><span>${ico}</span>${name}</button>`).join('')}</nav>`}
function renderShell(){app.innerHTML=`<div class="shell">${topbar()}<div class="main"><main class="viewport" id="viewport"></main><aside class="side" id="side"></aside></div>${bottomNav()}</div>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>selectNav(b.dataset.nav));selectNav('map')}
function selectNav(id){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));const view=document.querySelector('#viewport'),side=document.querySelector('#side');if(id==='map'){renderMap(view);renderMapSide(side)}else{view.innerHTML=`<div style="height:100%;overflow:auto;padding:14px" id="fullPanel"></div>`;const full=document.querySelector('#fullPanel');if(id==='char')renderCharacter(full);if(id==='inv')renderInventory(full);if(id==='quests')renderQuests(full);if(id==='bestiary')renderBestiary(full);if(id==='town')renderTown(full);if(id==='social')renderSocial(full);if(id==='more')renderMore(full);side.innerHTML='<div class="section-title"><h2>GeoRPG</h2></div><div class="muted">Build 0.1 — zapis lokalny. W kolejnych etapach dojdzie backend multiplayer, konto i synchronizacja.</div>'}}

function mapScale(){const el=document.querySelector('#viewport');const w=el?.clientWidth||900,h=el?.clientHeight||700;return Math.min(w,h)/900}
function posStyle(x,y){const s=mapScale();const p=state.player.position;return `left:calc(50% + ${(x-p.x)*s}px);top:calc(50% + ${(y-p.y)*s}px)`}
function renderMap(el){const p=state.player.position,z=rareZones(),s=mapScale();const entities=[...BUILDINGS,...state.world.entities];el.innerHTML=`<div class="map" id="map"><div class="map-center"></div>${['yellow','red','black'].map(k=>`<div class="zone ${k}" style="${posStyle(z[k].x,z[k].y)};width:${z[k].r*2*s}px;height:${z[k].r*2*s}px"></div><div class="zone-label" style="${posStyle(z[k].x,z[k].y)}">${k.toUpperCase()}</div>`).join('')}<div class="range"></div>${entities.map(entityHTML).join('')}<div class="player-marker"><div class="sprite">${CLASSES[state.player.class].icon}</div></div><div class="map-hud"><div class="hudbox">Strefa: <b>${zoneAt(p.x,p.y).toUpperCase()}</b><br>${p.gps?`GPS: ${p.lat?.toFixed(5)}, ${p.lng?.toFixed(5)}`:'Tryb demo — strzałkami poruszasz się po świecie'}</div><button id="gpsBtn" class="secondary">${p.gps?'📡 GPS aktywny':'📍 Włącz prawdziwy GPS'}</button></div><div class="move-pad"><button data-move="0,-20">▲</button><button style="grid-column:1;grid-row:2" data-move="-20,0">◀</button><button class="gps">✦</button><button style="grid-column:3;grid-row:2" data-move="20,0">▶</button><button style="grid-column:2;grid-row:3" data-move="0,20">▼</button></div></div>`;
 document.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>interactEntity(b.dataset.entity,b.dataset.kind));document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const [dx,dy]=b.dataset.move.split(',').map(Number);moveDemo(dx,dy)});document.querySelector('#gpsBtn').onclick=enableGps;}
function entityHTML(e){if(e.type==='monster'&&!e.alive&&e.respawn>Date.now())return'';let name=e.name,icon=e.icon,klass=e.type||e.kind;if(e.type==='monster'){const m=monsterTemplate(e);name=m.name;icon=m.icon;klass+=e.elite?' elite':'';}const d=dist(state.player.position,e);const locked=d>90&&e.type!=='building';return `<button class="entity ${klass} ${locked?'locked':''}" style="${posStyle(e.x,e.y)}" data-entity="${e.id}" data-kind="${e.type||e.kind}"><span class="sprite">${icon}</span><span class="ename">${name}${d<999?` • ${Math.round(d)}m`:''}</span></button>`}
function renderMapSide(el){const q=QUESTS.find(x=>state.quests.active.includes(x.id));el.innerHTML=`<div class="section-title"><h2>Aktywny cel</h2><span class="pill">GPS RPG</span></div>${q?questCard(q,true):'<div class="panel-item">Brak aktywnego zadania.</div>'}<div class="section-title" style="margin-top:14px"><h2>W pobliżu</h2></div><div class="panel-list">${nearestEntities().slice(0,6).map(({e,d})=>{let n=e.name||monsterTemplate(e).name;return `<div class="panel-item"><b>${n}</b><div class="muted">${Math.round(d)} m • ${e.type||e.kind}</div></div>`}).join('')}</div>`}
function nearestEntities(){return [...BUILDINGS,...state.world.entities].filter(e=>e.type!=='monster'||e.alive||e.respawn<=Date.now()).map(e=>({e,d:dist(state.player.position,e)})).sort((a,b)=>a.d-b.d)}
function moveDemo(dx,dy){const p=state.player.position;p.x+=dx;p.y+=dy;p.gps=false;checkQuestProgress('move','',Math.hypot(p.x,p.y));discoverNearby();save();selectNav('map')}
function discoverNearby(){for(const e of state.world.entities){if(e.type==='monster')continue;const d=dist(state.player.position,e);if(d<=25&&!state.player.discovered.includes(e.id)){state.player.discovered.push(e.id);if(e.type==='dungeon'&&!state.player.dungeons.includes(e.id))state.player.dungeons.push(e.id);checkQuestProgress('discover',e.id);toast(`Odkryto: ${e.name}`);}}}
function interactEntity(id,kind){const e=[...BUILDINGS,...state.world.entities].find(x=>x.id===id);if(!e)return;const d=dist(state.player.position,e);if(kind==='building'){if(d>120)return toast('Podejdź bliżej do budynku.');openBuilding(id);return}if(d>90)return toast(`Za daleko: ${Math.round(d)} m. Podejdź na ≤ 90 m.`);if(kind==='monster')startCombat(e);else if(kind==='dungeon'){if(d<=25){if(!state.player.discovered.includes(e.id)){state.player.discovered.push(e.id);state.player.dungeons.push(e.id);checkQuestProgress('discover',e.id);toast(`Odkryto loch: ${e.name}`)}openDungeon(e)}else toast('Podejdź na 25 m, aby odkryć loch.')}else{if(!state.player.discovered.includes(e.id)){state.player.discovered.push(e.id);checkQuestProgress('discover',e.id);toast(`Odkryto: ${e.name}`);save();selectNav('map')}else toast('To miejsce jest już odkryte.')}}

function enableGps(){if(!navigator.geolocation)return toast('Ta przeglądarka nie udostępnia geolokalizacji.');if(gpsWatch!==null){navigator.geolocation.clearWatch(gpsWatch);gpsWatch=null;state.player.position.gps=false;save();selectNav('map');return}let origin=null;gpsWatch=navigator.geolocation.watchPosition(pos=>{const {latitude,longitude,accuracy}=pos.coords;if(!origin)origin={lat:latitude,lng:longitude};const latm=(latitude-origin.lat)*111320,lngm=(longitude-origin.lng)*111320*Math.cos(latitude*Math.PI/180);Object.assign(state.player.position,{lat:latitude,lng:longitude,x:lngm,y:-latm,gps:true,accuracy});checkQuestProgress('move','',Math.hypot(lngm,latm));discoverNearby();save();selectNav('map')},()=>toast('Nie udało się pobrać GPS. Zezwól stronie na lokalizację.'),{enableHighAccuracy:true,maximumAge:3000,timeout:12000});toast('Uruchamiam GPS… Na GitHub Pages działa przez HTTPS.')}

function startCombat(ent){if(!ent.alive&&ent.respawn>Date.now())return toast('Ten przeciwnik jeszcze się nie odrodził.');const m=monsterTemplate(ent),lvl=monsterLevel(m);combat={entity:ent,monster:m,level:lvl,hp:Math.floor(m.hp*(.72+.075*lvl)),maxHp:Math.floor(m.hp*(.72+.075*lvl)),atk:Math.floor(m.atk*(.7+.055*lvl)),log:[`Rozpoczyna się walka z ${m.name} (lvl ${lvl}).`],turn:1,status:{fortress:0,poison:0}};renderCombat()}
function renderCombat(){const p=state.player,m=combat.monster;openModal(`<div class="modal-head"><div><h2>⚔️ Walka</h2><div class="muted">Tura ${combat.turn} • ${m.family}</div></div><button class="close" data-close>×</button></div><div class="combat"><div class="fighter"><div class="big">${CLASSES[p.class].icon}</div><b>${p.name}</b><div class="barwrap" style="margin-top:8px"><div class="bar hp" style="width:${100*p.hp/p.maxHp}%"></div><div class="barlabel">${p.hp}/${p.maxHp} HP</div></div><div class="barwrap"><div class="bar mana" style="width:${100*p.mana/p.maxMana}%"></div><div class="barlabel">${p.mana}/${p.maxMana} many</div></div></div><div class="fighter"><div class="big">${m.icon}</div><b>${combat.entity.elite?'ELITA • ':''}${m.name}</b><div class="muted">poziom ${combat.level}</div><div class="barwrap" style="margin-top:8px"><div class="bar hp" style="width:${100*combat.hp/combat.maxHp}%"></div><div class="barlabel">${combat.hp}/${combat.maxHp} HP</div></div></div></div><div class="combat-actions"><button class="primary" data-act="attack">⚔️ Atak</button><button class="secondary" data-act="skill">✨ Umiejętność</button><button class="secondary" data-act="potion">🧪 Mikstura (${countItem('potion')})</button><button class="danger" data-act="flee">🏃 Ucieczka</button></div><div class="log">${combat.log.slice(-8).map(x=>`<div>${x}</div>`).join('')}</div>`);document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>combatAction(b.dataset.act));}
function combatAction(a){if(a==='flee'){if(Math.random()<.7){closeModal();toast('Udało Ci się uciec.');return}else combat.log.push('Nie udało się uciec!')}else if(a==='potion'){if(!countItem('potion'))return toast('Brak mikstur.');removeItem('potion');const heal=itemObj('potion').heal;state.player.hp=Math.min(state.player.maxHp,state.player.hp+heal);combat.log.push(`Wypijasz miksturę: +${heal} HP.`)}else{let dmg=attackPower()+rnd(-3,5),manaCost=0;if(a==='skill'){manaCost=18;if(state.player.mana<manaCost)return toast('Za mało many.');state.player.mana-=manaCost;dmg=Math.floor(dmg*1.65);combat.log.push('Używasz umiejętności klasowej!')}if(Math.random()*100<critChance()){dmg*=2;combat.log.push('💥 Trafienie krytyczne!')}dmg=Math.max(1,Math.floor(dmg));combat.hp-=dmg;combat.log.push(`Zadajesz ${dmg} obrażeń.`);if(combat.hp<=0)return winCombat();}
 enemyTurn();combat.turn++;save();renderCombat()}
function enemyTurn(){let reduction=Math.floor(armorPower()*.65),dmg=Math.max(1,combat.atk+rnd(-3,4)-reduction);if(combat.status.fortress>0){dmg=Math.floor(dmg*.55);combat.status.fortress--}state.player.hp=Math.max(0,state.player.hp-dmg);combat.log.push(`${combat.monster.name} zadaje Ci ${dmg} obrażeń.`);if(state.player.hp<=0)loseCombat()}
function winCombat(){const m=combat.monster,e=combat.entity;let xp=Math.floor(m.xp*(.6+.06*combat.level)*(e.elite?1.8:1)),gold=rnd(...m.gold)*(e.elite?2:1);state.player.gold+=gold;state.player.kills++;state.player.bestiary[m.id]=(state.player.bestiary[m.id]||0)+1;e.alive=false;e.respawn=Date.now()+5*60*1000;checkQuestProgress('kill',m.id);if(m.id==='wolf'&&Math.random()<.65)addItem('wolfPelt');if(m.family==='Nieumarli'&&Math.random()<.55)addItem('bone');if(Math.random()<.18)addItem('potion');if(e.elite&&Math.random()<.32)addItem('blueBlade');gainXp(xp);save();closeModal();toast(`Zwycięstwo! +${xp} XP • +${gold} złota`);selectNav('map')}
function loseCombat(){state.player.gold=Math.max(0,state.player.gold-Math.ceil(state.player.gold*.05));state.player.hp=Math.ceil(state.player.maxHp*.45);state.player.mana=Math.ceil(state.player.maxMana*.45);save();closeModal();toast('Porażka. Budzisz się w wiosce i tracisz 5% złota.');state.player.position.x=0;state.player.position.y=0;selectNav('map')}

function questCard(q,compact=false){const prog=state.quests.progress[q.id]||q.steps.map(()=>0);return `<div class="panel-item"><h3>📜 ${q.name}</h3><div class="muted">${q.chapter} • sugerowany lvl ${q.level}</div>${compact?'':`<p>${q.desc}</p>`}${q.steps.map((s,i)=>`<div class="quest-step ${prog[i]>=(s.count||1)?'done':''}">${s.label} ${s.count?`(${prog[i]||0}/${s.count})`:prog[i]?'✓':''}</div>`).join('')}<div class="gold">Nagroda: ${q.xp} XP • ${q.gold} 🪙</div></div>`}
function renderCharacter(el){const p=state.player,c=CLASSES[p.class];el.innerHTML=`<div class="section-title"><h2>${c.icon} ${p.name} — ${c.name}</h2><span>lvl ${p.level}</span></div><div class="grid2">${Object.entries(p.stats).map(([k,v])=>`<div class="stat"><span>${{str:'Siła',agi:'Zręczność',int:'Inteligencja',vit:'Witalność'}[k]}</span><b>${v} ${p.statPoints?`<button class="secondary" style="padding:1px 5px" data-stat="${k}">+</button>`:''}</b></div>`).join('')}</div><p class="muted">Punkty statystyk: ${p.statPoints} • Punkty umiejętności: ${p.skillPoints}</p><div class="section-title"><h2>Drzewko umiejętności</h2></div>${SKILLS[p.class].map(s=>`<div class="skill-node ${p.skills.includes(s.id)?'unlocked':p.level>=s.lvl?'':'locked'}"><b>${p.skills.includes(s.id)?'✅':'🔒'} ${s.name}</b><div class="muted">Wymagany lvl ${s.lvl} • koszt ${s.cost} pkt</div><div>${s.desc}</div>${!p.skills.includes(s.id)&&p.level>=s.lvl?`<button class="secondary" data-skill="${s.id}">Odblokuj</button>`:''}</div>`).join('')}<div class="section-title" style="margin-top:16px"><h2>Wyposażenie</h2></div><div class="grid2">${['weapon','armor','trinket'].map(slot=>`<div class="panel-item"><b>${{weapon:'Broń',armor:'Pancerz',trinket:'Talizman'}[slot]}</b><div>${p.equipped[slot]?`${itemObj(p.equipped[slot].id).icon} ${itemObj(p.equipped[slot].id).name}`:'— puste —'}</div></div>`).join('')}</div>`;document.querySelectorAll('[data-stat]').forEach(b=>b.onclick=()=>{if(p.statPoints<=0)return;p.stats[b.dataset.stat]++;p.statPoints--;if(b.dataset.stat==='vit'){p.maxHp+=6;p.hp+=6}if(b.dataset.stat==='int'){p.maxMana+=4;p.mana+=4}save();selectNav('char')});document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{const s=SKILLS[p.class].find(x=>x.id===b.dataset.skill);if(p.skillPoints<s.cost)return toast('Za mało punktów umiejętności.');p.skillPoints-=s.cost;p.skills.push(s.id);save();selectNav('char')})}

function renderInventory(el){const p=state.player;el.innerHTML=`<div class="section-title"><h2>🎒 Ekwipunek</h2><span>${p.inventory.length}/40</span></div><div class="inventory-grid">${p.inventory.map((x,i)=>{const it=itemObj(x.id);return `<button class="slot ${it.rarity==='rare'?'rare':it.rarity==='epic'?'epic':it.rarity==='legendary'?'legend':''}" data-itemidx="${i}"><span class="ico">${it.icon}</span><span>${it.name}</span>${x.qty>1?`<span class="badge">x${x.qty}</span>`:''}</button>`}).join('')}${Array.from({length:Math.max(0,20-p.inventory.length)},()=>'<div class="slot"></div>').join('')}</div>`;document.querySelectorAll('[data-itemidx]').forEach(b=>b.onclick=()=>openItem(Number(b.dataset.itemidx)))}
function openItem(i){const x=state.player.inventory[i],it=itemObj(x.id);openModal(`<div class="modal-head"><div><h2>${it.icon} ${it.name}</h2><div class="muted">${it.type} • ${it.rarity}</div></div><button class="close" data-close>×</button></div><p>${it.power?`Obrażenia +${it.power}`:''}${it.armor?`Pancerz +${it.armor}`:''}${it.crit?`Krytyk +${it.crit}%`:''}${it.heal?`Leczy ${it.heal} HP`:''}</p><div class="tabs">${['weapon','armor','trinket'].includes(it.type)?`<button data-equip>Załóż</button>`:''}${it.type==='consumable'?`<button data-use>Użyj</button>`:''}${it.value?`<button data-sell>Sprzedaj (${Math.floor(it.value*.5)} 🪙)</button>`:''}</div>`);if(document.querySelector('[data-equip]'))document.querySelector('[data-equip]').onclick=()=>{state.player.equipped[it.type]=x;save();closeModal();selectNav('inv');toast(`Założono: ${it.name}`)};if(document.querySelector('[data-use]'))document.querySelector('[data-use]').onclick=()=>{if(it.heal)state.player.hp=Math.min(state.player.maxHp,state.player.hp+it.heal);if(it.mana)state.player.mana=Math.min(state.player.maxMana,state.player.mana+it.mana);removeItem(it.id);save();closeModal();selectNav('inv')};if(document.querySelector('[data-sell]'))document.querySelector('[data-sell]').onclick=()=>{state.player.gold+=Math.floor(it.value*.5);removeItem(it.id);save();closeModal();selectNav('inv')}}

function renderQuests(el){el.innerHTML=`<div class="section-title"><h2>📜 Dziennik zadań</h2><span>${state.quests.done.length}/${QUESTS.length}</span></div><div class="panel-list">${QUESTS.filter(q=>state.quests.active.includes(q.id)).map(q=>questCard(q)).join('')||'<div class="panel-item">Brak aktywnych zadań.</div>'}</div><div class="section-title" style="margin-top:18px"><h2>Ukończone</h2></div><div class="panel-list">${QUESTS.filter(q=>state.quests.done.includes(q.id)).map(q=>`<div class="panel-item"><b>✅ ${q.name}</b><div class="muted">${q.chapter}</div></div>`).join('')||'<div class="muted">Jeszcze żadnego.</div>'}</div>`}
function renderBestiary(el){const entries=MONSTERS.filter(m=>state.player.bestiary[m.id]);el.innerHTML=`<div class="section-title"><h2>📖 Bestiariusz</h2><span>${entries.length}/${MONSTERS.length}</span></div><div class="panel-list">${entries.map(m=>`<div class="panel-item"><h3>${m.icon} ${m.name}</h3><div class="muted">${m.family} • poziomy ${m.min}–${m.max} • strefa ${m.zone}</div><div>Pokonano: <b>${state.player.bestiary[m.id]}</b></div><div class="muted">Możliwy łup: złoto, materiały, mikstury${m.id==='wolf'?', wilcza skóra':''}.</div></div>`).join('')||'<div class="panel-item">Pokonaj pierwszego potwora, aby odkryć jego wpis.</div>'}</div>`}

function renderTown(el){el.innerHTML=`<div class="section-title"><h2>🏘️ Wioska</h2><span class="pill">bezpieczna strefa</span></div><div class="grid2">${BUILDINGS.map(b=>`<button class="panel-item" data-building="${b.id}" style="color:inherit;text-align:left"><h3>${b.icon} ${b.name}</h3><div class="muted">Otwórz usługę</div></button>`).join('')}</div><div class="section-title" style="margin-top:18px"><h2>Odkryte lochy</h2></div><div class="panel-list">${state.player.dungeons.map(id=>{const d=state.world.entities.find(e=>e.id===id);return `<button class="panel-item" style="color:inherit;text-align:left" data-home-dungeon="${id}"><b>${d?.icon||'🕳️'} ${d?.name||id}</b><div class="muted">Możesz wejść z domu — GPS był potrzebny do odkrycia.</div></button>`}).join('')||'<div class="panel-item">Nie odkryłeś jeszcze żadnego lochu w terenie.</div>'}</div>`;document.querySelectorAll('[data-building]').forEach(b=>b.onclick=()=>openBuilding(b.dataset.building));document.querySelectorAll('[data-home-dungeon]').forEach(b=>b.onclick=()=>openDungeon(state.world.entities.find(e=>e.id===b.dataset.homeDungeon)))}
function openBuilding(id){const pages={tavern:['🍺 Karczma „Pod Krukiem”',tavernHTML],shop:['🛒 Sklep kupiecki',shopHTML],smith:['⚒️ Kuźnia',smithHTML],alchemist:['⚗️ Alchemik',alchemistHTML],auction:['🏛️ Dom aukcyjny',auctionHTML],guild:['🏰 Sala gildii',guildHTML]};const [title,fn]=pages[id]||pages.tavern;openModal(`<div class="modal-head"><div><h2>${title}</h2><div class="muted">Wioska Startowa</div></div><button class="close" data-close>×</button></div><div id="buildingBody">${fn()}</div>`);bindBuilding(id)}
function tavernHTML(){const next=QUESTS.find(q=>!state.quests.done.includes(q.id)&&!state.quests.active.includes(q.id)&&q.level<=state.player.level+1);return `<p>W karczmie usłyszysz plotki, znajdziesz drużynę i odpoczniesz.</p><div class="panel-list"><div class="panel-item"><b>🛏️ Odpoczynek</b><div class="muted">Pełne HP i mana za 10 złota.</div><button class="secondary" data-rest>Odpocznij</button></div>${next?`<div class="panel-item"><b>📜 Tablica: ${next.name}</b><div>${next.desc}</div><button class="secondary" data-accept="${next.id}">Przyjmij zadanie</button></div>`:''}<div class="panel-item"><b>👥 Zadanie drużynowe</b><div class="muted">Demo UI — backend drużyn dojdzie w etapie multiplayer.</div></div></div>`}
function shopHTML(){return `<div class="panel-list">${['potion','manaPotion','leather'].map(id=>{const i=itemObj(id);return `<div class="panel-item shoprow"><div><b>${i.icon} ${i.name}</b><div class="muted">Cena ${i.value} 🪙</div></div><button class="secondary" data-buy="${id}">Kup</button></div>`}).join('')}</div>`}
function smithHTML(){return `<p>Kowal ulepsza wyposażenie. W tym buildzie naprawa i prosty zakup sprzętu są aktywne.</p><div class="panel-item shoprow"><div><b>🛡️ Żelazny kirys</b><div class="muted">Pancerz +9 • 75 🪙</div></div><button class="secondary" data-buy="ironArmor">Kup</button></div><div class="panel-item"><b>🔨 Ulepszenie +1</b><div class="muted">Pełny system poziomów przedmiotów powstanie w kolejnym buildzie.</div></div>`}
function alchemistHTML(){return `<div class="panel-item"><b>🧪 Warzenie mikstury życia</b><div class="muted">2× Gorzki liść → 1× Mikstura życia</div><button class="secondary" data-craft="potion">Uwarz</button></div><div class="panel-item"><b>🔷 Mikstura many</b><div class="muted">Kup w sklepie; receptura pojawi się po odkryciu składników.</div></div>`}
function auctionHTML(){return `<div class="panel-item"><b>🏛️ Aukcje graczy</b><p>Interfejs jest gotowy koncepcyjnie, ale prawdziwe oferty wymagają wspólnej bazy danych i logowania.</p><div class="muted">Build 0.1 nie udaje transakcji sieciowych — to zostanie spięte z backendem.</div></div>`}
function guildHTML(){return `<div class="panel-item"><b>🛡️ Gildie</b><p>${state.player.guild?`Należysz do gildii <b>${state.player.guild}</b>.`:'Nie należysz jeszcze do gildii.'}</p>${!state.player.guild?'<input id="guildName" placeholder="Nazwa gildii" style="width:100%;padding:9px;background:#0b0e11;color:#ddd;border:1px solid #333"><button class="secondary" style="margin-top:8px" data-create-guild>Utwórz lokalną gildię demo</button>':''}<div class="muted">Członkowie, czat i gildyjne lochy wymagają backendu.</div></div>`}
function bindBuilding(id){document.querySelector('[data-rest]')?.addEventListener('click',()=>{if(state.player.gold<10)return toast('Za mało złota.');state.player.gold-=10;state.player.hp=state.player.maxHp;state.player.mana=state.player.maxMana;save();closeModal();renderShell();toast('Odpoczywasz. Siły odzyskane.')});document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const i=itemObj(b.dataset.buy);if(state.player.gold<i.value)return toast('Za mało złota.');state.player.gold-=i.value;addItem(i.id);save();openBuilding(id);toast(`Kupiono: ${i.name}`)});document.querySelector('[data-craft]')?.addEventListener('click',()=>{if(countItem('herb')<2)return toast('Potrzebujesz 2× Gorzki liść.');removeItem('herb',2);addItem('potion');openBuilding(id);toast('Uwarzono Miksturę życia.')});document.querySelector('[data-accept]')?.addEventListener('click',e=>{state.quests.active.push(e.target.dataset.accept);save();closeModal();renderShell();toast('Zadanie przyjęte.')});document.querySelector('[data-create-guild]')?.addEventListener('click',()=>{const n=document.querySelector('#guildName').value.trim();if(!n)return;state.player.guild=n;save();openBuilding('guild')})}

function renderSocial(el){const fake=[{n:'Ardan',l:7,c:'knight',d:42},{n:'Mirael',l:6,c:'mage',d:88},{n:'Borvik',l:9,c:'berserker',d:135}];el.innerHTML=`<div class="section-title"><h2>👥 Gracze w pobliżu</h2><span class="pill">DEMO</span></div><p class="muted">Poniżsi gracze są demonstracją interfejsu. Prawdziwa obecność online wymaga backendu WebSocket / realtime DB.</p><div class="panel-list">${fake.map((x,i)=>`<button class="panel-item" style="color:inherit;text-align:left" data-player="${i}"><b>${CLASSES[x.c].icon} ${x.n}</b> • lvl ${x.l}<div class="muted">${x.d} m od Ciebie</div></button>`).join('')}</div>`;document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>openPlayer(fake[Number(b.dataset.player)]))}
function openPlayer(x){openModal(`<div class="modal-head"><div><h2>${CLASSES[x.c].icon} ${x.n}</h2><div class="muted">${CLASSES[x.c].name} • lvl ${x.l}</div></div><button class="close" data-close>×</button></div><div class="tabs"><button data-social="party">➕ Zaproś do drużyny</button><button data-social="pvp">⚔️ Wyzwij PvP</button><button data-social="trade">🤝 Handel</button><button data-social="profile">👤 Profil</button><button data-social="friend">⭐ Dodaj znajomego</button></div><p class="muted">Akcje sieciowe są przygotowane w UI. Po podpięciu backendu będą operować na prawdziwych kontach.</p>`);document.querySelectorAll('[data-social]').forEach(b=>b.onclick=()=>toast(`Akcja „${b.textContent.trim()}” wymaga backendu multiplayer.`))}

function renderMore(el){el.innerHTML=`<div class="section-title"><h2>⚙️ Ustawienia i informacje</h2></div><div class="panel-list"><div class="panel-item"><b>💾 Zapis gry</b><div class="muted">Automatycznie w localStorage tej przeglądarki.</div><button class="secondary" data-export>Eksportuj zapis</button></div><div class="panel-item"><b>🧪 Tryb testowy</b><div class="muted">Strzałki na mapie przesuwają postać o 20 m. Dzięki temu można testować bez chodzenia po mieście.</div></div><div class="panel-item"><b>📍 GPS</b><div class="muted">Prawdziwy GPS działa w przeglądarce po HTTPS. Pierwsza pobrana pozycja jest lokalnym punktem 0,0 świata proceduralnego.</div></div><div class="panel-item"><b>🔄 Reset</b><div class="muted">Usuwa lokalny zapis.</div><button class="danger" data-reset>Usuń zapis</button></div></div>`;document.querySelector('[data-export]').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='georpg-save.json';a.click();URL.revokeObjectURL(a.href)};document.querySelector('[data-reset]').onclick=()=>{if(confirm('Na pewno usunąć zapis?')){localStorage.removeItem(SAVE_KEY);state=null;render()}}}

function openDungeon(d){if(!d)return;const roomSeed=daySeed()+[...d.id].reduce((a,c)=>a+c.charCodeAt(0),0);const rooms=['Wejście','Sala z runami','Zawalony korytarz','Komnata strażnika','Ukryta skrytka','Sala bossa'];openModal(`<div class="modal-head"><div><h2>${d.icon||'🕳️'} ${d.name}</h2><div class="muted">Loch odświeża układ codziennie • odkryty GPS</div></div><button class="close" data-close>×</button></div><p>Wybierz drogę. Ten prototyp pokazuje podstawę systemu pomieszczeń, losowych zdarzeń i bossa.</p><div class="panel-list">${rooms.map((r,i)=>`<div class="panel-item"><b>${i+1}. ${r}</b><div class="muted">${i===1?'Runy mogą dać premię albo pułapkę.':i===4?'Szansa na skrzynię.':i===5?'Boss lochu — walka końcowa.':'Eksploracja.'}</div></div>`).join('')}</div><button class="primary" data-run-dungeon>Rozpocznij wyprawę</button>`);document.querySelector('[data-run-dungeon]').onclick=()=>runDungeon(d,roomSeed)}
function runDungeon(d,seed){closeModal();const candidates=state.world.entities.filter(e=>e.type==='monster');let e=candidates.find(x=>x.alive&&dist(x,d)<180)||candidates.find(x=>x.alive);if(!e){state.world.entities=generateWorld();e=state.world.entities.find(x=>x.type==='monster')}e.elite=true;const prev=e.template;if(d.id==='oldCrypt')e.template='skeleton';if(d.id==='beastLair')e.template='wyvern';combatDungeonTarget=d.id;startCombat(e);}
let combatDungeonTarget=null;
// Wrap dungeon victory without changing core combat definition above.
const _winBase=winCombat;
winCombat=function(){const target=combatDungeonTarget;const before=state.player.kills; // capture
 const m=combat.monster,e=combat.entity;let xp=Math.floor(m.xp*(.6+.06*combat.level)*(e.elite?1.8:1)),gold=rnd(...m.gold)*(e.elite?2:1);state.player.gold+=gold;state.player.kills++;state.player.bestiary[m.id]=(state.player.bestiary[m.id]||0)+1;e.alive=false;e.respawn=Date.now()+5*60*1000;checkQuestProgress('kill',m.id);if(m.id==='wolf'&&Math.random()<.65)addItem('wolfPelt');if(m.family==='Nieumarli'&&Math.random()<.55)addItem('bone');if(Math.random()<.2)addItem('potion');if(e.elite&&Math.random()<.35)addItem('blueBlade');gainXp(xp);if(target){const bonus=Math.floor(xp*.65);gainXp(bonus);state.player.gold+=30;checkQuestProgress('dungeon',target);combatDungeonTarget=null;toast(`Loch ukończony! +${xp+bonus} XP • +${gold+30} złota`)}else toast(`Zwycięstwo! +${xp} XP • +${gold} złota`);save();closeModal();selectNav('map')}

function openModal(html){let wrap=document.querySelector('.modal-back');if(!wrap){wrap=document.createElement('div');wrap.className='modal-back';document.body.appendChild(wrap)}wrap.innerHTML=`<div class="modal">${html}</div>`;wrap.onclick=e=>{if(e.target===wrap)closeModal()};wrap.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}
function closeModal(){document.querySelector('.modal-back')?.remove()}

state=load();
if(state?.world?.entities){for(const e of state.world.entities)if(e.type==='monster'&&!e.alive&&e.respawn<=Date.now())e.alive=true}
render();
