export const CLASSES = {
  knight:{name:'Ciężki Rycerz',icon:'🛡️',accent:'stal',desc:'Tank. Blok, pancerz, tarcza i kontrola przeciwnika.',base:{str:7,agi:3,int:2,vit:9},hp:150,mana:45},
  mage:{name:'Mag',icon:'🔮',accent:'arkanum',desc:'Silne zaklęcia, mana i efekty żywiołów.',base:{str:2,agi:4,int:10,vit:5},hp:95,mana:125},
  hunter:{name:'Łowca',icon:'🏹',accent:'las',desc:'Krytyki, podwójny strzał i współpraca z chowańcem.',base:{str:4,agi:10,int:3,vit:5},hp:108,mana:75},
  berserker:{name:'Berserker',icon:'🪓',accent:'krew',desc:'Ogromne obrażenia, furia i premie przy niskim HP.',base:{str:10,agi:5,int:1,vit:7},hp:138,mana:40},
  ranger:{name:'Tropiciel',icon:'🌿',accent:'natura',desc:'Trucizny, pułapki, mobilność i chowaniec.',base:{str:4,agi:8,int:6,vit:5},hp:112,mana:90}
};

export const MONSTERS = [
 {id:'slime',name:'Błotny Pełzacz',icon:'🟢',family:'Natura',min:1,max:4,zone:'green',hp:42,atk:7,xp:38,gold:[3,8],weak:'ogień'},
 {id:'rat',name:'Zdziczały Szczur',icon:'🐀',family:'Natura',min:1,max:5,zone:'green',hp:36,atk:8,xp:35,gold:[2,7],weak:'trucizna'},
 {id:'beetle',name:'Pancerznik',icon:'🪲',family:'Owady',min:2,max:7,zone:'green',hp:48,atk:8,xp:44,gold:[3,9],weak:'przebicie'},
 {id:'wolf',name:'Szary Wilk',icon:'🐺',family:'Natura',min:4,max:10,zone:'green',hp:62,atk:11,xp:62,gold:[5,12],weak:'pułapki'},
 {id:'goblin',name:'Gobliński Zwiadowca',icon:'👺',family:'Ludzie',min:3,max:12,zone:'green',hp:58,atk:10,xp:58,gold:[5,13],weak:'krwawienie'},
 {id:'skeleton',name:'Kościany Wojownik',icon:'💀',family:'Nieumarli',min:10,max:22,zone:'green',hp:94,atk:16,xp:118,gold:[10,20],weak:'obuch'},
 {id:'ghost',name:'Błądząca Zjawa',icon:'👻',family:'Zjawy',min:25,max:38,zone:'yellow',hp:145,atk:23,xp:245,gold:[18,34],weak:'arkanum'},
 {id:'elemental',name:'Żywiołak Kamienia',icon:'🗿',family:'Żywiołaki',min:30,max:45,zone:'yellow',hp:190,atk:25,xp:300,gold:[22,40],weak:'lód'},
 {id:'cultist',name:'Kultysta Pustki',icon:'🥷',family:'Ludzie',min:20,max:38,zone:'yellow',hp:135,atk:24,xp:220,gold:[16,35],weak:'światło'},
 {id:'demon',name:'Rogaty Demon',icon:'👹',family:'Demony',min:40,max:58,zone:'red',hp:265,atk:38,xp:520,gold:[35,65],weak:'lód'},
 {id:'hellhound',name:'Piekielny Ogar',icon:'🐕‍🦺',family:'Demony',min:45,max:65,zone:'red',hp:245,atk:43,xp:560,gold:[38,72],weak:'woda'},
 {id:'wyvern',name:'Popielna Wywerna',icon:'🐉',family:'Bestie',min:60,max:80,zone:'black',hp:420,atk:58,xp:920,gold:[70,120],weak:'przebicie'},
 {id:'shade',name:'Cień z Kurhanu',icon:'🌑',family:'Zjawy',min:18,max:32,zone:'yellow',hp:122,atk:21,xp:190,gold:[14,30],weak:'światło'},
 {id:'spider',name:'Leśny Tkacz',icon:'🕷️',family:'Owady',min:8,max:18,zone:'green',hp:82,atk:14,xp:96,gold:[8,18],weak:'ogień'},
 {id:'ogre',name:'Ogr Rozbójnik',icon:'👹',family:'Ludzie',min:32,max:48,zone:'yellow',hp:235,atk:31,xp:365,gold:[28,52],weak:'trucizna'},
 {id:'graveColossus',name:'Koloss z Kurhanu',icon:'🗿',family:'Nieumarli',min:8,max:45,zone:'red',hp:360,atk:33,xp:780,gold:[80,140],weak:'światło'},
 {id:'stormDrake',name:'Smok Burzowy',icon:'🐲',family:'Bestie',min:12,max:55,zone:'red',hp:420,atk:38,xp:920,gold:[95,160],weak:'lód'},
 {id:'mireCrawler',name:'Pełzacz Moczaru',icon:'🪱',family:'Owady',min:21,max:26,zone:'yellow',hp:152,atk:24,xp:255,gold:[20,36],weak:'ogień'},
 {id:'bogWraith',name:'Zjawa Topielca',icon:'🫧',family:'Zjawy',min:22,max:29,zone:'yellow',hp:164,atk:27,xp:285,gold:[22,40],weak:'światło'},
 {id:'fenStalker',name:'Trzcinowy Łowca',icon:'🦎',family:'Bestie',min:23,max:30,zone:'yellow',hp:178,atk:29,xp:315,gold:[24,44],weak:'trucizna'},
 {id:'rotCultist',name:'Kultysta Zgnilizny',icon:'🧟',family:'Ludzie',min:23,max:30,zone:'yellow',hp:170,atk:30,xp:325,gold:[26,46],weak:'ogień'},
 {id:'mossGolem',name:'Golem Torfowy',icon:'🪨',family:'Żywiołaki',min:25,max:31,zone:'yellow',hp:238,atk:31,xp:360,gold:[28,50],weak:'lód'},
 {id:'marshHag',name:'Wiedźma Moczaru',icon:'🧙‍♀️',family:'Demony',min:26,max:32,zone:'red',hp:205,atk:35,xp:410,gold:[32,58],weak:'światło'},
 {id:'blackrootGuardian',name:'Strażnik Czarnego Korzenia',icon:'🌳',family:'Natura',min:28,max:34,zone:'red',hp:285,atk:37,xp:470,gold:[38,66],weak:'ogień'},
 {id:'mireMother',name:'Matka Mgły',icon:'🕸️',family:'Bestie',min:30,max:36,zone:'red',hp:520,atk:45,xp:1100,gold:[120,190],weak:'ogień'},
{id:'ashScavenger',name:'Popielny Padlinożerca',icon:'🦴',family:'Bestie',min:31,max:36,zone:'yellow',hp:245,atk:36,xp:470,gold:[34,58],weak:'lód'},
 {id:'fireWasp',name:'Ognista Osa',icon:'🐝',family:'Owady',min:31,max:36,zone:'yellow',hp:205,atk:39,xp:450,gold:[32,56],weak:'lód'},
 {id:'cinderCultist',name:'Kultysta Żaru',icon:'🔥',family:'Ludzie',min:32,max:38,zone:'yellow',hp:252,atk:40,xp:510,gold:[36,62],weak:'przebicie'},
 {id:'emberWraith',name:'Widmo Popiołu',icon:'👻',family:'Zjawy',min:33,max:39,zone:'yellow',hp:238,atk:43,xp:540,gold:[38,66],weak:'światło'},
 {id:'slagGolem',name:'Golem Żużlowy',icon:'🪨',family:'Żywiołaki',min:34,max:40,zone:'red',hp:330,atk:44,xp:600,gold:[42,72],weak:'lód'},
 {id:'ashDrake',name:'Popielny Drak',icon:'🐉',family:'Bestie',min:36,max:42,zone:'red',hp:365,atk:49,xp:690,gold:[48,82],weak:'przebicie'},
 {id:'pyreKnight',name:'Rycerz Stosu',icon:'🛡️',family:'Nieumarli',min:37,max:43,zone:'red',hp:390,atk:50,xp:720,gold:[50,86],weak:'światło'},
 {id:'cinderMatriarch',name:'Matka Żaru',icon:'👑',family:'Demony',min:40,max:45,zone:'red',hp:720,atk:59,xp:1550,gold:[150,230],weak:'lód'},
 {id:'frostRaptor',name:'Mroźny Raptor',icon:'🦖',family:'Bestie',min:41,max:46,zone:'yellow',hp:360,atk:52,xp:760,gold:[54,90],weak:'ogień'},
 {id:'stormCultist',name:'Kultysta Burzy',icon:'⚡',family:'Ludzie',min:42,max:48,zone:'yellow',hp:345,atk:55,xp:810,gold:[58,96],weak:'obuch'},
 {id:'iceWraith',name:'Lodowe Widmo',icon:'❄️',family:'Zjawy',min:43,max:49,zone:'yellow',hp:330,atk:57,xp:840,gold:[60,100],weak:'ogień'},
 {id:'thunderGolem',name:'Golem Piorunów',icon:'🗿',family:'Żywiołaki',min:44,max:50,zone:'red',hp:455,atk:58,xp:920,gold:[66,108],weak:'obuch'},
 {id:'mountainTroll',name:'Troll Skalny',icon:'👹',family:'Bestie',min:45,max:51,zone:'red',hp:500,atk:61,xp:980,gold:[70,115],weak:'trucizna'},
 {id:'skySerpent',name:'Wąż Niebios',icon:'🐍',family:'Bestie',min:46,max:52,zone:'red',hp:430,atk:64,xp:1040,gold:[74,122],weak:'przebicie'},
 {id:'frozenKnight',name:'Zamarznięty Strażnik',icon:'⚔️',family:'Nieumarli',min:47,max:53,zone:'red',hp:470,atk:65,xp:1080,gold:[78,128],weak:'ogień'},
 {id:'tempestLord',name:'Władca Nawałnicy',icon:'🌩️',family:'Żywiołaki',min:50,max:55,zone:'black',hp:880,atk:74,xp:2200,gold:[210,310],weak:'obuch'}
];

export const ITEMS = {
 rustySword:{id:'rustySword',name:'Wyszczerbiony miecz',icon:'🗡️',type:'weapon',slot:'weapon',rarity:'common',value:18,power:4},
 hunterBow:{id:'hunterBow',name:'Łuk zwiadowcy',icon:'🏹',type:'weapon',slot:'weapon',rarity:'common',value:20,power:4},
 apprenticeStaff:{id:'apprenticeStaff',name:'Kostur ucznia',icon:'🪄',type:'weapon',slot:'weapon',rarity:'common',value:20,power:4},
 axe:{id:'axe',name:'Ciężki topór',icon:'🪓',type:'weapon',slot:'weapon',rarity:'common',value:20,power:5},
 leather:{id:'leather',name:'Skórzana kamizelka',icon:'🥋',type:'armor',slot:'armor',rarity:'common',value:16,armor:3},
 ironArmor:{id:'ironArmor',name:'Żelazny kirys',icon:'🛡️',type:'armor',slot:'armor',rarity:'rare',value:75,armor:9},
 scoutHood:{id:'scoutHood',name:'Kaptur zwiadowcy',icon:'🥷',type:'gear',slot:'helmet',rarity:'uncommon',value:34,armor:2,crit:1},
 ironHelm:{id:'ironHelm',name:'Żelazny hełm',icon:'⛑️',type:'gear',slot:'helmet',rarity:'rare',value:82,armor:6},
 leatherGloves:{id:'leatherGloves',name:'Rękawice wędrowca',icon:'🧤',type:'gear',slot:'gloves',rarity:'uncommon',value:28,armor:1,power:1},
 trailBoots:{id:'trailBoots',name:'Buty Zielonego Szlaku',icon:'🥾',type:'gear',slot:'boots',rarity:'uncommon',value:32,armor:1,crit:2},
 woodenShield:{id:'woodenShield',name:'Okrągła tarcza',icon:'🛡️',type:'gear',slot:'offhand',rarity:'uncommon',value:38,armor:4},
 blueBlade:{id:'blueBlade',name:'Ostrze Strażnika',icon:'⚔️',type:'weapon',slot:'weapon',rarity:'rare',value:110,power:14},
 forestBow:{id:'forestBow',name:'Łuk Zielonego Szlaku',icon:'🏹',type:'weapon',slot:'weapon',rarity:'rare',value:105,power:12,crit:2},
 arcaneStaff:{id:'arcaneStaff',name:'Kostur Runiczny',icon:'🪄',type:'weapon',slot:'weapon',rarity:'rare',value:115,power:13},
 shadowRing:{id:'shadowRing',name:'Pierścień Cienia',icon:'💍',type:'trinket',slot:'ring',rarity:'epic',value:260,crit:8},
 emberRing:{id:'emberRing',name:'Pierścień Żaru',icon:'💍',type:'trinket',slot:'ring',rarity:'rare',value:135,power:4,crit:2},
 wolfCharm:{id:'wolfCharm',name:'Wilczy amulet',icon:'📿',type:'trinket',slot:'amulet',rarity:'rare',value:95,crit:4,power:2},
 oldTalisman:{id:'oldTalisman',name:'Stary talizman',icon:'📿',type:'trinket',slot:'amulet',rarity:'uncommon',value:42,crit:2},
 potion:{id:'potion',name:'Mikstura życia',icon:'🧪',type:'consumable',rarity:'common',value:12,heal:55},
 strongPotion:{id:'strongPotion',name:'Większa mikstura życia',icon:'❤️‍🔥',type:'consumable',rarity:'rare',value:34,heal:130},
 manaPotion:{id:'manaPotion',name:'Mikstura many',icon:'🔷',type:'consumable',rarity:'common',value:14,mana:50},
 antidote:{id:'antidote',name:'Odtrutka',icon:'🍶',type:'consumable',rarity:'common',value:10},
 wolfPelt:{id:'wolfPelt',name:'Wilcza skóra',icon:'🧶',type:'material',rarity:'common',value:8},
 herb:{id:'herb',name:'Gorzki liść',icon:'🌿',type:'material',rarity:'common',value:4},
 moonHerb:{id:'moonHerb',name:'Księżycowe ziele',icon:'☘️',type:'material',rarity:'rare',value:10},
 bone:{id:'bone',name:'Kość nieumarłego',icon:'🦴',type:'material',rarity:'common',value:6},
 scrap:{id:'scrap',name:'Żelazny złom',icon:'🔩',type:'material',rarity:'common',value:6},
 crystal:{id:'crystal',name:'Odłamek kryształu',icon:'💎',type:'material',rarity:'rare',value:15},
 blackMedallion:{id:'blackMedallion',name:'Czarny medalion',icon:'📿',type:'quest',rarity:'epic',value:0},
 titanShard:{id:'titanShard',name:'Odłamek Tytana',icon:'🔶',type:'material',rarity:'legendary',value:90},
 stormCrown:{id:'stormCrown',name:'Korona Burz',icon:'👑',type:'gear',slot:'helmet',rarity:'legendary',value:480,armor:10,crit:5,power:5},
 cryptHeart:{id:'cryptHeart',name:'Serce Kurhanu',icon:'🫀',type:'trinket',slot:'amulet',rarity:'legendary',value:520,armor:5,crit:6,power:7},
 runeShard:{id:'runeShard',name:'Odłamek runiczny',icon:'🔹',type:'material',rarity:'uncommon',value:14},
 runePower:{id:'runePower',name:'Runa Mocy',icon:'🔴',type:'rune',rarity:'rare',value:70,runeKey:'power',runeValue:3},
 runeGuard:{id:'runeGuard',name:'Runa Straży',icon:'🔵',type:'rune',rarity:'rare',value:70,runeKey:'armor',runeValue:3},
 runePrecision:{id:'runePrecision',name:'Runa Precyzji',icon:'🟣',type:'rune',rarity:'rare',value:80,runeKey:'crit',runeValue:3},
 ravenBlade:{id:'ravenBlade',name:'Krucze Ostrze',icon:'🗡️',type:'weapon',slot:'weapon',rarity:'epic',value:260,power:18,crit:2,set:'raven'},
 ravenMail:{id:'ravenMail',name:'Kruczy Pancerz',icon:'🛡️',type:'armor',slot:'armor',rarity:'epic',value:250,armor:13,power:2,set:'raven'},
 ravenHelm:{id:'ravenHelm',name:'Kruczy Hełm',icon:'🪖',type:'gear',slot:'helmet',rarity:'epic',value:215,armor:8,crit:3,set:'raven'},
 wildBow:{id:'wildBow',name:'Łuk Dzikiego Szlaku',icon:'🏹',type:'weapon',slot:'weapon',rarity:'epic',value:255,power:16,crit:5,set:'wild'},
 wildHood:{id:'wildHood',name:'Kaptur Dzikiego Szlaku',icon:'🥷',type:'gear',slot:'helmet',rarity:'epic',value:205,armor:5,crit:5,set:'wild'},
 wildBoots:{id:'wildBoots',name:'Buty Dzikiego Szlaku',icon:'🥾',type:'gear',slot:'boots',rarity:'epic',value:190,armor:4,crit:4,power:2,set:'wild'},
 mireMoss:{id:'mireMoss',name:'Mech Moczaru',icon:'🌿',type:'material',rarity:'uncommon',value:13},
 bogAmber:{id:'bogAmber',name:'Bagienny Bursztyn',icon:'🟠',type:'material',rarity:'rare',value:28},
 wraithEssence:{id:'wraithEssence',name:'Esencja Topielca',icon:'💧',type:'material',rarity:'rare',value:32},
 mistBlade:{id:'mistBlade',name:'Ostrze Strażnika Mgieł',icon:'🗡️',type:'weapon',slot:'weapon',rarity:'epic',reqLevel:21,value:330,power:21,crit:4,set:'mist'},
 mistMail:{id:'mistMail',name:'Pancerz Strażnika Mgieł',icon:'🛡️',type:'armor',slot:'armor',rarity:'epic',reqLevel:21,value:320,armor:16,power:3,set:'mist'},
 mistHood:{id:'mistHood',name:'Kaptur Strażnika Mgieł',icon:'🥷',type:'gear',slot:'helmet',rarity:'epic',value:285,armor:8,crit:5,set:'mist'},
 mireCharm:{id:'mireCharm',name:'Amulet Zatopionego Dzwonu',icon:'📿',type:'trinket',slot:'amulet',rarity:'heroic',value:390,power:5,armor:4,crit:4}
};

export const SKILLS = {
 knight:[
  {id:'shield',branch:'Bastion',name:'Uderzenie tarczą',icon:'🛡️',req:1,cost:1,mana:8,kind:'damage',mult:1.25,desc:'125% obrażeń i osłabienie ataku przeciwnika.',debuff:0.15},
  {id:'fortress',branch:'Bastion',name:'Żelazna Forteca',icon:'🏰',req:3,cost:1,mana:12,kind:'guard',turns:2,requires:'shield',desc:'Przez 2 tury otrzymujesz o 45% mniej obrażeń.'},
  {id:'taunt',branch:'Bastion',name:'Prowokacja',icon:'📣',req:6,cost:2,mana:14,kind:'debuff',debuff:0.30,requires:'fortress',desc:'Mocno obniża atak przeciwnika na 3 tury.'},
  {id:'counter',branch:'Odwet',name:'Kontratak',icon:'↩️',req:4,cost:1,mana:10,kind:'damage',mult:1.5,requires:'shield',desc:'150% obrażeń. Bezpieczny, ciężki kontratak.'},
  {id:'breaker',branch:'Odwet',name:'Łamacz Gardy',icon:'🔨',req:8,cost:2,mana:18,kind:'damage',mult:2.0,requires:'counter',desc:'200% obrażeń. Cios przeznaczony na elity i bossów.'},
  {id:'lastStand',branch:'Odwet',name:'Ostatni Bastion',icon:'⚜️',req:12,cost:2,mana:22,kind:'guard',turns:3,requires:'breaker',desc:'Potężna obrona przez 3 tury.'}
 ],
 mage:[
  {id:'fire',branch:'Ogień',name:'Ognisty pocisk',icon:'🔥',req:1,cost:1,mana:12,kind:'damage',mult:1.55,desc:'155% obrażeń magicznych.'},
  {id:'frost',branch:'Lód',name:'Lodowa pieczęć',icon:'❄️',req:3,cost:1,mana:16,kind:'damage',mult:1.20,desc:'120% obrażeń i osłabienie przeciwnika.',debuff:0.20},
  {id:'elemental',branch:'Arkanum',name:'Eksplozja Żywiołów',icon:'💥',req:6,cost:2,mana:28,kind:'damage',mult:2.35,requires:'fire',desc:'Potężny atak za dużą ilość many.'},
  {id:'spark',branch:'Arkanum',name:'Łańcuch Iskier',icon:'⚡',req:4,cost:1,mana:15,kind:'multi',hits:2,mult:.9,requires:'fire',desc:'Dwa magiczne trafienia po 90%.'},
  {id:'iceArmor',branch:'Lód',name:'Pancerz Lodu',icon:'🧊',req:7,cost:2,mana:20,kind:'guard',turns:2,requires:'frost',desc:'Zmniejsza obrażenia przez 2 tury.'},
  {id:'meteor',branch:'Ogień',name:'Meteor',icon:'☄️',req:12,cost:2,mana:36,kind:'damage',mult:3.0,requires:'elemental',desc:'300% obrażeń. Drogi, kończący czar.'}
 ],
 hunter:[
  {id:'double',branch:'Strzelectwo',name:'Podwójny strzał',icon:'🏹',req:1,cost:1,mana:10,kind:'multi',hits:2,mult:0.82,desc:'Dwa trafienia po 82% obrażeń.'},
  {id:'mark',branch:'Strzelectwo',name:'Znak łowcy',icon:'🎯',req:3,cost:1,mana:12,kind:'mark',turns:3,requires:'double',desc:'Przez 3 tury +25% szansy na krytyk.'},
  {id:'petStrike',branch:'Bestia',name:'Skoordynowany Strzał',icon:'🐺',req:6,cost:2,mana:18,kind:'pet',mult:1.45,desc:'145% obrażeń, a aktywny pupil zawsze atakuje.'},
  {id:'eagleEye',branch:'Strzelectwo',name:'Sokole Oko',icon:'🦅',req:7,cost:2,mana:18,kind:'damage',mult:1.7,critBonus:30,requires:'mark',desc:'170% obrażeń i wysoka szansa na krytyk.'},
  {id:'pack',branch:'Bestia',name:'Zew Stada',icon:'🐾',req:9,cost:2,mana:20,kind:'pet',mult:1.6,requires:'petStrike',desc:'Silny wspólny atak z chowańcem.'},
  {id:'volley',branch:'Przetrwanie',name:'Salwa',icon:'🌧️',req:12,cost:2,mana:26,kind:'multi',hits:3,mult:.76,requires:'eagleEye',desc:'Trzy szybkie trafienia po 76%.'}
 ],
 berserker:[
  {id:'rage',branch:'Furia',name:'Furia',icon:'😡',req:1,cost:1,mana:6,kind:'rage',desc:'Cios 120–190% zależnie od utraconego HP.'},
  {id:'cleave',branch:'Rzeź',name:'Rozłupanie',icon:'🪓',req:3,cost:1,mana:10,kind:'damage',mult:1.75,desc:'Silny cios za 175% obrażeń.'},
  {id:'blood',branch:'Rzeź',name:'Krwawy Taniec',icon:'🩸',req:6,cost:2,mana:16,kind:'multi',hits:3,mult:0.72,requires:'cleave',desc:'Trzy szybkie ciosy po 72% obrażeń.'},
  {id:'roar',branch:'Furia',name:'Ryk Wojenny',icon:'📢',req:5,cost:1,mana:8,kind:'debuff',debuff:.22,requires:'rage',desc:'Osłabia atak przeciwnika.'},
  {id:'execution',branch:'Rzeź',name:'Egzekucja',icon:'⚔️',req:9,cost:2,mana:15,kind:'damage',mult:2.25,requires:'blood',desc:'225% obrażeń.'},
  {id:'berserk',branch:'Furia',name:'Szał Berserkera',icon:'🔥',req:12,cost:2,mana:18,kind:'rage',requires:'roar',desc:'Potężny cios skalujący się z utraconym HP.'}
 ],
 ranger:[
  {id:'poison',branch:'Trucizny',name:'Zatruty grot',icon:'☠️',req:1,cost:1,mana:10,kind:'poison',mult:1.05,turns:3,desc:'105% obrażeń i trucizna przez 3 tury.'},
  {id:'trap',branch:'Pułapki',name:'Leśna pułapka',icon:'🪤',req:3,cost:1,mana:12,kind:'debuff',debuff:0.25,desc:'Obniża atak przeciwnika na 3 tury.'},
  {id:'destiny',branch:'Trucizny',name:'Strzała Przeznaczenia',icon:'🌠',req:6,cost:2,mana:20,kind:'damage',mult:2.0,critBonus:20,requires:'poison',desc:'200% obrażeń i +20% szansy na krytyk.'},
  {id:'vine',branch:'Pułapki',name:'Pnącza',icon:'🌱',req:6,cost:1,mana:14,kind:'debuff',debuff:.32,requires:'trap',desc:'Mocne osłabienie przeciwnika.'},
  {id:'spirit',branch:'Duch Natury',name:'Duch Lasu',icon:'🦊',req:8,cost:2,mana:18,kind:'pet',mult:1.5,desc:'Wspólny atak z aktywnym chowańcem.'},
  {id:'venomRain',branch:'Trucizny',name:'Deszcz Jadu',icon:'🌧️',req:12,cost:2,mana:26,kind:'poison',mult:1.65,turns:4,requires:'destiny',desc:'Silny strzał i dłuższa trucizna.'}
 ]
};

export const PETS = {
 youngWolf:{id:'youngWolf',name:'Młody Wilk',icon:'🐺',power:7,skill:'Rozszarpanie',passive:'+ regularne ataki',desc:'Wierny kompan. Często dobija osłabionych przeciwników.'},
 raven:{id:'raven',name:'Kruk',icon:'🐦‍⬛',power:6,crit:4,skill:'Pikowanie',passive:'+4% krytyka',desc:'Zwiększa szansę na krytyk i atakuje z powietrza.'},
 forestLynx:{id:'forestLynx',name:'Ryś Leśny',icon:'🐈',power:10,skill:'Skok',passive:'+ obrażenia',desc:'Rzadki, ofensywny pupil Tropicieli i Łowców.'},
 emberling:{id:'emberling',name:'Żaroptak',icon:'🐦',power:12,crit:2,skill:'Iskra',passive:'+2% krytyka',desc:'Rzadki ptak znaleziony przy czerwonych strefach.'},
 shadowFox:{id:'shadowFox',name:'Lis Cienia',icon:'🦊',power:9,crit:5,skill:'Zniknięcie',passive:'+5% krytyka',desc:'Niezwykle rzadki chowaniec związany z ruinami.'},
 mireLynx:{id:'mireLynx',name:'Ryś Mgieł',icon:'🐈‍⬛',power:14,crit:6,skill:'Skok zza mgły',passive:'+6% krytyka',desc:'Rzadki drapieżnik Mokradeł Echa. Atakuje z zasadzki i wzmacnia krytyki.'},
 cinderHound:{id:'cinderHound',name:'Ogar Popiołu',icon:'🐕',power:17,crit:5,skill:'Skok przez żar',passive:'+5% krytyka',desc:'Drapieżnik Popielnych Pustkowi. Wyczuwa elity i atakuje bez ostrzeżenia.'},
 stormHawk:{id:'stormHawk',name:'Jastrząb Burzy',icon:'🦅',power:20,crit:7,skill:'Pikowanie gromu',passive:'+7% krytyka',desc:'Rzadki ptak Rozbitych Szczytów. Najsilniejszy chowaniec eksploracyjny tej części świata.'}
};

export const RECIPES = [
 {id:'potion',station:'alchemist',name:'Mikstura życia',result:'potion',qty:1,ingredients:{herb:2}},
 {id:'manaPotion',station:'alchemist',name:'Mikstura many',result:'manaPotion',qty:1,ingredients:{herb:1,crystal:1}},
 {id:'strongPotion',station:'alchemist',name:'Większa mikstura życia',result:'strongPotion',qty:1,ingredients:{herb:2,moonHerb:1}},
 {id:'antidote',station:'alchemist',name:'Odtrutka',result:'antidote',qty:1,ingredients:{herb:1,bone:1}},
 {id:'runePower',station:'smith',name:'Runa Mocy',result:'runePower',qty:1,ingredients:{runeShard:2,crystal:1}},
 {id:'runeGuard',station:'smith',name:'Runa Straży',result:'runeGuard',qty:1,ingredients:{runeShard:2,scrap:2}},
 {id:'runePrecision',station:'smith',name:'Runa Precyzji',result:'runePrecision',qty:1,ingredients:{runeShard:2,moonHerb:1}},
 {id:'ravenBlade',station:'smith',name:'Krucze Ostrze',result:'ravenBlade',qty:1,ingredients:{scrap:5,crystal:2,bone:2}},
 {id:'ravenMail',station:'smith',name:'Kruczy Pancerz',result:'ravenMail',qty:1,ingredients:{scrap:6,wolfPelt:3,bone:2}},
 {id:'ravenHelm',station:'smith',name:'Kruczy Hełm',result:'ravenHelm',qty:1,ingredients:{scrap:4,crystal:1,bone:2}},
 {id:'wildBow',station:'smith',name:'Łuk Dzikiego Szlaku',result:'wildBow',qty:1,ingredients:{wolfPelt:4,crystal:2,scrap:2}},
 {id:'wildHood',station:'smith',name:'Kaptur Dzikiego Szlaku',result:'wildHood',qty:1,ingredients:{wolfPelt:3,moonHerb:2}},
 {id:'wildBoots',station:'smith',name:'Buty Dzikiego Szlaku',result:'wildBoots',qty:1,ingredients:{wolfPelt:3,herb:4,scrap:1}},
 {id:'mistBlade',station:'smith',name:'Ostrze Strażnika Mgieł',result:'mistBlade',qty:1,ingredients:{bogAmber:3,wraithEssence:2,scrap:4}},
 {id:'mistMail',station:'smith',name:'Pancerz Strażnika Mgieł',result:'mistMail',qty:1,ingredients:{mireMoss:5,bogAmber:2,scrap:5}},
 {id:'mistHood',station:'smith',name:'Kaptur Strażnika Mgieł',result:'mistHood',qty:1,ingredients:{mireMoss:3,wraithEssence:2,moonHerb:1}},
{id:'ashBlade',station:'smith',name:'Ostrze Popielnej Straży',result:'ashBlade',qty:1,ingredients:{ashGlass:3,emberCore:2,charredIron:5}},
 {id:'ashMail',station:'smith',name:'Pancerz Popielnej Straży',result:'ashMail',qty:1,ingredients:{charredIron:7,ashGlass:2,scrap:5}},
 {id:'ashHelm',station:'smith',name:'Hełm Popielnej Straży',result:'ashHelm',qty:1,ingredients:{charredIron:5,emberCore:1,crystal:2}},
 {id:'stormSpear',station:'smith',name:'Włócznia Nawałnicy',result:'stormSpear',qty:1,ingredients:{skySteel:3,stormFeather:2,frostCrystal:2}},
 {id:'stormMail',station:'smith',name:'Pancerz Nawałnicy',result:'stormMail',qty:1,ingredients:{skySteel:4,frostCrystal:3,scrap:6}},
 {id:'stormHelm',station:'smith',name:'Korona Nawałnicy',result:'stormHelm',qty:1,ingredients:{skySteel:2,stormFeather:3,crystal:3}}
];

export const DUNGEONS = [
 {id:'trainingCellar',name:'Piwnica Pod Krukiem',icon:'🪜',x:-75,y:35,min:1,boss:'rat',desc:'Stara piwnica pod zapleczem karczmy. Idealne miejsce na pierwszą wyprawę: kilka korytarzy, prosta pułapka i zdziczały szczur, który zrobił tu legowisko.'},
 {id:'oldCrypt',name:'Stara Krypta',icon:'🕳️',x:185,y:-125,min:7,boss:'skeleton',desc:'Wilgotne podziemia pełne kości, run, pułapek i bocznych komnat.'},
 {id:'forgottenTower',name:'Zapomniana Wieża',icon:'🗼',x:-300,y:-170,min:18,boss:'cultist',desc:'Wieża starego zakonu. W środku słychać szepty.'},
 {id:'beastLair',name:'Legowisko Bestii',icon:'🦴',x:320,y:245,min:45,boss:'wyvern',desc:'Czarna strefa. W powietrzu czuć popiół i siarkę.'},
 {id:'sunkenChapel',name:'Zatopiona Kaplica',icon:'⛪',x:690,y:-310,min:23,boss:'bogWraith',desc:'Dzwon kaplicy słychać spod czarnej wody. W środku czają się topielcy i zgniłe korzenie.'},
 {id:'witchBarrow',name:'Kopiec Wiedźmy',icon:'🕯️',x:810,y:250,min:27,boss:'marshHag',desc:'Kamienny kopiec otoczony trzcinami. Runy na wejściu są świeże, choć miejsce wygląda na martwe od stuleci.'},
 {id:'blackrootKeep',name:'Twierdza Czarnego Korzenia',icon:'🌑',x:930,y:-40,min:30,boss:'mireMother',desc:'Serce Mokradeł Echa. Korzenie oplatają kamień, a mgła nie porusza się nawet przy silnym wietrze.'},
{id:'emberMine',name:'Kopalnia Żaru',icon:'⛏️',x:1165,y:-265,min:33,boss:'slagGolem',desc:'Korytarze pełne gorącego pyłu, żużlu i pękniętych pieców. W głębi porusza się coś z kamienia i ognia.'},
 {id:'ashenCitadel',name:'Popielna Cytadela',icon:'🏰',x:1360,y:40,min:40,boss:'cinderMatriarch',desc:'Twierdza kultu Żaru. W jej centrum płonie ogień, którego nikt nie podtrzymuje.'},
 {id:'frostVault',name:'Krypta Mrozu',icon:'🧊',x:1535,y:-250,min:43,boss:'iceWraith',desc:'Zamarznięte podziemia dawnych strażników. Ciszę przerywa tylko pękający lód.'},
 {id:'tempestSpire',name:'Iglica Nawałnicy',icon:'🗼',x:1810,y:55,min:50,boss:'tempestLord',desc:'Najwyższa wieża Rozbitych Szczytów. Pioruny uderzają w nią nawet przy czystym niebie.'}
];

export const QUESTS = [
 {id:'q1',chapter:'Cienie nad Doliną',name:'Pierwszy krok',level:1,desc:'Karczmarz prosi, abyś sprawdził drogę za wioską.',steps:[{type:'move',target:60,label:'Oddal się 60 m od wioski'},{type:'kill',target:'any',count:2,label:'Pokonaj 2 stworzenia'}],xp:150,gold:25},
 {id:'q2',chapter:'Cienie nad Doliną',name:'Zaginiona owca',level:2,desc:'Z pastwiska zniknęła owca. Ślady wyglądają na wilcze, ale coś się nie zgadza.',steps:[{type:'discover',target:'pasture',label:'Zbadaj pastwisko i ślady'},{type:'story',target:'q2',label:'Zdecyduj, jak potraktować trop wilków'}],xp:260,gold:35},
 {id:'q3',chapter:'Cienie nad Doliną',name:'Wilcza jama',level:3,desc:'Ranne wilki nie wyglądają na winnych. Przy jamie znajdujesz ślady butów i skrawki worków.',steps:[{type:'discover',target:'wolfDen',label:'Odnajdź wilczą jamę'},{type:'story',target:'q3',label:'Połącz znalezione ślady'}],xp:420,gold:55},
 {id:'q4',chapter:'Cienie nad Doliną',name:'Mapa',level:4,desc:'Fragment mapy wskazuje stare ruiny.',steps:[{type:'discover',target:'oldRuins',label:'Odkryj Stare Ruiny'}],xp:500,gold:70},
 {id:'q5',chapter:'Cienie nad Doliną',name:'Nie jesteśmy sami',level:4,desc:'Obserwuj ruiny i ustal, dokąd gobliny prowadzą łupy.',steps:[{type:'discover',target:'watchPoint',label:'Dotrzyj do punktu obserwacyjnego'}],xp:560,gold:75},
 {id:'q6',chapter:'Cienie nad Doliną',name:'Obserwator',level:5,desc:'Obóz żyje własnym rytmem. Możesz zachować dystans albo zaryzykować bliższe podejście.',steps:[{type:'discover',target:'goblinCamp',label:'Podejdź do obozu goblinów'},{type:'story',target:'q6',label:'Wybierz sposób obserwacji obozu'}],xp:650,gold:90},
 {id:'q7',chapter:'Cienie nad Doliną',name:'Zaginiony myśliwy',level:6,desc:'Myśliwy nie wrócił z patrolu. Na szlaku są ślady po walce i zerwany pasek od kołczanu.',steps:[{type:'discover',target:'hunterTrail',label:'Odnajdź ślady myśliwego'}],xp:780,gold:110},
 {id:'q8',chapter:'Cienie nad Doliną',name:'Ten, który uciekł',level:6,desc:'Odnajdź rannego myśliwego i eskortuj go do bezpiecznego miejsca.',steps:[{type:'discover',target:'woundedHunter',label:'Odnajdź rannego myśliwego'}],xp:850,gold:115},
 {id:'q9',chapter:'Cienie nad Doliną',name:'Ruiny',level:7,desc:'Zbadaj dziedziniec, wieżę i podziemia ruin.',steps:[{type:'dungeon',target:'oldCrypt',label:'Ukończ Starą Kryptę'}],xp:1050,gold:150},
 {id:'q10',chapter:'Cienie nad Doliną',name:'Stary znak',level:7,desc:'Pustelnik rozpoznaje symbol, ale chce wiedzieć, czy jesteś gotów zaufać jego wersji wydarzeń.',steps:[{type:'discover',target:'hermit',label:'Odnajdź pustelnika'},{type:'story',target:'q10',label:'Zdecyduj, co zrobić z wiedzą pustelnika'}],xp:900,gold:120},
 {id:'q11',chapter:'Cienie nad Doliną',name:'Pod ruinami',level:8,desc:'Wróć do ruin i znajdź więźnia.',steps:[{type:'dungeon',target:'oldCrypt',label:'Przeszukaj podziemia'}],xp:1200,gold:180},
 {id:'q12',chapter:'Cienie nad Doliną',name:'Nocny gość',level:8,desc:'Spotkanie odbywa się tylko po zmroku. W cieniu możesz zostać obserwatorem albo ruszyć za nieznajomym.',steps:[{type:'condition',target:'night',label:'Poczekaj do nocy'},{type:'discover',target:'nightGuest',label:'Dotrzyj do punktu obserwacji'},{type:'story',target:'q12',label:'Zdecyduj, jak zakończyć obserwację'}],xp:1350,gold:200},
 {id:'q13',chapter:'Cienie nad Doliną',name:'Atak na wioskę',level:9,desc:'Gobliny ruszyły na wioskę. Broń mieszkańców.',steps:[{type:'kill',target:'any',count:5,label:'Pokonaj napastników'}],xp:1600,gold:250},
 {id:'q14',chapter:'Cienie nad Doliną',name:'Czarny medalion',level:9,desc:'Zanieś tajemniczy medalion pustelnikowi.',steps:[{type:'discover',target:'hermit',label:'Zanieś Czarny medalion pustelnikowi'}],xp:1500,gold:220},
 {id:'q15',chapter:'Cienie nad Doliną',name:'Droga na północ',level:10,desc:'Pierwszy rozdział dobiega końca. Otwiera się nowy region.',steps:[{type:'move',target:350,label:'Oddal się 350 m od wioski'}],xp:2200,gold:350},
 {id:'q16',chapter:'Północne Rubieże',name:'Za granicą doliny',level:11,desc:'Droga prowadzi w chłodniejsze i znacznie bardziej niebezpieczne ziemie.',steps:[{type:'move',target:430,label:'Dotrzyj na północne rubieże'}],xp:2400,gold:380},
 {id:'q17',chapter:'Północne Rubieże',name:'Obóz bez ognia',level:11,desc:'Namioty stoją otwarte, jedzenie zamarzło na stołach, a ślady prowadzą w dwie strony.',steps:[{type:'discover',target:'northCamp',label:'Zbadaj Obóz Północny'},{type:'story',target:'q17',label:'Wybierz, czego szukać najpierw'}],xp:2550,gold:400},
 {id:'q18',chapter:'Północne Rubieże',name:'Ciężkie kroki',level:12,desc:'Ślady przy obozie są zbyt wielkie, by należały do człowieka.',steps:[{type:'kill',target:'ogre',count:2,label:'Pokonaj 2 ogry'}],xp:2800,gold:440},
 {id:'q19',chapter:'Północne Rubieże',name:'Wieża w śniegu',level:13,desc:'Stary trakt prowadzi do zapomnianej wieży zakonu.',steps:[{type:'dungeon',target:'forgottenTower',label:'Ukończ Zapomnianą Wieżę'}],xp:3300,gold:520},
 {id:'q20',chapter:'Północne Rubieże',name:'Znak mrozu',level:14,desc:'W ruinach znaleziono symbol, który odpowiada znakom ze starego sanktuarium.',steps:[{type:'discover',target:'coldShrine',label:'Odnajdź Mroźne Sanktuarium'},{type:'kill',target:'any',count:5,label:'Przetrwaj drogę przez północ'}],xp:3900,gold:650},
 {id:'q21',chapter:'Mokradła Echa',name:'Droga przez trzcinowiska',level:21,desc:'Za północnym traktem ziemia zapada się w wodę. Stary przewodnik oznaczył wejście na mokradła.',steps:[{type:'discover',target:'mireGate',label:'Odnajdź Bramę Trzcin'}],xp:4300,gold:680},
 {id:'q22',chapter:'Mokradła Echa',name:'Wioska bez głosów',level:21,desc:'Domy stoją otwarte, na stole stygnie czarna woda, a na placu nie ma ani jednego ciała.',steps:[{type:'discover',target:'drownedVillage',label:'Odkryj Zatopioną Wioskę'},{type:'story',target:'q22',label:'Zdecyduj, jak przeszukać wioskę'}],xp:4500,gold:700},
 {id:'q23',chapter:'Mokradła Echa',name:'Co porusza wodę',level:22,desc:'Pod powierzchnią coś śledzi każdy krok. Trzeba oczyścić drogę.',steps:[{type:'kill',target:'mireCrawler',count:4,label:'Pokonaj 4 Pełzacze Moczaru'}],xp:4700,gold:730},
 {id:'q24',chapter:'Mokradła Echa',name:'Dzwon spod powierzchni',level:23,desc:'Dzwon odzywa się nocą albo wtedy, gdy mgła schodzi nisko nad wodę.',steps:[{type:'condition',target:'nightOrFog',label:'Poczekaj na noc albo mgłę'},{type:'discover',target:'sunkenBell',label:'Odnajdź Zatopiony Dzwon'},{type:'story',target:'q24',label:'Zdecyduj, czy odpowiedzieć na wezwanie'}],xp:4900,gold:760},
 {id:'q25',chapter:'Mokradła Echa',name:'Zatopiona kaplica',level:23,desc:'Wejdź do kaplicy i sprawdź, kto nadal wprawia dzwon w ruch.',steps:[{type:'dungeon',target:'sunkenChapel',label:'Ukończ Zatopioną Kaplicę'}],xp:5400,gold:820},
 {id:'q26',chapter:'Mokradła Echa',name:'Szepty w trzcinach',level:24,desc:'Głosy prowadzą w głąb bagien. Nie wszystkie należą do żywych.',steps:[{type:'discover',target:'whisperMarsh',label:'Dotrzyj na Szeptane Rozlewisko'},{type:'kill',target:'bogWraith',count:2,label:'Pokonaj 2 Zjawy Topielców'}],xp:5600,gold:850},
 {id:'q27',chapter:'Mokradła Echa',name:'Totemy wiedźmy',level:25,desc:'Kościane znaki są świeże. Można je zniszczyć albo spróbować odczytać rytuał.',steps:[{type:'discover',target:'witchTotem',label:'Zbadaj Totemy Wiedźmy'},{type:'story',target:'q27',label:'Zdecyduj, co zrobić z totemami'}],xp:5800,gold:880},
 {id:'q28',chapter:'Mokradła Echa',name:'Łowcy pod sitowiem',level:25,desc:'Trzcinowi Łowcy patrolują ścieżki i nie pozwalają zbliżyć się do kopca.',steps:[{type:'kill',target:'fenStalker',count:3,label:'Pokonaj 3 Trzcinowych Łowców'}],xp:6100,gold:920},
 {id:'q29',chapter:'Mokradła Echa',name:'Czarny korzeń',level:26,desc:'W obozie kultystów znajdujesz więźnia i ślady rytuału prowadzące dalej w bagno.',steps:[{type:'discover',target:'blackrootCamp',label:'Odnajdź Obóz Czarnego Korzenia'},{type:'kill',target:'rotCultist',count:1,label:'Pokonaj strażnika obozu'},{type:'story',target:'q29',label:'Zdecyduj, co zrobić po walce'}],xp:6400,gold:960},
 {id:'q30',chapter:'Mokradła Echa',name:'Kopiec wiedźmy',level:27,desc:'Źródłem rytuałów jest kamienny kopiec pośrodku mokradeł.',steps:[{type:'dungeon',target:'witchBarrow',label:'Ukończ Kopiec Wiedźmy'}],xp:7000,gold:1050},
 {id:'q31',chapter:'Mokradła Echa',name:'Stary trakt',level:27,desc:'Za kopcem zachował się brukowany trakt prowadzący do miejsca, którego nie ma na mapach.',steps:[{type:'discover',target:'oldCauseway',label:'Odnajdź Stary Trakt'}],xp:6600,gold:980},
 {id:'q32',chapter:'Mokradła Echa',name:'Serce torfowiska',level:28,desc:'Golemy wyrywają się z ziemi w pobliżu najstarszych korzeni.',steps:[{type:'kill',target:'mossGolem',count:2,label:'Pokonaj 2 Golemy Torfowe'}],xp:7200,gold:1080},
 {id:'q33',chapter:'Mokradła Echa',name:'Ołtarz mgły',level:29,desc:'Ołtarz ujawnia prawdziwy kształt dopiero po zmroku albo w naturalnej mgle.',steps:[{type:'condition',target:'nightOrFog',label:'Poczekaj na noc albo mgłę'},{type:'discover',target:'fogAltar',label:'Odkryj Ołtarz Mgły'},{type:'story',target:'q33',label:'Wybierz sposób przełamania rytuału'}],xp:7500,gold:1120},
 {id:'q34',chapter:'Mokradła Echa',name:'Strażnik korzeni',level:29,desc:'Drogi do twierdzy broni istota z drewna, torfu i kości.',steps:[{type:'kill',target:'blackrootGuardian',count:1,label:'Pokonaj Strażnika Czarnego Korzenia'},{type:'discover',target:'blackrootGate',label:'Odnajdź Bramę Twierdzy'}],xp:7900,gold:1180},
 {id:'q35',chapter:'Mokradła Echa',name:'Matka Mgły',level:30,desc:'Po zwycięstwie nad Matką Mgły pozostaje decyzja: zniszczyć serce bagna czy je zapieczętować.',steps:[{type:'dungeon',target:'blackrootKeep',label:'Ukończ Twierdzę Czarnego Korzenia'},{type:'story',target:'q35',label:'Podejmij decyzję o losie serca bagna'}],xp:9800,gold:1500},
{id:'q36',chapter:'Popielne Pustkowia',name:'Droga w popiół',level:31,desc:'Za mokradłami ziemia robi się sucha, a wiatr niesie drobny czarny pył. Pierwszy kamień graniczny stoi przy Popielnej Bramie.',steps:[{type:'discover',target:'ashGate',label:'Odnajdź Popielną Bramę'}],xp:10400,gold:1580},
 {id:'q37',chapter:'Popielne Pustkowia',name:'Ogień pod stopami',level:32,desc:'Z pęknięć w ziemi wylatują roje rozgrzanych owadów.',steps:[{type:'kill',target:'fireWasp',count:3,label:'Pokonaj 3 Ogniste Osy'}],xp:11000,gold:1650},
 {id:'q38',chapter:'Popielne Pustkowia',name:'Kopalnia bez górników',level:33,desc:'Stary szyb wciąż świeci od środka. Nikt nie pracował tu od lat.',steps:[{type:'discover',target:'emberMineGate',label:'Odnajdź wejście do Kopalni Żaru'},{type:'dungeon',target:'emberMine',label:'Ukończ Kopalnię Żaru'}],xp:11800,gold:1740},
 {id:'q39',chapter:'Popielne Pustkowia',name:'Czarny dym',level:34,desc:'Na horyzoncie widać obóz kultystów. Dym nie rozprasza się nawet przy silnym wietrze.',steps:[{type:'discover',target:'cinderCamp',label:'Odkryj Obóz Żaru'},{type:'kill',target:'cinderCultist',count:3,label:'Pokonaj 3 Kultystów Żaru'}],xp:12400,gold:1820},
 {id:'q40',chapter:'Popielne Pustkowia',name:'Szept w popiele',level:35,desc:'Nocą popiół układa się w ślady prowadzące do starego sanktuarium.',steps:[{type:'condition',target:'nightOrFog',label:'Poczekaj na noc albo mgłę'},{type:'discover',target:'ashShrine',label:'Odnajdź Sanktuarium Popiołu'}],xp:13200,gold:1920},
 {id:'q41',chapter:'Popielne Pustkowia',name:'Żelazny deszcz',level:36,desc:'Golemy wynoszą z ziemi rozgrzane bryły metalu i zrzucają je na szlak.',steps:[{type:'kill',target:'slagGolem',count:2,label:'Pokonaj 2 Golemy Żużlowe'}],xp:14000,gold:2020},
 {id:'q42',chapter:'Popielne Pustkowia',name:'Spalony sztandar',level:37,desc:'Przy ruinach fortu wiszą sztandary dawnej straży. Ktoś wypalił na nich nowy symbol.',steps:[{type:'discover',target:'charredFort',label:'Odkryj Spalony Fort'}],xp:14700,gold:2120},
 {id:'q43',chapter:'Popielne Pustkowia',name:'Polowanie na draki',level:38,desc:'Popielne draki atakują karawany przechodzące przez pustkowia.',steps:[{type:'kill',target:'ashDrake',count:2,label:'Pokonaj 2 Popielne Draki'}],xp:15500,gold:2220},
 {id:'q44',chapter:'Popielne Pustkowia',name:'Rycerze stosu',level:39,desc:'Przed cytadelą stoją zbroje, które dawno powinny być puste.',steps:[{type:'discover',target:'ashenCitadelGate',label:'Odnajdź Bramę Popielnej Cytadeli'},{type:'kill',target:'pyreKnight',count:2,label:'Pokonaj 2 Rycerzy Stosu'}],xp:16400,gold:2340},
 {id:'q45',chapter:'Popielne Pustkowia',name:'Matka Żaru',level:40,desc:'W centrum cytadeli płonie serce pustkowi. Po walce zdecydujesz, czy zgasić je na zawsze, czy przejąć jego moc.',steps:[{type:'dungeon',target:'ashenCitadel',label:'Ukończ Popielną Cytadelę'},{type:'story',target:'q45',label:'Zdecyduj o losie Serca Żaru'}],xp:18400,gold:2700},
 {id:'q46',chapter:'Rozbite Szczyty',name:'Wysoka przełęcz',level:41,desc:'Droga wspina się ponad chmury. Pierwszy obóz kartografów leży przy Kamiennej Przełęczy.',steps:[{type:'discover',target:'peakGate',label:'Dotrzyj do Kamiennej Przełęczy'},{type:'story',target:'q46',label:'Zdecyduj, komu pomóc na przełęczy'}],xp:19000,gold:2800},
 {id:'q47',chapter:'Rozbite Szczyty',name:'Łowcy lodu',level:42,desc:'Mroźne drapieżniki polują między skałami i zepchnęły podróżnych z głównego traktu.',steps:[{type:'kill',target:'frostRaptor',count:3,label:'Pokonaj 3 Mroźne Raptory'}],xp:19800,gold:2920},
 {id:'q48',chapter:'Rozbite Szczyty',name:'Krypta ciszy',level:43,desc:'Pod lodowcem znajduje się wejście do starej krypty strażników.',steps:[{type:'discover',target:'frostVaultGate',label:'Odnajdź Kryptę Mrozu'},{type:'dungeon',target:'frostVault',label:'Ukończ Kryptę Mrozu'}],xp:20700,gold:3040},
 {id:'q49',chapter:'Rozbite Szczyty',name:'Wyznawcy burzy',level:44,desc:'Na skalnej półce kult odprawia rytuały przyciągające pioruny.',steps:[{type:'discover',target:'stormCamp',label:'Odkryj Obóz Burzy'},{type:'kill',target:'stormCultist',count:3,label:'Pokonaj 3 Kultystów Burzy'}],xp:21600,gold:3160},
 {id:'q50',chapter:'Rozbite Szczyty',name:'Zamarznięta przysięga',level:45,desc:'W lodzie tkwi posąg rycerza. Głos spod hełmu prosi o uwolnienie albo dokończenie dawnej przysięgi.',steps:[{type:'discover',target:'frozenMonument',label:'Odnajdź Zamarznięty Pomnik'},{type:'story',target:'q50',label:'Zdecyduj o losie strażnika'}],xp:22600,gold:3300},
 {id:'q51',chapter:'Rozbite Szczyty',name:'Kamienie piorunów',level:46,desc:'Żywiołaki gromadzą energię przy wysokich menhirach.',steps:[{type:'kill',target:'thunderGolem',count:2,label:'Pokonaj 2 Golemy Piorunów'}],xp:23600,gold:3440},
 {id:'q52',chapter:'Rozbite Szczyty',name:'Krawędź nieba',level:47,desc:'Kamienny most kończy się nad przepaścią, ale stare runy wskazują dalszą drogę.',steps:[{type:'discover',target:'skyBridge',label:'Odnajdź Most Niebios'}],xp:24600,gold:3580},
 {id:'q53',chapter:'Rozbite Szczyty',name:'Wąż nad chmurami',level:48,desc:'Węże Niebios przecinają szlak między mostem a iglicą.',steps:[{type:'kill',target:'skySerpent',count:2,label:'Pokonaj 2 Węże Niebios'}],xp:25700,gold:3720},
 {id:'q54',chapter:'Rozbite Szczyty',name:'Iglica w burzy',level:49,desc:'Wejście do iglicy ujawnia się najlepiej podczas złej pogody.',steps:[{type:'condition',target:'badWeather',label:'Poczekaj na mgłę, deszcz albo burzę'},{type:'discover',target:'tempestSpireGate',label:'Odnajdź Bramę Iglicy Nawałnicy'}],xp:26800,gold:3880},
 {id:'q55',chapter:'Rozbite Szczyty',name:'Władca Nawałnicy',level:50,desc:'Na szczycie iglicy czeka istota, która steruje burzami regionu. Po zwycięstwie zdecydujesz, co zrobić z Sercem Nawałnicy.',steps:[{type:'dungeon',target:'tempestSpire',label:'Ukończ Iglicę Nawałnicy'},{type:'story',target:'q55',label:'Zdecyduj o losie Serca Nawałnicy'}],xp:31000,gold:4600}
];

export const BUILDINGS = [
 {id:'tavern',name:'Karczma „Pod Krukiem”',icon:'🍺',tag:'Questy • odpoczynek'},
 {id:'shop',name:'Sklep kupiecki',icon:'🛒',tag:'Mikstury • materiały'},
 {id:'smith',name:'Kuźnia',icon:'⚒️',tag:'Ulepszanie • rozbiórka'},
 {id:'alchemist',name:'Alchemik',icon:'⚗️',tag:'Warzenie mikstur'},
 {id:'auction',name:'Dom aukcyjny',icon:'🏛️',tag:'Oferty dnia'},
 {id:'guild',name:'Sala gildii',icon:'🏰',tag:'Gildie • wyprawy'}
];
