export const CLASSES = {
  knight:{name:'Ciężki Rycerz',icon:'🛡️',accent:'stal',desc:'Tank. Blok, pancerz, tarcza i kontrola przeciwnika.',base:{str:7,agi:3,int:2,vit:9},hp:150,mana:45},
  mage:{name:'Mag',icon:'🔮',accent:'arkanum',desc:'Silne zaklęcia, mana i efekty żywiołów.',base:{str:2,agi:4,int:10,vit:5},hp:95,mana:125},
  hunter:{name:'Łowca',icon:'🏹',accent:'las',desc:'Krytyki, podwójny strzał i współpraca z chowańcem.',base:{str:4,agi:10,int:3,vit:5},hp:108,mana:75},
  berserker:{name:'Berserker',icon:'🪓',accent:'krew',desc:'Ogromne obrażenia, furia i premie przy niskim HP.',base:{str:10,agi:5,int:1,vit:7},hp:138,mana:40},
  ranger:{name:'Tropiciel',icon:'🌿',accent:'natura',desc:'Trucizny, pułapki, mobilność i chowaniec.',base:{str:4,agi:8,int:6,vit:5},hp:112,mana:90}
};

// Build 3.3 — stworzenia odnalezione w starym katalogu grafik. Każde ma
// osobny wpis w bestiariuszu i jest przypisane do regionu oraz biomu.
const ARCHIVE_MONSTER_DEFS=[
 ['bazyliszek','Bazyliszek','🐍','Bestie',46,62,'red','przebicie','highlands',5,'bazyliszek.png'],
 ['bies','Bies Borowy','👹','Demony',34,47,'red','światło','forest',4,'bies.png'],
 ['blednyOgnik','Błędny Ognik','🔥','Zjawy',13,26,'yellow','arkanum','ruins',2,'bledny-ognik.png'],
 ['chochlik','Chochlik Zarośli','👺','Natura',2,11,'green','obuch','forest',1,'chochlik.png'],
 ['cmaUpiorna','Ćma Upiorna','🦋','Owady',23,35,'yellow','ogień','marsh',3,'cma-upiorna.png'],
 ['czapla','Czapla Żelaznodzioba','🪶','Natura',3,12,'green','przebicie','marsh',1,'czapla.png'],
 ['diabel','Diabeł Popielny','😈','Demony',38,51,'red','lód','highlands',4,'diabel.png'],
 ['dziewanna','Drapieżna Dziewanna','🌼','Natura',4,14,'green','ogień','meadow',1,'dziewanna.png'],
 ['dzik','Dzik Szarżownik','🐗','Bestie',5,16,'green','przebicie','forest',1,'dzik.png'],
 ['ghul','Ghul Cmentarny','🧟','Nieumarli',15,28,'yellow','światło','ruins',2,'ghul.png'],
 ['gryf','Gryf Skalnego Gniazda','🦅','Bestie',48,65,'black','przebicie','highlands',5,'gryf.png'],
 ['grzybiarz','Grzybiarz Zarodnikowy','🍄','Natura',6,17,'green','ogień','forest',1,'grzybiarz.png'],
 ['harpia','Harpia Północnego Wiatru','🦅','Bestie',17,29,'yellow','przebicie','highlands',2,'harpia.png'],
 ['jednorozec','Jednorożec Świetlistej Grani','🦄','Natura',50,68,'black','cień','highlands',5,'jednorozec.png'],
 ['kieszonkowiec','Kieszonkowiec Traktu','🗡️','Ludzie',4,13,'green','krwawienie','meadow',1,'kieszonkowiec.png'],
 ['klusownik','Kłusownik Kniei','🏹','Ludzie',7,18,'green','trucizna','forest',1,'klusownik.png'],
 ['komarzyca','Krwawa Komarzyca','🦟','Owady',24,36,'yellow','ogień','marsh',3,'komarzyca.png'],
 ['kosciej','Kościej Nieśmiertelny','💀','Nieumarli',53,72,'black','światło','ruins',5,'kosciej.png'],
 ['kozica','Kozica Gromowa','🐐','Bestie',43,56,'red','obuch','highlands',5,'kozica.png'],
 ['krocionog','Krocionóg Bagienny','🐛','Owady',22,34,'yellow','ogień','marsh',3,'krocionog.png'],
 ['kruk','Kruk Zwiadowca','🐦‍⬛','Natura',3,12,'green','arkanum','forest',1,'kruk.png'],
 ['latawiec','Latawiec Ognisty','🔥','Demony',27,39,'red','lód','marsh',3,'latawiec.png'],
 ['leszy','Leszy Starego Boru','🌳','Natura',28,41,'red','ogień','forest',3,'leszy.png'],
 ['lis','Lis Rdzawiec','🦊','Natura',2,11,'green','pułapki','forest',1,'lis.png'],
 ['lodowyGolem','Lodowy Golem','🧊','Żywiołaki',45,60,'red','ogień','highlands',5,'lodowy-golem.png'],
 ['mangradora','Mangradora Krzykliwa','🌱','Natura',25,37,'yellow','ogień','marsh',3,'mangradora.png'],
 ['mlodyKraken','Młody Kraken','🐙','Bestie',29,42,'red','przebicie','marsh',3,'mlody-kraken.png'],
 ['mumia','Mumia Strażnika','🧟','Nieumarli',18,30,'yellow','ogień','ruins',2,'mumia.png'],
 ['najemnik','Najemnik Czarnego Szlaku','⚔️','Ludzie',16,29,'yellow','krwawienie','meadow',2,'najemnik.png'],
 ['niedzwiedz','Niedźwiedź Północy','🐻','Bestie',19,31,'yellow','ogień','forest',2,'niedzwiedz.png'],
 ['ork','Ork Łupieżca','👹','Ludzie',17,30,'yellow','trucizna','highlands',2,'ork.png'],
 ['placzacaPanna','Płacząca Panna','👻','Zjawy',26,38,'yellow','światło','marsh',3,'placzaca-panna.png'],
 ['placzacaWierzba','Płacząca Wierzba','🌳','Natura',28,40,'red','ogień','marsh',3,'placzaca-wierzba.png'],
 ['plomyk','Płomyk Żaru','🔥','Żywiołaki',31,43,'yellow','lód','highlands',4,'plomyk.png'],
 ['poltergeist','Poltergeist Ruin','👻','Zjawy',14,27,'yellow','światło','ruins',2,'poltergeist.png'],
 ['poludnica','Południca','🌾','Zjawy',16,29,'yellow','cień','meadow',2,'poludnica.png'],
 ['ropucha','Ropucha Błotna','🐸','Natura',5,15,'green','lód','marsh',1,'ropucha.png'],
 ['rozbojnik','Rozbójnik Gościńca','🥷','Ludzie',8,20,'green','krwawienie','meadow',1,'rozbojnik.png'],
 ['rusalka','Rusałka Topieli','🧜‍♀️','Zjawy',25,38,'yellow','światło','marsh',3,'rusalka.png'],
 ['rys','Ryś Północny','🐈','Bestie',14,27,'yellow','pułapki','forest',2,'rys.png'],
 ['skorpion','Skorpion Czarnego Błota','🦂','Owady',25,39,'yellow','lód','marsh',3,'skorpion.png'],
 ['sokol','Sokół Łowca','🦅','Natura',6,17,'green','przebicie','highlands',1,'sokol.png'],
 ['strachNaWroble','Strach na Wróble','🎃','Zjawy',9,21,'green','ogień','meadow',1,'strach-na-wroble.png'],
 ['sumOlbrzymi','Sum Olbrzymi','🐟','Bestie',28,42,'red','przebicie','marsh',3,'sum-olbrzymi.png'],
 ['szaleniec','Szaleniec z Toporem','🪓','Ludzie',18,31,'yellow','trucizna','ruins',2,'szaleniec.png'],
 ['trupojad','Trupojad','🧟','Nieumarli',27,40,'red','światło','marsh',3,'trupojad.png'],
 ['trzcinnik','Trzcinnik','🌾','Natura',23,36,'yellow','ogień','marsh',3,'trzcinnik.png'],
 ['widmowyJezdziec','Widmowy Jeździec','🐎','Zjawy',49,66,'black','światło','highlands',5,'widmowy-jezdziec.png'],
 ['wilkolak','Wilkołak Północy','🐺','Bestie',20,34,'yellow','światło','forest',2,'wilkolak.png'],
 ['wir','Żywy Wir','🌀','Żywiołaki',29,43,'red','arkanum','marsh',3,'wir.png'],
 ['wisielec','Wisielec z Rozstajów','☠️','Nieumarli',15,28,'yellow','światło','ruins',2,'wisielec.png'],
 ['wodnik','Wodnik Rozlewiska','🧌','Demony',27,40,'red','lód','marsh',3,'wodnik.png'],
 ['wydra','Wydra Wojowniczka','🦦','Natura',4,14,'green','pułapki','marsh',1,'wydra.png'],
 ['zbik','Żbik Leśny','🐈','Bestie',7,18,'green','pułapki','forest',1,'zbik.png'],
 ['zbir','Zbir Karczemny','🔪','Ludzie',6,17,'green','krwawienie','meadow',1,'zbir.png'],
 ['zdziczalyPies','Zdziczały Pies','🐕','Natura',3,13,'green','pułapki','meadow',1,'zdziczaly-pies.png'],
 ['zmora','Zmora Nocna','🌑','Zjawy',30,44,'red','światło','marsh',3,'zmora.png'],
 ['zniwiarzPol','Żniwiarz Pól','💀','Nieumarli',19,32,'yellow','światło','meadow',2,'zniwiarz-pol.png'],
 ['zombie','Zombie Strażnik','🧟','Nieumarli',12,25,'green','ogień','ruins',2,'zombie.png'],
 ['zywiolakCienia','Żywiołak Cienia','🌑','Żywiołaki',36,50,'red','światło','ruins',4,'zywiolak-cienia.png'],
 ['zywiolakSwiatla','Żywiołak Światła','☀️','Żywiołaki',47,64,'black','cień','highlands',5,'zywiolak-swiatla.png']
];
const ARCHIVE_MONSTERS=ARCHIVE_MONSTER_DEFS.map(([id,name,icon,family,min,max,zone,weak,biome,archiveRegion,sourceAsset])=>{
 const zoneHp={green:0,yellow:25,red:55,black:95}[zone]||0;
 return {id,name,icon,family,min,max,zone,weak,biome,archiveRegion,sourceAsset,hp:Math.round(42+min*7.6+zoneHp),atk:Math.round(7+min*1.05),xp:Math.round(38+min*17.5),gold:[Math.max(3,Math.round(min*1.35)),Math.max(8,Math.round(min*2.45))]};
});

export const MONSTERS = [
 {id:'slime',name:'Błotny Pełzacz',icon:'🟢',family:'Natura',min:1,max:4,zone:'green',hp:42,atk:7,xp:38,gold:[3,8],weak:'ogień'},
 {id:'rat',name:'Zdziczały Szczur',icon:'🐀',family:'Natura',min:1,max:5,zone:'green',hp:36,atk:8,xp:35,gold:[2,7],weak:'trucizna'},
 {id:'beetle',name:'Pancerznik',icon:'🪲',family:'Owady',min:2,max:7,zone:'green',hp:48,atk:8,xp:44,gold:[3,9],weak:'przebicie'},
 {id:'wolf',name:'Szary Wilk',icon:'🐺',family:'Natura',min:4,max:10,zone:'green',hp:62,atk:11,xp:62,gold:[5,12],weak:'pułapki'},
 {id:'goblin',name:'Gobliński Zwiadowca',icon:'👺',family:'Ludzie',role:'Zwiadowca',min:3,max:12,zone:'green',hp:58,atk:10,xp:58,gold:[5,13],weak:'krwawienie'},
 {id:'goblinWarrior',name:'Gobliński Wojownik',icon:'👺',family:'Ludzie',role:'Wojownik',min:6,max:18,zone:'green',hp:86,atk:14,xp:92,gold:[8,19],weak:'obuch'},
 {id:'goblinMage',name:'Gobliński Mag',icon:'👺',family:'Ludzie',role:'Mag',min:10,max:25,zone:'green',hp:76,atk:20,xp:138,gold:[12,27],weak:'przebicie'},
 {id:'goblinChampion',name:'Gobliński Czempion',icon:'👺',family:'Ludzie',role:'Dowódca',min:18,max:34,zone:'yellow',hp:188,atk:28,xp:285,gold:[24,48],weak:'trucizna'},
 {id:'skeleton',name:'Kościany Wojownik',icon:'💀',family:'Nieumarli',min:10,max:22,zone:'green',hp:94,atk:16,xp:118,gold:[10,20],weak:'obuch'},
 {id:'ghost',name:'Błądząca Zjawa',icon:'👻',family:'Zjawy',min:25,max:38,zone:'yellow',hp:145,atk:23,xp:245,gold:[18,34],weak:'arkanum'},
 {id:'elemental',name:'Żywiołak Kamienia',icon:'🗿',family:'Żywiołaki',min:30,max:45,zone:'yellow',hp:190,atk:25,xp:300,gold:[22,40],weak:'lód'},
 {id:'cultist',name:'Kultysta Pustki',icon:'🥷',family:'Ludzie',min:20,max:38,zone:'yellow',hp:135,atk:24,xp:220,gold:[16,35],weak:'światło'},
 {id:'demon',name:'Rogaty Demon',icon:'👹',family:'Demony',min:40,max:58,zone:'red',hp:265,atk:38,xp:520,gold:[35,65],weak:'lód'},
 {id:'hellhound',name:'Piekielny Ogar',icon:'🐕‍🦺',family:'Demony',min:45,max:65,zone:'red',hp:245,atk:43,xp:560,gold:[38,72],weak:'woda'},
 {id:'wyvern',name:'Popielna Wywerna',icon:'🐉',family:'Bestie',min:60,max:80,zone:'black',hp:420,atk:58,xp:920,gold:[70,120],weak:'przebicie'},
 {id:'shade',name:'Cień z Kurhanu',icon:'🌑',family:'Zjawy',min:18,max:32,zone:'yellow',hp:122,atk:21,xp:190,gold:[14,30],weak:'światło'},
 {id:'spider',name:'Leśny Tkacz',icon:'🕷️',family:'Owady',min:8,max:18,zone:'green',hp:82,atk:14,xp:96,gold:[8,18],weak:'ogień'},
 {id:'ogre',name:'Ogr Rozbójnik',icon:'👹',family:'Ludzie',min:32,max:48,zone:'yellow',hp:235,atk:31,xp:365,gold:[28,52],weak:'trucizna'},
 {id:'graveColossus',name:'Koloss z Kurhanu',icon:'🗿',family:'Nieumarli',min:8,max:45,zone:'red',hp:360,atk:33,xp:780,gold:[80,140],weak:'światło'},
 {id:'stormDrake',name:'Smok Burzowy',icon:'🐲',family:'Bestie',min:12,max:55,zone:'red',hp:420,atk:38,xp:920,gold:[95,160],weak:'lód'},
 {id:'mireCrawler',name:'Pełzacz Moczaru',icon:'🪱',family:'Owady',min:21,max:26,zone:'yellow',hp:152,atk:24,xp:255,gold:[20,36],weak:'ogień'},
 {id:'bogWraith',name:'Zjawa Topielca',icon:'🫧',family:'Zjawy',min:22,max:29,zone:'yellow',hp:164,atk:27,xp:285,gold:[22,40],weak:'światło'},
 {id:'fenStalker',name:'Trzcinowy Łowca',icon:'🦎',family:'Bestie',min:23,max:30,zone:'yellow',hp:178,atk:29,xp:315,gold:[24,44],weak:'trucizna'},
 {id:'rotCultist',name:'Kultysta Zgnilizny',icon:'🧟',family:'Ludzie',min:23,max:30,zone:'yellow',hp:170,atk:30,xp:325,gold:[26,46],weak:'ogień'},
 {id:'mossGolem',name:'Golem Torfowy',icon:'🪨',family:'Żywiołaki',min:25,max:31,zone:'yellow',hp:238,atk:31,xp:360,gold:[28,50],weak:'lód'},
 {id:'marshHag',name:'Wiedźma Moczaru',icon:'🧙‍♀️',family:'Demony',min:26,max:32,zone:'red',hp:205,atk:35,xp:410,gold:[32,58],weak:'światło'},
 {id:'blackrootGuardian',name:'Strażnik Czarnego Korzenia',icon:'🌳',family:'Natura',min:28,max:34,zone:'red',hp:285,atk:37,xp:470,gold:[38,66],weak:'ogień'},
 {id:'mireMother',name:'Matka Mgły',icon:'🕸️',family:'Bestie',min:30,max:36,zone:'red',hp:520,atk:45,xp:1100,gold:[120,190],weak:'ogień'},
{id:'ashScavenger',name:'Popielny Padlinożerca',icon:'🦴',family:'Bestie',min:31,max:36,zone:'yellow',hp:245,atk:36,xp:470,gold:[34,58],weak:'lód'},
 {id:'fireWasp',name:'Ognista Osa',icon:'🐝',family:'Owady',min:31,max:36,zone:'yellow',hp:205,atk:39,xp:450,gold:[32,56],weak:'lód'},
 {id:'cinderCultist',name:'Kultysta Żaru',icon:'🔥',family:'Ludzie',min:32,max:38,zone:'yellow',hp:252,atk:40,xp:510,gold:[36,62],weak:'przebicie'},
 {id:'emberWraith',name:'Widmo Popiołu',icon:'👻',family:'Zjawy',min:33,max:39,zone:'yellow',hp:238,atk:43,xp:540,gold:[38,66],weak:'światło'},
 {id:'slagGolem',name:'Golem Żużlowy',icon:'🪨',family:'Żywiołaki',min:34,max:40,zone:'red',hp:330,atk:44,xp:600,gold:[42,72],weak:'lód'},
 {id:'ashDrake',name:'Popielny Drak',icon:'🐉',family:'Bestie',min:36,max:42,zone:'red',hp:365,atk:49,xp:690,gold:[48,82],weak:'przebicie'},
 {id:'pyreKnight',name:'Rycerz Stosu',icon:'🛡️',family:'Nieumarli',min:37,max:43,zone:'red',hp:390,atk:50,xp:720,gold:[50,86],weak:'światło'},
 {id:'cinderMatriarch',name:'Matka Żaru',icon:'👑',family:'Demony',min:40,max:45,zone:'red',hp:720,atk:59,xp:1550,gold:[150,230],weak:'lód'},
 {id:'frostRaptor',name:'Mroźny Raptor',icon:'🦖',family:'Bestie',min:41,max:46,zone:'yellow',hp:360,atk:52,xp:760,gold:[54,90],weak:'ogień'},
 {id:'stormCultist',name:'Kultysta Burzy',icon:'⚡',family:'Ludzie',min:42,max:48,zone:'yellow',hp:345,atk:55,xp:810,gold:[58,96],weak:'obuch'},
 {id:'iceWraith',name:'Lodowe Widmo',icon:'❄️',family:'Zjawy',min:43,max:49,zone:'yellow',hp:330,atk:57,xp:840,gold:[60,100],weak:'ogień'},
 {id:'thunderGolem',name:'Golem Piorunów',icon:'🗿',family:'Żywiołaki',min:44,max:50,zone:'red',hp:455,atk:58,xp:920,gold:[66,108],weak:'obuch'},
 {id:'mountainTroll',name:'Troll Skalny',icon:'👹',family:'Bestie',min:45,max:51,zone:'red',hp:500,atk:61,xp:980,gold:[70,115],weak:'trucizna'},
 {id:'skySerpent',name:'Wąż Niebios',icon:'🐍',family:'Bestie',min:46,max:52,zone:'red',hp:430,atk:64,xp:1040,gold:[74,122],weak:'przebicie'},
 {id:'frozenKnight',name:'Zamarznięty Strażnik',icon:'⚔️',family:'Nieumarli',min:47,max:53,zone:'red',hp:470,atk:65,xp:1080,gold:[78,128],weak:'ogień'},
 {id:'tempestLord',name:'Władca Nawałnicy',icon:'🌩️',family:'Żywiołaki',min:50,max:55,zone:'black',hp:880,atk:74,xp:2200,gold:[210,310],weak:'obuch'},

 // Build 3.2 — nowe gatunki spotykane w biomach i strefach zagrożenia
 {id:'thornBoar',name:'Kolczasty Odyniec',icon:'🐗',family:'Natura',min:5,max:16,zone:'green',hp:76,atk:13,xp:82,gold:[7,16],weak:'ogień'},
 {id:'caveBat',name:'Jaskiniowy Krwiopijca',icon:'🦇',family:'Bestie',min:3,max:14,zone:'green',hp:54,atk:12,xp:68,gold:[5,13],weak:'światło'},
 {id:'graveMoth',name:'Ćma Grobowa',icon:'🦋',family:'Owady',min:8,max:20,zone:'green',hp:88,atk:16,xp:108,gold:[8,20],weak:'ogień'},
 {id:'boneArcher',name:'Kościany Łucznik',icon:'🏹',family:'Nieumarli',min:12,max:25,zone:'green',hp:112,atk:20,xp:148,gold:[12,26],weak:'obuch'},
 {id:'mistStag',name:'Jeleń Mgły',icon:'🦌',family:'Zjawy',min:20,max:34,zone:'yellow',hp:154,atk:25,xp:265,gold:[20,42],weak:'światło'},
 {id:'plagueToad',name:'Ropuch Zarazy',icon:'🐸',family:'Natura',min:22,max:36,zone:'yellow',hp:196,atk:27,xp:310,gold:[24,48],weak:'lód'},
 {id:'magmaScorpion',name:'Magma Skorpion',icon:'🦂',family:'Owady',min:34,max:48,zone:'red',hp:285,atk:43,xp:590,gold:[42,78],weak:'lód'},
 {id:'voidHound',name:'Ogar Pustki',icon:'🐕',family:'Demony',min:38,max:54,zone:'red',hp:315,atk:49,xp:690,gold:[50,88],weak:'światło'},
 {id:'obsidianSentinel',name:'Obsydianowy Strażnik',icon:'🗿',family:'Żywiołaki',min:42,max:58,zone:'red',hp:470,atk:54,xp:840,gold:[62,106],weak:'obuch'},
 {id:'stormGriffin',name:'Gryf Nawałnicy',icon:'🦅',family:'Bestie',min:48,max:68,zone:'black',hp:560,atk:67,xp:1180,gold:[92,148],weak:'przebicie'},
 {id:'lichWarden',name:'Licz Strażnik',icon:'💀',family:'Nieumarli',min:52,max:74,zone:'black',hp:610,atk:72,xp:1360,gold:[105,170],weak:'światło'},
 {id:'abyssHydra',name:'Hydra Otchłani',icon:'🐉',family:'Demony',min:60,max:82,zone:'black',hp:760,atk:82,xp:1750,gold:[140,220],weak:'lód'},
 ...ARCHIVE_MONSTERS
];


// Build 2.9 — pełne tabele łupów. Wpis w bestiariuszu odblokowuje je po pierwszym pokonaniu.
export const MONSTER_LOOT = {
 slime:[{id:'slimeGel',chance:.82,min:1,max:2},{id:'herb',chance:.18,min:1,max:1}],
 rat:[{id:'ratTail',chance:.78,min:1,max:1},{id:'rawMeat',chance:.42,min:1,max:1}],
 beetle:[{id:'beetleCarapace',chance:.72,min:1,max:2},{id:'venomGland',chance:.16,min:1,max:1}],
 wolf:[{id:'wolfPelt',chance:.62,min:1,max:1},{id:'rawMeat',chance:.72,min:1,max:2},{id:'wolfFang',chance:.34,min:1,max:1}],
 goblin:[{id:'goblinEar',chance:.68,min:1,max:1},{id:'goblinMapScrap',chance:.46,min:1,max:1},{id:'roughCloth',chance:.42,min:1,max:2},{id:'primitiveArrow',chance:.26,min:2,max:7}],
 goblinWarrior:[{id:'goblinEar',chance:.72,min:1,max:1},{id:'dentedBuckler',chance:.48,min:1,max:1},{id:'scrap',chance:.58,min:1,max:2},{id:'rustySword',chance:.045,min:1,max:1}],
 goblinMage:[{id:'goblinEar',chance:.62,min:1,max:1},{id:'goblinFocus',chance:.54,min:1,max:1},{id:'manaPotion',chance:.20,min:1,max:1},{id:'runeShard',chance:.09,min:1,max:1}],
 goblinChampion:[{id:'goblinEar',chance:.92,min:1,max:2},{id:'goblinBanner',chance:.66,min:1,max:1},{id:'oldCoin',chance:.58,min:2,max:5},{id:'runeShard',chance:.16,min:1,max:1},{id:'ironAxe',chance:.055,min:1,max:1}],
 skeleton:[{id:'bone',chance:.88,min:1,max:3},{id:'brokenBlade',chance:.28,min:1,max:1},{id:'oldCoin',chance:.24,min:1,max:2}],
 ghost:[{id:'ectoplasm',chance:.66,min:1,max:2},{id:'graveDust',chance:.38,min:1,max:1},{id:'crystal',chance:.08,min:1,max:1}],
 elemental:[{id:'stoneCore',chance:.72,min:1,max:2},{id:'crystal',chance:.24,min:1,max:1},{id:'scrap',chance:.16,min:1,max:2}],
 cultist:[{id:'cultistSigil',chance:.48,min:1,max:1},{id:'roughCloth',chance:.62,min:1,max:2},{id:'scrap',chance:.30,min:1,max:2}],
 demon:[{id:'demonHorn',chance:.54,min:1,max:2},{id:'demonBlood',chance:.42,min:1,max:1},{id:'sulfur',chance:.68,min:1,max:2}],
 hellhound:[{id:'hellhoundFang',chance:.58,min:1,max:2},{id:'charredHide',chance:.52,min:1,max:1},{id:'demonBlood',chance:.24,min:1,max:1}],
 wyvern:[{id:'wyvernScale',chance:.74,min:1,max:3},{id:'wyvernClaw',chance:.38,min:1,max:1},{id:'emberCore',chance:.18,min:1,max:1}],
 shade:[{id:'shadowEssence',chance:.62,min:1,max:2},{id:'ectoplasm',chance:.42,min:1,max:1},{id:'graveDust',chance:.28,min:1,max:1}],
 spider:[{id:'spiderSilk',chance:.76,min:1,max:2},{id:'venomGland',chance:.44,min:1,max:1}],
 ogre:[{id:'ogreHide',chance:.68,min:1,max:2},{id:'ogreTooth',chance:.42,min:1,max:1},{id:'rawMeat',chance:.52,min:1,max:2}],
 graveColossus:[{id:'bone',chance:1,min:2,max:4},{id:'graveDust',chance:.78,min:1,max:3},{id:'runeShard',chance:.30,min:1,max:1}],
 stormDrake:[{id:'stormScale',chance:.82,min:1,max:3},{id:'stormFeather',chance:.36,min:1,max:2},{id:'frostCrystal',chance:.14,min:1,max:1}],
 mireCrawler:[{id:'mireMoss',chance:.64,min:1,max:2},{id:'beetleCarapace',chance:.34,min:1,max:1},{id:'venomGland',chance:.22,min:1,max:1}],
 bogWraith:[{id:'wraithEssence',chance:.58,min:1,max:2},{id:'ectoplasm',chance:.52,min:1,max:2},{id:'graveDust',chance:.20,min:1,max:1}],
 fenStalker:[{id:'swampScale',chance:.66,min:1,max:2},{id:'rawMeat',chance:.52,min:1,max:2},{id:'mireMoss',chance:.28,min:1,max:1}],
 rotCultist:[{id:'rotSigil',chance:.52,min:1,max:1},{id:'roughCloth',chance:.56,min:1,max:2},{id:'mireMoss',chance:.32,min:1,max:1}],
 mossGolem:[{id:'stoneCore',chance:.58,min:1,max:2},{id:'mireMoss',chance:.64,min:1,max:3},{id:'bogAmber',chance:.24,min:1,max:1}],
 marshHag:[{id:'hagCharm',chance:.38,min:1,max:1},{id:'moonHerb',chance:.44,min:1,max:2},{id:'wraithEssence',chance:.28,min:1,max:1}],
 blackrootGuardian:[{id:'ancientBark',chance:.78,min:1,max:3},{id:'blackroot',chance:.52,min:1,max:2},{id:'mireMoss',chance:.42,min:1,max:2}],
 mireMother:[{id:'mireSilk',chance:1,min:2,max:4},{id:'bogAmber',chance:1,min:2,max:3},{id:'wraithEssence',chance:1,min:1,max:2},{id:'mireMoss',chance:1,min:2,max:4}],
 ashScavenger:[{id:'scorchedBone',chance:.62,min:1,max:2},{id:'charredIron',chance:.44,min:1,max:2},{id:'rawMeat',chance:.26,min:1,max:1}],
 fireWasp:[{id:'fireWing',chance:.72,min:1,max:2},{id:'ashGlass',chance:.34,min:1,max:1},{id:'venomGland',chance:.28,min:1,max:1}],
 cinderCultist:[{id:'cultistSigil',chance:.48,min:1,max:1},{id:'charredIron',chance:.58,min:1,max:2},{id:'roughCloth',chance:.36,min:1,max:1}],
 emberWraith:[{id:'ectoplasm',chance:.56,min:1,max:2},{id:'ashGlass',chance:.48,min:1,max:2},{id:'shadowEssence',chance:.18,min:1,max:1}],
 slagGolem:[{id:'charredIron',chance:.74,min:1,max:3},{id:'stoneCore',chance:.44,min:1,max:2},{id:'emberCore',chance:.22,min:1,max:1}],
 ashDrake:[{id:'ashScale',chance:.78,min:1,max:3},{id:'emberCore',chance:.34,min:1,max:1},{id:'wyvernClaw',chance:.18,min:1,max:1}],
 pyreKnight:[{id:'charredIron',chance:.68,min:1,max:3},{id:'scorchedBone',chance:.52,min:1,max:2},{id:'brokenBlade',chance:.34,min:1,max:1}],
 cinderMatriarch:[{id:'emberCore',chance:1,min:2,max:3},{id:'ashGlass',chance:1,min:2,max:3},{id:'charredIron',chance:1,min:2,max:4},{id:'demonBlood',chance:.60,min:1,max:2}],
 frostRaptor:[{id:'frostClaw',chance:.68,min:1,max:2},{id:'frostCrystal',chance:.42,min:1,max:1},{id:'rawMeat',chance:.36,min:1,max:2}],
 stormCultist:[{id:'cultistSigil',chance:.46,min:1,max:1},{id:'stormFeather',chance:.34,min:1,max:1},{id:'roughCloth',chance:.42,min:1,max:2}],
 iceWraith:[{id:'ectoplasm',chance:.52,min:1,max:2},{id:'frostCrystal',chance:.56,min:1,max:2},{id:'graveDust',chance:.18,min:1,max:1}],
 thunderGolem:[{id:'stormCore',chance:.48,min:1,max:1},{id:'skySteel',chance:.32,min:1,max:1},{id:'stoneCore',chance:.62,min:1,max:2}],
 mountainTroll:[{id:'trollHide',chance:.72,min:1,max:2},{id:'trollTooth',chance:.44,min:1,max:1},{id:'rawMeat',chance:.54,min:1,max:2}],
 skySerpent:[{id:'skyScale',chance:.76,min:1,max:3},{id:'stormFeather',chance:.42,min:1,max:2},{id:'stormCore',chance:.16,min:1,max:1}],
 frozenKnight:[{id:'frostCrystal',chance:.54,min:1,max:2},{id:'brokenBlade',chance:.42,min:1,max:1},{id:'skySteel',chance:.16,min:1,max:1}],
 tempestLord:[{id:'stormCore',chance:1,min:2,max:3},{id:'skySteel',chance:1,min:2,max:3},{id:'stormFeather',chance:1,min:2,max:4},{id:'frostCrystal',chance:.80,min:1,max:2}],
 thornBoar:[{id:'rawMeat',chance:.82,min:1,max:2},{id:'wolfPelt',chance:.26,min:1,max:1},{id:'herb',chance:.18,min:1,max:1}],
 caveBat:[{id:'roughCloth',chance:.34,min:1,max:1},{id:'ectoplasm',chance:.12,min:1,max:1},{id:'oldCoin',chance:.20,min:1,max:2}],
 graveMoth:[{id:'graveDust',chance:.58,min:1,max:2},{id:'spiderSilk',chance:.44,min:1,max:1},{id:'moonHerb',chance:.10,min:1,max:1}],
 boneArcher:[{id:'bone',chance:.86,min:1,max:3},{id:'brokenBlade',chance:.32,min:1,max:1},{id:'oldCoin',chance:.30,min:1,max:2}],
 mistStag:[{id:'ectoplasm',chance:.52,min:1,max:2},{id:'moonHerb',chance:.34,min:1,max:1},{id:'crystal',chance:.12,min:1,max:1}],
 plagueToad:[{id:'venomGland',chance:.66,min:1,max:2},{id:'mireMoss',chance:.48,min:1,max:2},{id:'slimeGel',chance:.30,min:1,max:1}],
 magmaScorpion:[{id:'ashGlass',chance:.62,min:1,max:2},{id:'fireWing',chance:.30,min:1,max:1},{id:'emberCore',chance:.12,min:1,max:1}],
 voidHound:[{id:'charredHide',chance:.64,min:1,max:2},{id:'demonBlood',chance:.46,min:1,max:1},{id:'shadowEssence',chance:.20,min:1,max:1}],
 obsidianSentinel:[{id:'stoneCore',chance:.76,min:1,max:3},{id:'charredIron',chance:.54,min:1,max:2},{id:'runeShard',chance:.14,min:1,max:1}],
 stormGriffin:[{id:'stormFeather',chance:.82,min:1,max:3},{id:'skySteel',chance:.26,min:1,max:1},{id:'frostClaw',chance:.22,min:1,max:1}],
 lichWarden:[{id:'graveDust',chance:.74,min:1,max:3},{id:'shadowEssence',chance:.52,min:1,max:2},{id:'runeShard',chance:.24,min:1,max:1}],
 abyssHydra:[{id:'demonBlood',chance:.86,min:1,max:3},{id:'emberCore',chance:.44,min:1,max:2},{id:'wyvernScale',chance:.58,min:1,max:3},{id:'runeShard',chance:.30,min:1,max:1}]
};

export const ITEMS = {
 // STARTOWE EQ — celowo słabe
 tornRags:{id:'tornRags',name:'Zdarte szmaty',icon:'🧥',type:'armor',slot:'armor',rarity:'common',reqLevel:1,value:2,armor:1,classes:['knight','mage','hunter','berserker','ranger']},
 holeyBoots:{id:'holeyBoots',name:'Dziurawe buty',icon:'🥾',type:'gear',slot:'boots',rarity:'common',reqLevel:1,value:2,armor:0,classes:['knight','mage','hunter','berserker','ranger']},
 shortBlade:{id:'shortBlade',name:'Krótkie wyszczerbione ostrze',icon:'🗡️',type:'weapon',slot:'weapon',weaponKind:'sword',rarity:'common',reqLevel:1,value:5,damage:[1,5],power:1,classes:['knight','berserker']},
 willowStaff:{id:'willowStaff',name:'Kij z wierzby',icon:'🪄',type:'weapon',slot:'weapon',weaponKind:'staff',rarity:'common',reqLevel:1,value:5,damage:[4,6],power:1,classes:['mage'],magicAlwaysHits:true},
 primitiveBow:{id:'primitiveBow',name:'Prymitywny łuk',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'common',reqLevel:1,value:5,damage:[3,5],power:1,classes:['hunter','ranger'],ammo:'primitiveArrow'},
 primitiveArrow:{id:'primitiveArrow',name:'Prymitywna strzała',icon:'➶',type:'ammo',rarity:'common',value:1,maxStack:250},
 // PIERWSZY ŁUP KLASOWY — gwarantowany z pierwszego pokonanego stwora
 trainingShield:{id:'trainingShield',name:'Tarcza rekruta',icon:'🛡️',type:'gear',slot:'offhand',rarity:'common',reqLevel:1,value:10,armor:3,classes:['knight']},
 trainingAxe:{id:'trainingAxe',name:'Topór rekruta',icon:'🪓',type:'weapon',slot:'weapon',weaponKind:'axe',rarity:'common',reqLevel:1,value:10,damage:[3,6],power:2,classes:['berserker']},
 trainingStaff:{id:'trainingStaff',name:'Kostur ucznia',icon:'🪄',type:'weapon',slot:'weapon',weaponKind:'staff',rarity:'common',reqLevel:1,value:10,damage:[5,8],power:2,classes:['mage'],magicAlwaysHits:true},
 trainingBow:{id:'trainingBow',name:'Łuk ucznia',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'common',reqLevel:1,value:10,damage:[4,7],power:2,classes:['hunter','ranger'],ammo:'primitiveArrow'},

 // BROŃ — RYCERZ / BERSERKER
 rustySword:{id:'rustySword',name:'Zardzewiały miecz',icon:'🗡️',type:'weapon',slot:'weapon',weaponKind:'sword',rarity:'common',reqLevel:3,value:18,damage:[3,7],power:2,classes:['knight','berserker']},
 shortSword:{id:'shortSword',name:'Krótki miecz',icon:'⚔️',type:'weapon',slot:'weapon',weaponKind:'sword',rarity:'common',reqLevel:7,value:44,damage:[6,11],power:4,classes:['knight','berserker']},
 ironAxe:{id:'ironAxe',name:'Żelazny topór',icon:'🪓',type:'weapon',slot:'weapon',weaponKind:'axe',rarity:'common',reqLevel:9,value:58,damage:[8,13],power:5,classes:['knight','berserker']},
 warHammer:{id:'warHammer',name:'Młot bojowy',icon:'🔨',type:'weapon',slot:'weapon',weaponKind:'hammer',rarity:'epic',reqLevel:12,value:90,damage:[11,17],power:7,classes:['knight','berserker']},
 axe:{id:'axe',name:'Ciężki topór',icon:'🪓',type:'weapon',slot:'weapon',weaponKind:'axe',rarity:'epic',reqLevel:14,value:105,damage:[13,20],power:8,classes:['knight','berserker']},
 blueBlade:{id:'blueBlade',name:'Ostrze Strażnika',icon:'⚔️',type:'weapon',slot:'weapon',weaponKind:'sword',rarity:'epic',reqLevel:16,value:130,damage:[15,23],power:9,classes:['knight','berserker']},
 ravenBlade:{id:'ravenBlade',name:'Krucze Ostrze',icon:'🗡️',type:'weapon',slot:'weapon',weaponKind:'sword',rarity:'unique',reqLevel:20,value:260,damage:[20,30],power:11,crit:2,set:'raven',classes:['knight','berserker']},
 mistBlade:{id:'mistBlade',name:'Ostrze Strażnika Mgieł',icon:'🗡️',type:'weapon',slot:'weapon',weaponKind:'sword',rarity:'unique',reqLevel:28,value:330,damage:[27,39],power:14,crit:4,set:'mist',classes:['knight','berserker']},
 ashBlade:{id:'ashBlade',name:'Ostrze Popielnej Straży',icon:'🔥',type:'weapon',slot:'weapon',weaponKind:'sword',rarity:'unique',reqLevel:36,value:430,damage:[35,49],power:17,crit:4,set:'ashguard',classes:['knight','berserker']},
 stormSpear:{id:'stormSpear',name:'Włócznia Nawałnicy',icon:'🔱',type:'weapon',slot:'weapon',weaponKind:'spear',rarity:'unique',reqLevel:45,value:560,damage:[44,62],power:21,crit:5,set:'stormforged',classes:['knight','berserker']},

 // BROŃ — MAG
 noviceStaff:{id:'noviceStaff',name:'Kostur nowicjusza',icon:'🪄',type:'weapon',slot:'weapon',weaponKind:'staff',rarity:'common',reqLevel:4,value:26,damage:[6,9],power:2,classes:['mage'],magicAlwaysHits:true},
 apprenticeStaff:{id:'apprenticeStaff',name:'Kostur ucznia',icon:'🪄',type:'weapon',slot:'weapon',weaponKind:'staff',rarity:'common',reqLevel:7,value:52,damage:[8,13],power:4,classes:['mage'],magicAlwaysHits:true},
 emberWand:{id:'emberWand',name:'Różdżka żaru',icon:'🔥',type:'weapon',slot:'weapon',weaponKind:'wand',rarity:'epic',reqLevel:12,value:88,damage:[12,18],power:7,crit:2,classes:['mage'],magicAlwaysHits:true},
 arcaneStaff:{id:'arcaneStaff',name:'Kostur Runiczny',icon:'🪄',type:'weapon',slot:'weapon',weaponKind:'staff',rarity:'epic',reqLevel:16,value:125,damage:[16,24],power:9,classes:['mage'],magicAlwaysHits:true},
 mistStaff:{id:'mistStaff',name:'Kostur Mgieł',icon:'🌫️',type:'weapon',slot:'weapon',weaponKind:'staff',rarity:'unique',reqLevel:28,value:335,damage:[28,41],power:15,crit:4,set:'mist',classes:['mage'],magicAlwaysHits:true},
 ashStaff:{id:'ashStaff',name:'Kostur Popielnego Rdzenia',icon:'🔥',type:'weapon',slot:'weapon',weaponKind:'staff',rarity:'unique',reqLevel:36,value:435,damage:[36,51],power:18,crit:4,set:'ashguard',classes:['mage'],magicAlwaysHits:true},
 stormStaff:{id:'stormStaff',name:'Kostur Serca Burzy',icon:'⚡',type:'weapon',slot:'weapon',weaponKind:'staff',rarity:'unique',reqLevel:45,value:575,damage:[45,64],power:22,crit:5,set:'stormforged',classes:['mage'],magicAlwaysHits:true},

 // BROŃ — ŁOWCA / TROPICIEL
 hunterBow:{id:'hunterBow',name:'Łuk zwiadowcy',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'common',reqLevel:4,value:24,damage:[5,8],power:2,classes:['hunter','ranger'],ammo:'primitiveArrow'},
 yewBow:{id:'yewBow',name:'Łuk cisowy',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'common',reqLevel:7,value:50,damage:[7,11],power:4,crit:1,classes:['hunter','ranger'],ammo:'primitiveArrow'},
 forestBow:{id:'forestBow',name:'Łuk Zielonego Szlaku',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'epic',reqLevel:12,value:105,damage:[11,17],power:7,crit:2,classes:['hunter','ranger'],ammo:'primitiveArrow'},
 wildBow:{id:'wildBow',name:'Łuk Dzikiego Szlaku',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'unique',reqLevel:20,value:255,damage:[19,29],power:11,crit:5,set:'wild',classes:['hunter','ranger'],ammo:'primitiveArrow'},
 mistBow:{id:'mistBow',name:'Łuk Mgieł',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'unique',reqLevel:28,value:330,damage:[26,38],power:14,crit:5,set:'mist',classes:['hunter','ranger'],ammo:'primitiveArrow'},
 ashBow:{id:'ashBow',name:'Łuk Popielnego Szlaku',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'unique',reqLevel:36,value:425,damage:[34,48],power:17,crit:6,set:'ashguard',classes:['hunter','ranger'],ammo:'primitiveArrow'},
 stormBow:{id:'stormBow',name:'Łuk Nawałnicy',icon:'🏹',type:'weapon',slot:'weapon',weaponKind:'bow',rarity:'unique',reqLevel:45,value:565,damage:[43,61],power:21,crit:7,set:'stormforged',classes:['hunter','ranger'],ammo:'primitiveArrow'},

 // PANCERZE I UBRANIA
 leather:{id:'leather',name:'Łatana skórzana kamizelka',icon:'🥋',type:'armor',slot:'armor',rarity:'common',reqLevel:3,value:16,armor:3,classes:['hunter','ranger','berserker']},
 apprenticeRobe:{id:'apprenticeRobe',name:'Szata ucznia',icon:'🥻',type:'armor',slot:'armor',rarity:'common',reqLevel:4,value:34,armor:2,power:2,classes:['mage']},
 chainVest:{id:'chainVest',name:'Kolczuga strażnika',icon:'🦺',type:'armor',slot:'armor',rarity:'common',reqLevel:5,value:48,armor:6,classes:['knight','berserker']},
 rangerLeather:{id:'rangerLeather',name:'Skóra tropiciela',icon:'🥋',type:'armor',slot:'armor',rarity:'common',reqLevel:7,value:55,armor:5,crit:1,classes:['hunter','ranger']},
 berserkerHarness:{id:'berserkerHarness',name:'Uprząż berserkera',icon:'🥋',type:'armor',slot:'armor',rarity:'epic',reqLevel:9,value:76,armor:5,power:3,classes:['berserker']},
 ironArmor:{id:'ironArmor',name:'Żelazny kirys',icon:'🛡️',type:'armor',slot:'armor',rarity:'epic',reqLevel:10,value:90,armor:10,classes:['knight']},
 runicRobe:{id:'runicRobe',name:'Szata runiczna',icon:'🥻',type:'armor',slot:'armor',rarity:'epic',reqLevel:11,value:86,armor:4,power:4,classes:['mage']},
 ravenMail:{id:'ravenMail',name:'Kruczy Pancerz',icon:'🛡️',type:'armor',slot:'armor',rarity:'unique',reqLevel:20,value:250,armor:13,power:2,set:'raven',classes:['knight','berserker']},
 wildMail:{id:'wildMail',name:'Pancerz Dzikiego Szlaku',icon:'🥋',type:'armor',slot:'armor',rarity:'unique',reqLevel:20,value:245,armor:9,crit:4,set:'wild',classes:['hunter','ranger']},
 arcaneRobe:{id:'arcaneRobe',name:'Szata Kręgu',icon:'🥻',type:'armor',slot:'armor',rarity:'unique',reqLevel:20,value:250,armor:7,power:7,crit:2,classes:['mage']},
 mistMail:{id:'mistMail',name:'Pancerz Strażnika Mgieł',icon:'🛡️',type:'armor',slot:'armor',rarity:'unique',reqLevel:28,value:320,armor:16,power:3,set:'mist',classes:['knight','berserker']},
 mistLeathers:{id:'mistLeathers',name:'Skóry Mgieł',icon:'🥋',type:'armor',slot:'armor',rarity:'unique',reqLevel:28,value:315,armor:11,crit:5,set:'mist',classes:['hunter','ranger']},
 mistRobe:{id:'mistRobe',name:'Szata Mgieł',icon:'🥻',type:'armor',slot:'armor',rarity:'unique',reqLevel:28,value:315,armor:8,power:8,set:'mist',classes:['mage']},
 ashMail:{id:'ashMail',name:'Pancerz Popielnej Straży',icon:'🛡️',type:'armor',slot:'armor',rarity:'unique',reqLevel:36,value:410,armor:20,power:4,set:'ashguard',classes:['knight','berserker']},
 ashLeathers:{id:'ashLeathers',name:'Skóry Popielnego Szlaku',icon:'🥋',type:'armor',slot:'armor',rarity:'unique',reqLevel:36,value:405,armor:14,crit:6,set:'ashguard',classes:['hunter','ranger']},
 ashRobe:{id:'ashRobe',name:'Szata Popielnego Kręgu',icon:'🥻',type:'armor',slot:'armor',rarity:'unique',reqLevel:36,value:408,armor:10,power:9,set:'ashguard',classes:['mage']},
 stormMail:{id:'stormMail',name:'Pancerz Nawałnicy',icon:'🛡️',type:'armor',slot:'armor',rarity:'unique',reqLevel:45,value:540,armor:24,power:5,set:'stormforged',classes:['knight','berserker']},
 stormLeathers:{id:'stormLeathers',name:'Skóry Nawałnicy',icon:'🥋',type:'armor',slot:'armor',rarity:'unique',reqLevel:45,value:535,armor:17,crit:7,set:'stormforged',classes:['hunter','ranger']},
 stormRobe:{id:'stormRobe',name:'Szata Nawałnicy',icon:'🥻',type:'armor',slot:'armor',rarity:'unique',reqLevel:45,value:538,armor:12,power:11,set:'stormforged',classes:['mage']},

 // HEŁMY / RĘKAWICE / BUTY / DRUGA RĘKA
 scoutHood:{id:'scoutHood',name:'Kaptur zwiadowcy',icon:'🥷',type:'gear',slot:'helmet',rarity:'common',reqLevel:4,value:34,armor:2,crit:1,classes:['hunter','ranger']},
 ironHelm:{id:'ironHelm',name:'Żelazny hełm',icon:'⛑️',type:'gear',slot:'helmet',rarity:'epic',reqLevel:9,value:82,armor:6,classes:['knight','berserker']},
 mageHood:{id:'mageHood',name:'Kaptur adepta',icon:'🧙',type:'gear',slot:'helmet',rarity:'common',reqLevel:5,value:40,armor:1,power:2,classes:['mage']},
 leatherGloves:{id:'leatherGloves',name:'Rękawice wędrowca',icon:'🧤',type:'gear',slot:'gloves',rarity:'common',reqLevel:4,value:28,armor:1,power:1,classes:['knight','mage','hunter','berserker','ranger']},
 ironGauntlets:{id:'ironGauntlets',name:'Żelazne rękawice',icon:'🧤',type:'gear',slot:'gloves',rarity:'epic',reqLevel:10,value:64,armor:4,power:2,classes:['knight','berserker']},
 trailBoots:{id:'trailBoots',name:'Buty Zielonego Szlaku',icon:'🥾',type:'gear',slot:'boots',rarity:'common',reqLevel:5,value:32,armor:1,crit:2,classes:['hunter','ranger']},
 ironBoots:{id:'ironBoots',name:'Okute buty',icon:'🥾',type:'gear',slot:'boots',rarity:'epic',reqLevel:8,value:58,armor:4,classes:['knight','berserker']},
 mageShoes:{id:'mageShoes',name:'Miękkie buty maga',icon:'🥾',type:'gear',slot:'boots',rarity:'common',reqLevel:5,value:36,armor:1,power:1,classes:['mage']},
 woodenShield:{id:'woodenShield',name:'Okrągła drewniana tarcza',icon:'🛡️',type:'gear',slot:'offhand',rarity:'common',reqLevel:4,value:38,armor:4,classes:['knight']},
 ironShield:{id:'ironShield',name:'Żelazna tarcza',icon:'🛡️',type:'gear',slot:'offhand',rarity:'epic',reqLevel:10,value:88,armor:8,classes:['knight']},
 ravenHelm:{id:'ravenHelm',name:'Kruczy Hełm',icon:'🪖',type:'gear',slot:'helmet',rarity:'unique',reqLevel:20,value:215,armor:8,crit:3,set:'raven',classes:['knight','berserker']},
 wildHood:{id:'wildHood',name:'Kaptur Dzikiego Szlaku',icon:'🥷',type:'gear',slot:'helmet',rarity:'unique',reqLevel:20,value:205,armor:5,crit:5,set:'wild',classes:['hunter','ranger']},
 wildBoots:{id:'wildBoots',name:'Buty Dzikiego Szlaku',icon:'🥾',type:'gear',slot:'boots',rarity:'unique',reqLevel:20,value:190,armor:4,crit:4,power:2,set:'wild',classes:['hunter','ranger']},
 mistHelm:{id:'mistHelm',name:'Hełm Strażnika Mgieł',icon:'🪖',type:'gear',slot:'helmet',rarity:'unique',reqLevel:28,value:290,armor:10,crit:3,set:'mist',classes:['knight','berserker']},
 mistHood:{id:'mistHood',name:'Kaptur Mgieł',icon:'🥷',type:'gear',slot:'helmet',rarity:'unique',reqLevel:28,value:285,armor:7,crit:6,set:'mist',classes:['hunter','ranger']},
 mistCirclet:{id:'mistCirclet',name:'Diadem Mgieł',icon:'👑',type:'gear',slot:'helmet',rarity:'unique',reqLevel:28,value:288,armor:5,power:5,crit:3,set:'mist',classes:['mage']},
 ashHelm:{id:'ashHelm',name:'Hełm Popielnej Straży',icon:'🪖',type:'gear',slot:'helmet',rarity:'unique',reqLevel:36,value:390,armor:12,crit:3,set:'ashguard',classes:['knight','berserker']},
 ashHood:{id:'ashHood',name:'Kaptur Popielnego Szlaku',icon:'🥷',type:'gear',slot:'helmet',rarity:'unique',reqLevel:36,value:385,armor:8,crit:7,set:'ashguard',classes:['hunter','ranger']},
 ashCowl:{id:'ashCowl',name:'Kaptur Żaromanty',icon:'🧙',type:'gear',slot:'helmet',rarity:'unique',reqLevel:36,value:388,armor:6,power:6,crit:4,set:'ashguard',classes:['mage']},
 stormHelm:{id:'stormHelm',name:'Hełm Nawałnicy',icon:'🪖',type:'gear',slot:'helmet',rarity:'unique',reqLevel:45,value:510,armor:15,crit:4,set:'stormforged',classes:['knight','berserker']},
 stormHood:{id:'stormHood',name:'Kaptur Nawałnicy',icon:'🥷',type:'gear',slot:'helmet',rarity:'unique',reqLevel:45,value:505,armor:10,crit:8,set:'stormforged',classes:['hunter','ranger']},
 stormCowl:{id:'stormCowl',name:'Korona Burzowego Maga',icon:'👑',type:'gear',slot:'helmet',rarity:'unique',reqLevel:45,value:508,armor:7,power:7,crit:5,set:'stormforged',classes:['mage']},

 // BIŻUTERIA
 shadowRing:{id:'shadowRing',name:'Pierścień Cienia',icon:'💍',type:'trinket',slot:'ring',rarity:'unique',reqLevel:18,value:260,crit:8},
 emberRing:{id:'emberRing',name:'Pierścień Żaru',icon:'💍',type:'trinket',slot:'ring',rarity:'epic',reqLevel:12,value:135,power:4,crit:2},
 wolfCharm:{id:'wolfCharm',name:'Wilczy amulet',icon:'📿',type:'trinket',slot:'amulet',rarity:'epic',reqLevel:8,value:95,crit:4,power:2},
 oldTalisman:{id:'oldTalisman',name:'Stary talizman',icon:'📿',type:'trinket',slot:'amulet',rarity:'uncommon',reqLevel:4,value:42,crit:2},
 boneRing:{id:'boneRing',name:'Pierścień z kości',icon:'💍',type:'trinket',slot:'ring',rarity:'uncommon',reqLevel:6,value:50,armor:1,power:1},
 mireCharm:{id:'mireCharm',name:'Amulet Zatopionego Dzwonu',icon:'📿',type:'trinket',slot:'amulet',rarity:'heroic',reqLevel:28,value:390,power:5,armor:4,crit:4},
 cinderCharm:{id:'cinderCharm',name:'Amulet Serca Żaru',icon:'📿',type:'trinket',slot:'amulet',rarity:'heroic',reqLevel:36,value:490,power:7,armor:4,crit:5},
 tempestCharm:{id:'tempestCharm',name:'Amulet Nawałnicy',icon:'📿',type:'trinket',slot:'amulet',rarity:'heroic',reqLevel:45,value:640,power:9,armor:5,crit:6},
 stormCrown:{id:'stormCrown',name:'Korona Burz',icon:'👑',type:'gear',slot:'helmet',rarity:'legendary',reqLevel:48,value:680,armor:10,crit:8,power:7},
 cryptHeart:{id:'cryptHeart',name:'Serce Kurhanu',icon:'🫀',type:'trinket',slot:'amulet',rarity:'legendary',reqLevel:30,value:620,armor:5,crit:6,power:7},

 // MIKSTURY / MATERIAŁY
 potion:{id:'potion',name:'Mikstura życia',icon:'🧪',type:'consumable',rarity:'common',value:12,heal:55},
 strongPotion:{id:'strongPotion',name:'Większa mikstura życia',icon:'❤️‍🔥',type:'consumable',rarity:'rare',value:34,heal:130},
 manaPotion:{id:'manaPotion',name:'Mikstura many',icon:'🔷',type:'consumable',rarity:'common',value:14,mana:50},
 antidote:{id:'antidote',name:'Odtrutka',icon:'🍶',type:'consumable',rarity:'common',value:10},
 wolfPelt:{id:'wolfPelt',name:'Wilcza skóra',icon:'🧶',type:'material',rarity:'common',value:8,maxStack:99},

 // LOOT 2.9 — materiały z konkretnych stworów
 rawMeat:{id:'rawMeat',name:'Surowe mięso',icon:'🥩',type:'material',rarity:'common',value:4,maxStack:99},
 ratTail:{id:'ratTail',name:'Szczurzy ogon',icon:'🐀',type:'material',rarity:'common',value:3,maxStack:99},
 slimeGel:{id:'slimeGel',name:'Śluz pełzacza',icon:'🟢',type:'material',rarity:'common',value:4,maxStack:99},
 beetleCarapace:{id:'beetleCarapace',name:'Pancerz owada',icon:'🪲',type:'material',rarity:'common',value:6,maxStack:99},
 wolfFang:{id:'wolfFang',name:'Wilczy kieł',icon:'🦷',type:'material',rarity:'uncommon',value:10,maxStack:99},
 goblinEar:{id:'goblinEar',name:'Goblińskie ucho',icon:'👂',type:'material',rarity:'common',value:7,maxStack:99},
 goblinMapScrap:{id:'goblinMapScrap',name:'Skrawek goblińskiej mapy',icon:'🗺️',type:'material',rarity:'uncommon',value:12,maxStack:99},
 dentedBuckler:{id:'dentedBuckler',name:'Wgnieciony puklerz',icon:'🛡️',type:'material',rarity:'uncommon',value:16,maxStack:99},
 goblinFocus:{id:'goblinFocus',name:'Gobliński fokus zaklęć',icon:'🔮',type:'material',rarity:'rare',value:26,maxStack:99},
 goblinBanner:{id:'goblinBanner',name:'Strzęp sztandaru czempiona',icon:'🚩',type:'material',rarity:'rare',value:34,maxStack:99},
 hardenedMark:{id:'hardenedMark',name:'Znak zahartowania',icon:'⚔️',type:'material',rarity:'uncommon',value:18,maxStack:99},
 corruptedEssence:{id:'corruptedEssence',name:'Skażona esencja',icon:'🟣',type:'material',rarity:'rare',value:38,maxStack:99},
 ancientRelic:{id:'ancientRelic',name:'Pradawny relikt',icon:'🏺',type:'material',rarity:'epic',value:82,maxStack:99},
 roughCloth:{id:'roughCloth',name:'Szorstkie płótno',icon:'🧵',type:'material',rarity:'common',value:6,maxStack:99},
 brokenBlade:{id:'brokenBlade',name:'Odłamek ostrza',icon:'🗡️',type:'material',rarity:'uncommon',value:10,maxStack:99},
 oldCoin:{id:'oldCoin',name:'Stara moneta',icon:'🪙',type:'material',rarity:'common',value:5,maxStack:99},
 ectoplasm:{id:'ectoplasm',name:'Ektoplazma',icon:'🫧',type:'material',rarity:'uncommon',value:13,maxStack:99},
 graveDust:{id:'graveDust',name:'Pył grobowy',icon:'🌫️',type:'material',rarity:'uncommon',value:11,maxStack:99},
 stoneCore:{id:'stoneCore',name:'Kamienny rdzeń',icon:'🪨',type:'material',rarity:'uncommon',value:14,maxStack:99},
 cultistSigil:{id:'cultistSigil',name:'Znak kultysty',icon:'🔻',type:'material',rarity:'uncommon',value:15,maxStack:99},
 demonHorn:{id:'demonHorn',name:'Demoniczny róg',icon:'😈',type:'material',rarity:'rare',value:28,maxStack:99},
 demonBlood:{id:'demonBlood',name:'Demoniczna krew',icon:'🩸',type:'material',rarity:'rare',value:30,maxStack:99},
 sulfur:{id:'sulfur',name:'Siarka',icon:'🟡',type:'material',rarity:'uncommon',value:14,maxStack:99},
 hellhoundFang:{id:'hellhoundFang',name:'Kieł piekielnego ogara',icon:'🦷',type:'material',rarity:'rare',value:32,maxStack:99},
 charredHide:{id:'charredHide',name:'Zwęglona skóra',icon:'⬛',type:'material',rarity:'uncommon',value:18,maxStack:99},
 wyvernScale:{id:'wyvernScale',name:'Łuska wywerny',icon:'🐉',type:'material',rarity:'rare',value:38,maxStack:99},
 wyvernClaw:{id:'wyvernClaw',name:'Szpon wywerny',icon:'🦅',type:'material',rarity:'rare',value:42,maxStack:99},
 shadowEssence:{id:'shadowEssence',name:'Esencja cienia',icon:'🌑',type:'material',rarity:'rare',value:26,maxStack:99},
 spiderSilk:{id:'spiderSilk',name:'Pajęcza nić',icon:'🕸️',type:'material',rarity:'common',value:8,maxStack:99},
 venomGland:{id:'venomGland',name:'Gruczoł jadowy',icon:'☠️',type:'material',rarity:'uncommon',value:14,maxStack:99},
 ogreHide:{id:'ogreHide',name:'Skóra ogra',icon:'🟫',type:'material',rarity:'uncommon',value:22,maxStack:99},
 ogreTooth:{id:'ogreTooth',name:'Ząb ogra',icon:'🦷',type:'material',rarity:'rare',value:30,maxStack:99},
 stormScale:{id:'stormScale',name:'Łuska burzowego smoka',icon:'🔷',type:'material',rarity:'rare',value:44,maxStack:99},
 swampScale:{id:'swampScale',name:'Łuska trzcinowego łowcy',icon:'🦎',type:'material',rarity:'uncommon',value:17,maxStack:99},
 rotSigil:{id:'rotSigil',name:'Znak zgnilizny',icon:'☣️',type:'material',rarity:'rare',value:24,maxStack:99},
 hagCharm:{id:'hagCharm',name:'Talizman wiedźmy',icon:'🧿',type:'material',rarity:'rare',value:32,maxStack:99},
 ancientBark:{id:'ancientBark',name:'Prastara kora',icon:'🪵',type:'material',rarity:'uncommon',value:20,maxStack:99},
 blackroot:{id:'blackroot',name:'Czarny korzeń',icon:'🌱',type:'material',rarity:'rare',value:28,maxStack:99},
 mireSilk:{id:'mireSilk',name:'Nić Matki Mgły',icon:'🕸️',type:'material',rarity:'epic',value:52,maxStack:99},
 scorchedBone:{id:'scorchedBone',name:'Zwęglona kość',icon:'🦴',type:'material',rarity:'uncommon',value:18,maxStack:99},
 fireWing:{id:'fireWing',name:'Skrzydło ognistej osy',icon:'🪽',type:'material',rarity:'rare',value:27,maxStack:99},
 ashScale:{id:'ashScale',name:'Popielna łuska',icon:'🐲',type:'material',rarity:'rare',value:36,maxStack:99},
 frostClaw:{id:'frostClaw',name:'Mroźny pazur',icon:'❄️',type:'material',rarity:'rare',value:34,maxStack:99},
 stormCore:{id:'stormCore',name:'Rdzeń burzy',icon:'⚡',type:'material',rarity:'epic',value:58,maxStack:99},
 trollHide:{id:'trollHide',name:'Skóra trolla',icon:'🟫',type:'material',rarity:'rare',value:35,maxStack:99},
 trollTooth:{id:'trollTooth',name:'Ząb trolla',icon:'🦷',type:'material',rarity:'rare',value:38,maxStack:99},
 skyScale:{id:'skyScale',name:'Łuska węża niebios',icon:'🐍',type:'material',rarity:'rare',value:42,maxStack:99},
 herb:{id:'herb',name:'Jaskółcze ziele',icon:'🌿',type:'material',rarity:'common',value:4,maxStack:99},
 moonHerb:{id:'moonHerb',name:'Księżycowe ziele',icon:'☘️',type:'material',rarity:'rare',value:10,maxStack:99},
 bone:{id:'bone',name:'Kość nieumarłego',icon:'🦴',type:'material',rarity:'common',value:6,maxStack:99},
 scrap:{id:'scrap',name:'Żelazny złom',icon:'🔩',type:'material',rarity:'common',value:6,maxStack:99},
 crystal:{id:'crystal',name:'Odłamek kryształu',icon:'💎',type:'material',rarity:'rare',value:15,maxStack:99},
 blackMedallion:{id:'blackMedallion',name:'Czarny medalion',icon:'📿',type:'quest',rarity:'epic',value:0},
 titanShard:{id:'titanShard',name:'Odłamek Tytana',icon:'🔶',type:'material',rarity:'legendary',value:90,maxStack:99},
 runeShard:{id:'runeShard',name:'Odłamek runiczny',icon:'🔹',type:'material',rarity:'uncommon',value:14,maxStack:99},
 runePower:{id:'runePower',name:'Runa Mocy',icon:'🔴',type:'rune',rarity:'rare',value:70,runeKey:'power',runeValue:3},
 runeGuard:{id:'runeGuard',name:'Runa Straży',icon:'🔵',type:'rune',rarity:'rare',value:70,runeKey:'armor',runeValue:3},
 runePrecision:{id:'runePrecision',name:'Runa Precyzji',icon:'🟣',type:'rune',rarity:'rare',value:80,runeKey:'crit',runeValue:3},
 mireMoss:{id:'mireMoss',name:'Mech Moczaru',icon:'🌿',type:'material',rarity:'uncommon',value:13,maxStack:99},
 bogAmber:{id:'bogAmber',name:'Bagienny Bursztyn',icon:'🟠',type:'material',rarity:'rare',value:28,maxStack:99},
 wraithEssence:{id:'wraithEssence',name:'Esencja Topielca',icon:'💧',type:'material',rarity:'rare',value:32,maxStack:99},
 charredIron:{id:'charredIron',name:'Zwęglone żelazo',icon:'⚙️',type:'material',rarity:'uncommon',value:18,maxStack:99},
 ashGlass:{id:'ashGlass',name:'Popielne szkło',icon:'🔸',type:'material',rarity:'rare',value:30,maxStack:99},
 emberCore:{id:'emberCore',name:'Rdzeń żaru',icon:'🔥',type:'material',rarity:'rare',value:38,maxStack:99},
 frostCrystal:{id:'frostCrystal',name:'Kryształ mrozu',icon:'❄️',type:'material',rarity:'rare',value:34,maxStack:99},
 stormFeather:{id:'stormFeather',name:'Pióro burzy',icon:'🪶',type:'material',rarity:'rare',value:36,maxStack:99},
 skySteel:{id:'skySteel',name:'Stal niebios',icon:'⚡',type:'material',rarity:'epic',value:50,maxStack:99}
};

export const SKILLS = {
 knight:[
  {id:'shield',branch:'Bastion',name:'Uderzenie tarczą',icon:'🛡️',req:1,cost:1,mana:8,kind:'damage',mult:1.25,cooldown:1,status:'stun',statusChance:.18,desc:'125% obrażeń, osłabienie ataku i szansa na ogłuszenie.',debuff:0.15},
  {id:'fortress',branch:'Bastion',name:'Żelazna Forteca',icon:'🏰',req:3,cost:1,mana:12,kind:'guard',turns:2,cooldown:3,requires:'shield',desc:'Przez 2 tury otrzymujesz znacznie mniej obrażeń.'},
  {id:'lastStand',branch:'Bastion',name:'Ostatni Bastion',icon:'⚜️',req:12,cost:2,mana:22,kind:'buff',buff:'block',value:24,turns:3,cooldown:5,requires:'fortress',desc:'Przez 3 tury ogromnie zwiększa blok i wzmacnia postawę obronną.'},
  {id:'counter',branch:'Odwet',name:'Kontratak',icon:'↩️',req:4,cost:1,mana:10,kind:'damage',mult:1.5,cooldown:1,desc:'150% obrażeń. Stabilny kontratak.'},
  {id:'breaker',branch:'Odwet',name:'Łamacz Gardy',icon:'🔨',req:8,cost:2,mana:18,kind:'damage',mult:2.0,cooldown:3,requires:'counter',desc:'200% obrażeń i bardzo wysokie przełamanie.'},
  {id:'riposte',branch:'Odwet',name:'Riposta Strażnika',icon:'⚔️',req:14,cost:2,mana:20,kind:'damage',mult:2.35,cooldown:4,requires:'breaker',status:'bleed',statusTurns:3,statusChance:.55,desc:'235% obrażeń i duża szansa na krwawienie.'},
  {id:'taunt',branch:'Dowodzenie',name:'Prowokacja',icon:'📣',req:6,cost:2,mana:14,kind:'debuff',debuff:0.30,cooldown:3,desc:'Mocno obniża atak przeciwnika na 3 tury.'},
  {id:'rally',branch:'Dowodzenie',name:'Zew Straży',icon:'🚩',req:9,cost:2,mana:16,kind:'buff',buff:'power',value:22,turns:3,cooldown:4,requires:'taunt',desc:'Przez 3 tury zwiększa zadawane obrażenia.'},
  {id:'banner',branch:'Dowodzenie',name:'Sztandar Niezłomnych',icon:'🏳️',req:16,cost:3,mana:24,kind:'buff',buff:'block',value:18,turns:4,cooldown:6,requires:'rally',desc:'Długi defensywny buff: blok i odporność w kluczowym momencie.'}
 ],
 mage:[
  {id:'fire',branch:'Ogień',name:'Ognisty pocisk',icon:'🔥',req:1,cost:1,mana:12,kind:'damage',mult:1.55,cooldown:0,status:'burn',statusTurns:2,statusChance:.45,desc:'155% obrażeń magicznych i szansa na podpalenie.'},
  {id:'elemental',branch:'Ogień',name:'Eksplozja Żywiołów',icon:'💥',req:6,cost:2,mana:28,kind:'damage',mult:2.35,cooldown:3,requires:'fire',status:'burn',statusTurns:3,statusChance:.65,desc:'Potężny atak i silne podpalenie.'},
  {id:'meteor',branch:'Ogień',name:'Meteor',icon:'☄️',req:12,cost:2,mana:36,kind:'damage',mult:3.0,cooldown:5,requires:'elemental',status:'burn',statusTurns:4,statusChance:1,desc:'300% obrażeń. Zawsze podpala trafiony cel.'},
  {id:'frost',branch:'Lód',name:'Lodowa pieczęć',icon:'❄️',req:3,cost:1,mana:16,kind:'damage',mult:1.20,cooldown:1,status:'freeze',statusTurns:2,statusChance:.6,desc:'120% obrażeń, osłabienie i szansa na zamrożenie.',debuff:0.20},
  {id:'iceArmor',branch:'Lód',name:'Pancerz Lodu',icon:'🧊',req:7,cost:2,mana:20,kind:'buff',buff:'block',value:18,turns:2,cooldown:4,requires:'frost',desc:'Zwiększa redukcję obrażeń i blok przez 2 tury.'},
  {id:'frostNova',branch:'Lód',name:'Nova Mrozu',icon:'🌨️',req:14,cost:2,mana:30,kind:'damage',mult:1.85,cooldown:4,requires:'iceArmor',status:'freeze',statusTurns:3,statusChance:1,desc:'185% obrażeń i gwarantowane zamrożenie.'},
  {id:'spark',branch:'Arkanum',name:'Łańcuch Iskier',icon:'⚡',req:4,cost:1,mana:15,kind:'multi',hits:2,mult:.9,cooldown:1,desc:'Dwa magiczne trafienia po 90%.'},
  {id:'arcaneSurge',branch:'Arkanum',name:'Przypływ Arkanum',icon:'🔷',req:9,cost:2,mana:18,kind:'buff',buff:'crit',value:22,turns:3,cooldown:4,requires:'spark',desc:'Przez 3 tury mocno zwiększa szansę na krytyczne czary.'},
  {id:'arcaneRift',branch:'Arkanum',name:'Szczelina Arkanum',icon:'🌀',req:16,cost:3,mana:40,kind:'damage',mult:2.65,cooldown:5,requires:'arcaneSurge',status:'stun',statusChance:.5,desc:'265% obrażeń i szansa na ogłuszenie przeciwnika.'}
 ],
 hunter:[
  {id:'double',branch:'Strzelectwo',name:'Podwójny strzał',icon:'🏹',req:1,cost:1,mana:10,kind:'multi',hits:2,mult:0.82,cooldown:0,desc:'Dwa trafienia po 82% obrażeń.'},
  {id:'mark',branch:'Strzelectwo',name:'Znak łowcy',icon:'🎯',req:3,cost:1,mana:12,kind:'mark',turns:3,cooldown:2,requires:'double',desc:'Przez 3 tury +25% szansy na krytyk.'},
  {id:'eagleEye',branch:'Strzelectwo',name:'Sokole Oko',icon:'🦅',req:7,cost:2,mana:18,kind:'damage',mult:1.7,critBonus:30,cooldown:2,requires:'mark',desc:'170% obrażeń i wysoka szansa na krytyk.'},
  {id:'petStrike',branch:'Bestia',name:'Skoordynowany Strzał',icon:'🐺',req:6,cost:2,mana:18,kind:'pet',mult:1.45,cooldown:2,desc:'145% obrażeń, a aktywny pupil zawsze atakuje.'},
  {id:'pack',branch:'Bestia',name:'Zew Stada',icon:'🐾',req:9,cost:2,mana:20,kind:'pet',mult:1.6,cooldown:3,requires:'petStrike',desc:'Silny wspólny atak z chowańcem.'},
  {id:'beastFury',branch:'Bestia',name:'Furia Towarzysza',icon:'🐺',req:15,cost:3,mana:24,kind:'pet',mult:2.0,cooldown:5,requires:'pack',status:'bleed',statusTurns:3,statusChance:.7,desc:'Potężny wspólny atak i krwawienie.'},
  {id:'volley',branch:'Przetrwanie',name:'Salwa',icon:'🌧️',req:12,cost:2,mana:26,kind:'multi',hits:3,mult:.76,cooldown:3,desc:'Trzy szybkie trafienia po 76%.'},
  {id:'camouflage',branch:'Przetrwanie',name:'Kamuflaż',icon:'🌲',req:8,cost:2,mana:14,kind:'buff',buff:'dodge',value:24,turns:3,cooldown:4,desc:'Przez 3 tury wyraźnie zwiększa unik.'},
  {id:'piercingShot',branch:'Przetrwanie',name:'Przeszywający Strzał',icon:'➶',req:16,cost:3,mana:28,kind:'damage',mult:2.45,cooldown:4,requires:'camouflage',status:'bleed',statusTurns:4,statusChance:.75,desc:'245% obrażeń, wysokie przełamanie i krwawienie.'}
 ],
 berserker:[
  {id:'rage',branch:'Furia',name:'Furia',icon:'😡',req:1,cost:1,mana:6,kind:'rage',cooldown:0,desc:'Cios rośnie wraz z utraconym HP.'},
  {id:'roar',branch:'Furia',name:'Ryk Wojenny',icon:'📢',req:5,cost:1,mana:8,kind:'debuff',debuff:.22,cooldown:2,requires:'rage',desc:'Osłabia atak przeciwnika.'},
  {id:'berserk',branch:'Furia',name:'Szał Berserkera',icon:'🔥',req:12,cost:2,mana:18,kind:'rage',cooldown:4,requires:'roar',status:'bleed',statusTurns:3,statusChance:.6,desc:'Potężny cios skalujący się z utraconym HP i krwawienie.'},
  {id:'cleave',branch:'Rzeź',name:'Rozłupanie',icon:'🪓',req:3,cost:1,mana:10,kind:'damage',mult:1.75,cooldown:1,status:'bleed',statusTurns:2,statusChance:.35,desc:'Silny cios i szansa na krwawienie.'},
  {id:'blood',branch:'Rzeź',name:'Krwawy Taniec',icon:'🩸',req:6,cost:2,mana:16,kind:'multi',hits:3,mult:0.72,cooldown:2,requires:'cleave',status:'bleed',statusTurns:3,statusChance:.65,desc:'Trzy szybkie ciosy i krwawienie.'},
  {id:'execution',branch:'Rzeź',name:'Egzekucja',icon:'⚔️',req:9,cost:2,mana:15,kind:'damage',mult:2.25,cooldown:3,requires:'blood',desc:'225% obrażeń. Szczególnie mocna przy niskim HP.'},
  {id:'dualCut',branch:'Dwa Ostrza',name:'Podwójne Cięcie',icon:'⚔️',req:4,cost:1,mana:10,kind:'multi',hits:2,mult:.92,cooldown:1,desc:'Dwa szybkie ciosy. Najlepsze przy dwóch broniach.'},
  {id:'whirlwind',branch:'Dwa Ostrza',name:'Wir Ostrzy',icon:'🌪️',req:9,cost:2,mana:18,kind:'multi',hits:3,mult:.82,cooldown:3,requires:'dualCut',desc:'Trzy agresywne cięcia.'},
  {id:'bloodRush',branch:'Dwa Ostrza',name:'Krwawy Pęd',icon:'💢',req:16,cost:3,mana:22,kind:'buff',buff:'power',value:30,turns:3,cooldown:5,requires:'whirlwind',desc:'Przez 3 tury znacząco zwiększa obrażenia.'}
 ],
 ranger:[
  {id:'poison',branch:'Trucizny',name:'Zatruty grot',icon:'☠️',req:1,cost:1,mana:10,kind:'poison',mult:1.05,turns:3,cooldown:0,desc:'105% obrażeń i trucizna przez 3 tury.'},
  {id:'destiny',branch:'Trucizny',name:'Strzała Przeznaczenia',icon:'🌠',req:6,cost:2,mana:20,kind:'damage',mult:2.0,critBonus:20,cooldown:2,requires:'poison',desc:'200% obrażeń i +20% szansy na krytyk.'},
  {id:'venomRain',branch:'Trucizny',name:'Deszcz Jadu',icon:'🌧️',req:12,cost:2,mana:26,kind:'poison',mult:1.65,turns:4,cooldown:4,requires:'destiny',desc:'Silny strzał i dłuższa trucizna.'},
  {id:'trap',branch:'Pułapki',name:'Leśna pułapka',icon:'🪤',req:3,cost:1,mana:12,kind:'debuff',debuff:0.25,cooldown:2,desc:'Obniża atak przeciwnika na 3 tury.'},
  {id:'vine',branch:'Pułapki',name:'Pnącza',icon:'🌱',req:6,cost:1,mana:14,kind:'debuff',debuff:.32,cooldown:3,requires:'trap',desc:'Mocne osłabienie przeciwnika.'},
  {id:'snareShot',branch:'Pułapki',name:'Strzał Unieruchamiający',icon:'🪢',req:14,cost:2,mana:22,kind:'damage',mult:1.55,cooldown:4,requires:'vine',status:'stun',statusChance:.65,desc:'155% obrażeń i duża szansa na ogłuszenie.'},
  {id:'spirit',branch:'Duch Natury',name:'Duch Lasu',icon:'🦊',req:8,cost:2,mana:18,kind:'pet',mult:1.5,cooldown:2,desc:'Wspólny atak z aktywnym chowańcem.'},
  {id:'windStep',branch:'Duch Natury',name:'Krok Wiatru',icon:'🍃',req:10,cost:2,mana:16,kind:'buff',buff:'dodge',value:28,turns:3,cooldown:4,requires:'spirit',desc:'Przez 3 tury mocno zwiększa unik.'},
  {id:'wildFocus',branch:'Duch Natury',name:'Instynkt Drapieżcy',icon:'👁️',req:16,cost:3,mana:24,kind:'buff',buff:'crit',value:25,turns:3,cooldown:5,requires:'windStep',desc:'Przez 3 tury zwiększa szansę na krytyk.'}
 ]
};

export const PETS = {
 youngWolf:{id:'youngWolf',name:'Młody Wilk',icon:'🐺',power:7,skill:'Rozszarpanie',passive:'+ regularne ataki',desc:'Wierny kompan. Często dobija osłabionych przeciwników.'},
 raven:{id:'raven',name:'Kruk',icon:'🐦‍⬛',power:6,crit:4,skill:'Pikowanie',passive:'+4% krytyka',desc:'Zwiększa szansę na krytyk i atakuje z powietrza.'},
 forestLynx:{id:'forestLynx',name:'Ryś Leśny',icon:'🐈',power:10,skill:'Skok',passive:'+ obrażenia',desc:'Rzadki, ofensywny pupil Tropicieli i Łowców.'},
 emberling:{id:'emberling',name:'Żaroptak',icon:'🐦',power:12,crit:2,skill:'Iskra',passive:'+2% krytyka',desc:'Rzadki ptak znaleziony przy czerwonych strefach.'},
 shadowFox:{id:'shadowFox',name:'Lis Cienia',icon:'🦊',power:9,crit:5,skill:'Zniknięcie',passive:'+5% krytyka',desc:'Niezwykle rzadki chowaniec związany z ruinami.'},
 mireLynx:{id:'mireLynx',name:'Ryś Mgieł',icon:'🐈‍⬛',power:14,crit:6,skill:'Skok zza mgły',passive:'+6% krytyka',desc:'Rzadki drapieżnik Mokradeł Echa. Atakuje z zasadzki i wzmacnia krytyki.'},
 cinderHound:{id:'cinderHound',name:'Ogar Popiołu',icon:'🐕',power:17,crit:5,skill:'Skok przez żar',passive:'+5% krytyka',desc:'Drapieżnik Popielnych Pustkowi. Wyczuwa elity i atakuje bez ostrzeżenia.'},
 stormHawk:{id:'stormHawk',name:'Jastrząb Burzy',icon:'🦅',power:20,crit:7,skill:'Pikowanie gromu',passive:'+7% krytyka',desc:'Rzadki ptak Rozbitych Szczytów. Najsilniejszy chowaniec eksploracyjny tej części świata.'}
};

export const RECIPES = [
 {id:'potion',station:'alchemist',name:'Mikstura życia',result:'potion',qty:1,ingredients:{herb:2}},
 {id:'manaPotion',station:'alchemist',name:'Mikstura many',result:'manaPotion',qty:1,ingredients:{herb:1,crystal:1}},
 {id:'strongPotion',station:'alchemist',name:'Większa mikstura życia',result:'strongPotion',qty:1,ingredients:{herb:2,moonHerb:1}},
 {id:'antidote',station:'alchemist',name:'Odtrutka',result:'antidote',qty:1,ingredients:{herb:1,venomGland:1}},
 {id:'strongPotion2',station:'alchemist',name:'Większa mikstura życia',result:'strongPotion',qty:1,ingredients:{herb:2,moonHerb:1,slimeGel:1}},
 {id:'manaPotion2',station:'alchemist',name:'Mikstura many z ektoplazmy',result:'manaPotion',qty:2,ingredients:{herb:1,ectoplasm:1,crystal:1}},
 {id:'runePower',station:'smith',name:'Runa Mocy',result:'runePower',qty:1,ingredients:{runeShard:2,crystal:1}},
 {id:'runeGuard',station:'smith',name:'Runa Straży',result:'runeGuard',qty:1,ingredients:{runeShard:2,scrap:2}},
 {id:'runePrecision',station:'smith',name:'Runa Precyzji',result:'runePrecision',qty:1,ingredients:{runeShard:2,moonHerb:1}},

 {id:'arrowBundle',station:'smith',name:'Pęk prymitywnych strzał',result:'primitiveArrow',qty:30,ingredients:{scrap:1,roughCloth:1}},
 {id:'rustySwordCraft',station:'smith',name:'Zardzewiały miecz',result:'rustySword',qty:1,ingredients:{scrap:3,brokenBlade:1}},
 {id:'shortSwordCraft',station:'smith',name:'Krótki miecz',result:'shortSword',qty:1,ingredients:{scrap:5,brokenBlade:2}},
 {id:'leatherGlovesCraft',station:'smith',name:'Rękawice wędrowca',result:'leatherGloves',qty:1,ingredients:{wolfPelt:2,roughCloth:2}},
 {id:'trailBootsCraft',station:'smith',name:'Buty Zielonego Szlaku',result:'trailBoots',qty:1,ingredients:{wolfPelt:3,spiderSilk:2,roughCloth:2}},
 {id:'wolfCharmCraft',station:'smith',name:'Wilczy amulet',result:'wolfCharm',qty:1,ingredients:{wolfFang:3,wolfPelt:2,crystal:1}},
 {id:'boneRingCraft',station:'smith',name:'Pierścień z kości',result:'boneRing',qty:1,ingredients:{bone:4,ectoplasm:1}},
 {id:'ironShieldCraft',station:'smith',name:'Żelazna tarcza',result:'ironShield',qty:1,ingredients:{scrap:7,beetleCarapace:2}},

 {id:'ravenBlade',station:'smith',name:'Krucze Ostrze',result:'ravenBlade',qty:1,ingredients:{scrap:5,crystal:2,bone:2}},
 {id:'ravenMail',station:'smith',name:'Kruczy Pancerz',result:'ravenMail',qty:1,ingredients:{scrap:6,wolfPelt:3,bone:2}},
 {id:'ravenHelm',station:'smith',name:'Kruczy Hełm',result:'ravenHelm',qty:1,ingredients:{scrap:4,crystal:1,bone:2}},
 {id:'wildBow',station:'smith',name:'Łuk Dzikiego Szlaku',result:'wildBow',qty:1,ingredients:{wolfPelt:4,crystal:2,scrap:2}},
 {id:'wildHood',station:'smith',name:'Kaptur Dzikiego Szlaku',result:'wildHood',qty:1,ingredients:{wolfPelt:3,moonHerb:2}},
 {id:'wildBoots',station:'smith',name:'Buty Dzikiego Szlaku',result:'wildBoots',qty:1,ingredients:{wolfPelt:3,herb:4,scrap:1}},
 {id:'mistBlade',station:'smith',name:'Ostrze Strażnika Mgieł',result:'mistBlade',qty:1,ingredients:{bogAmber:3,wraithEssence:2,scrap:4}},
 {id:'mistMail',station:'smith',name:'Pancerz Strażnika Mgieł',result:'mistMail',qty:1,ingredients:{mireMoss:5,bogAmber:2,scrap:5}},
 {id:'mistHood',station:'smith',name:'Kaptur Strażnika Mgieł',result:'mistHood',qty:1,ingredients:{mireMoss:3,wraithEssence:2,moonHerb:1}},
{id:'ashBlade',station:'smith',name:'Ostrze Popielnej Straży',result:'ashBlade',qty:1,ingredients:{ashGlass:3,emberCore:2,charredIron:5}},
 {id:'ashMail',station:'smith',name:'Pancerz Popielnej Straży',result:'ashMail',qty:1,ingredients:{charredIron:7,ashGlass:2,scrap:5}},
 {id:'ashHelm',station:'smith',name:'Hełm Popielnej Straży',result:'ashHelm',qty:1,ingredients:{charredIron:5,emberCore:1,crystal:2}},
 {id:'stormSpear',station:'smith',name:'Włócznia Nawałnicy',result:'stormSpear',qty:1,ingredients:{skySteel:3,stormFeather:2,frostCrystal:2}},
 {id:'stormMail',station:'smith',name:'Pancerz Nawałnicy',result:'stormMail',qty:1,ingredients:{skySteel:4,frostCrystal:3,scrap:6}},
 // Warianty klasowe późnych setów
 {id:'mistBow',station:'smith',name:'Łuk Mgieł',result:'mistBow',qty:1,ingredients:{bogAmber:3,wraithEssence:2,mireMoss:4}},
 {id:'mistStaff',station:'smith',name:'Kostur Mgieł',result:'mistStaff',qty:1,ingredients:{bogAmber:3,wraithEssence:3,crystal:2}},
 {id:'mistLeathers',station:'smith',name:'Skóry Mgieł',result:'mistLeathers',qty:1,ingredients:{mireMoss:6,bogAmber:2,wolfPelt:3}},
 {id:'mistRobe',station:'smith',name:'Szata Mgieł',result:'mistRobe',qty:1,ingredients:{mireMoss:5,wraithEssence:3,moonHerb:2}},
 {id:'mistHelm',station:'smith',name:'Hełm Strażnika Mgieł',result:'mistHelm',qty:1,ingredients:{bogAmber:2,scrap:4,wraithEssence:1}},
 {id:'mistCirclet',station:'smith',name:'Diadem Mgieł',result:'mistCirclet',qty:1,ingredients:{bogAmber:2,wraithEssence:2,crystal:1}},
 {id:'ashBow',station:'smith',name:'Łuk Popielnego Szlaku',result:'ashBow',qty:1,ingredients:{ashGlass:3,emberCore:2,charredIron:4}},
 {id:'ashStaff',station:'smith',name:'Kostur Popielnego Rdzenia',result:'ashStaff',qty:1,ingredients:{emberCore:3,ashGlass:3,crystal:2}},
 {id:'ashLeathers',station:'smith',name:'Skóry Popielnego Szlaku',result:'ashLeathers',qty:1,ingredients:{charredIron:5,ashGlass:3,wolfPelt:4}},
 {id:'ashRobe',station:'smith',name:'Szata Popielnego Kręgu',result:'ashRobe',qty:1,ingredients:{ashGlass:4,emberCore:2,moonHerb:3}},
 {id:'ashHood',station:'smith',name:'Kaptur Popielnego Szlaku',result:'ashHood',qty:1,ingredients:{ashGlass:2,charredIron:3,wolfPelt:2}},
 {id:'ashCowl',station:'smith',name:'Kaptur Żaromanty',result:'ashCowl',qty:1,ingredients:{ashGlass:2,emberCore:2,crystal:1}},
 {id:'stormBow',station:'smith',name:'Łuk Nawałnicy',result:'stormBow',qty:1,ingredients:{skySteel:3,stormFeather:4,frostCrystal:2}},
 {id:'stormStaff',station:'smith',name:'Kostur Serca Burzy',result:'stormStaff',qty:1,ingredients:{skySteel:3,frostCrystal:3,stormFeather:3}},
 {id:'stormLeathers',station:'smith',name:'Skóry Nawałnicy',result:'stormLeathers',qty:1,ingredients:{skySteel:3,stormFeather:4,wolfPelt:4}},
 {id:'stormRobe',station:'smith',name:'Szata Nawałnicy',result:'stormRobe',qty:1,ingredients:{frostCrystal:4,stormFeather:4,crystal:3}},
 {id:'stormHood',station:'smith',name:'Kaptur Nawałnicy',result:'stormHood',qty:1,ingredients:{stormFeather:4,frostCrystal:2,skySteel:1}},
 {id:'stormCowl',station:'smith',name:'Korona Burzowego Maga',result:'stormCowl',qty:1,ingredients:{stormFeather:3,frostCrystal:3,crystal:2}},
 {id:'stormHelm',station:'smith',name:'Korona Nawałnicy',result:'stormHelm',qty:1,ingredients:{skySteel:2,stormFeather:3,crystal:3}}
];

export const DUNGEONS = [
 {id:'trainingCellar',name:'Piwnica Pod Krukiem',icon:'🪜',x:-75,y:35,min:1,boss:'rat',desc:'Stara piwnica pod zapleczem karczmy. Idealne miejsce na pierwszą wyprawę: kilka korytarzy, prosta pułapka i zdziczały szczur, który zrobił tu legowisko.'},
 {id:'oldCrypt',name:'Stara Krypta',icon:'🕳️',x:185,y:-125,min:7,boss:'skeleton',desc:'Wilgotne podziemia pełne kości, run, pułapek i bocznych komnat.'},
 {id:'forgottenTower',name:'Zapomniana Wieża',icon:'🗼',x:-300,y:-170,min:18,boss:'cultist',desc:'Wieża starego zakonu. W środku słychać szepty.'},
 {id:'beastLair',name:'Legowisko Bestii',icon:'🦴',x:320,y:245,min:45,boss:'wyvern',desc:'Czarna strefa. W powietrzu czuć popiół i siarkę.'},
 {id:'sunkenChapel',name:'Zatopiona Kaplica',icon:'⛪',x:690,y:-310,min:23,boss:'bogWraith',desc:'Dzwon kaplicy słychać spod czarnej wody. W środku czają się topielcy i zgniłe korzenie.'},
 {id:'witchBarrow',name:'Kopiec Wiedźmy',icon:'🕯️',x:810,y:250,min:27,boss:'marshHag',desc:'Kamienny kopiec otoczony trzcinami. Runy na wejściu są świeże, choć miejsce wygląda na martwe od stuleci.'},
 {id:'blackrootKeep',name:'Twierdza Czarnego Korzenia',icon:'🌑',x:930,y:-40,min:30,boss:'mireMother',desc:'Serce Mokradeł Echa. Korzenie oplatają kamień, a mgła nie porusza się nawet przy silnym wietrze.'},
{id:'emberMine',name:'Kopalnia Żaru',icon:'⛏️',x:1165,y:-265,min:33,boss:'slagGolem',desc:'Korytarze pełne gorącego pyłu, żużlu i pękniętych pieców. W głębi porusza się coś z kamienia i ognia.'},
 {id:'ashenCitadel',name:'Popielna Cytadela',icon:'🏰',x:1360,y:40,min:40,boss:'cinderMatriarch',desc:'Twierdza kultu Żaru. W jej centrum płonie ogień, którego nikt nie podtrzymuje.'},
 {id:'frostVault',name:'Krypta Mrozu',icon:'🧊',x:1535,y:-250,min:43,boss:'iceWraith',desc:'Zamarznięte podziemia dawnych strażników. Ciszę przerywa tylko pękający lód.'},
 {id:'tempestSpire',name:'Iglica Nawałnicy',icon:'🗼',x:1810,y:55,min:50,boss:'tempestLord',desc:'Najwyższa wieża Rozbitych Szczytów. Pioruny uderzają w nią nawet przy czystym niebie.'}
];

export const QUESTS = [
 {id:'q1',chapter:'Cienie nad Doliną',name:'Pierwszy krok',level:1,desc:'Karczmarz prosi, abyś sprawdził drogę za wioską.',steps:[{type:'move',target:60,label:'Oddal się 60 m od wioski'},{type:'kill',target:'any',count:2,label:'Pokonaj 2 stworzenia'}],xp:150,gold:25},
 {id:'q2',chapter:'Cienie nad Doliną',name:'Zaginiona owca',level:2,desc:'Z pastwiska zniknęła owca. Każdy odnaleziony trop odsłania dopiero następny etap śledztwa.',steps:[{type:'questInteract',target:'q2_sheep',label:'Odnajdź zaginioną owcę'},{type:'questInteract',target:'q2_tracks',label:'Zbadaj wilcze tropy'},{type:'questInteract',target:'q2_wolves',label:'Odnajdź dwa ranne wilki'},{type:'story',target:'q2',label:'Zdecyduj, co zrobić z rannymi wilkami'}],xp:320,gold:45},
 {id:'q3',chapter:'Cienie nad Doliną',name:'Wilcza jama',level:3,desc:'Ranne wilki nie wyglądają na winnych. Przy jamie znajdujesz ślady butów i skrawki worków.',steps:[{type:'discover',target:'wolfDen',label:'Odnajdź wilczą jamę'},{type:'story',target:'q3',label:'Połącz znalezione ślady'}],xp:420,gold:55},
 {id:'q4',chapter:'Cienie nad Doliną',name:'Mapa',level:4,desc:'Fragment mapy wskazuje stare ruiny.',steps:[{type:'discover',target:'oldRuins',label:'Odkryj Stare Ruiny'}],xp:500,gold:70},
 {id:'q5',chapter:'Cienie nad Doliną',name:'Nie jesteśmy sami',level:4,desc:'Obserwuj ruiny i ustal, dokąd gobliny prowadzą łupy.',steps:[{type:'discover',target:'watchPoint',label:'Dotrzyj do punktu obserwacyjnego'}],xp:560,gold:75},
 {id:'q6',chapter:'Cienie nad Doliną',name:'Obserwator',level:5,desc:'Obóz żyje własnym rytmem. Możesz zachować dystans albo zaryzykować bliższe podejście.',steps:[{type:'discover',target:'goblinCamp',label:'Podejdź do obozu goblinów'},{type:'story',target:'q6',label:'Wybierz sposób obserwacji obozu'}],xp:650,gold:90},
 {id:'q7',chapter:'Cienie nad Doliną',name:'Zaginiony myśliwy',level:6,desc:'Myśliwy nie wrócił z patrolu. Na szlaku są ślady po walce i zerwany pasek od kołczanu.',steps:[{type:'discover',target:'hunterTrail',label:'Odnajdź ślady myśliwego'}],xp:780,gold:110},
 {id:'q8',chapter:'Cienie nad Doliną',name:'Ten, który uciekł',level:6,desc:'Odnajdź rannego myśliwego i eskortuj go do bezpiecznego miejsca.',steps:[{type:'discover',target:'woundedHunter',label:'Odnajdź rannego myśliwego'}],xp:850,gold:115},
 {id:'q9',chapter:'Cienie nad Doliną',name:'Ruiny',level:7,desc:'Zbadaj dziedziniec, wieżę i podziemia ruin.',steps:[{type:'dungeon',target:'oldCrypt',label:'Ukończ Starą Kryptę'}],xp:1050,gold:150},
 {id:'q10',chapter:'Cienie nad Doliną',name:'Stary znak',level:7,desc:'Pustelnik rozpoznaje symbol, ale chce wiedzieć, czy jesteś gotów zaufać jego wersji wydarzeń.',steps:[{type:'discover',target:'hermit',label:'Odnajdź pustelnika'},{type:'story',target:'q10',label:'Zdecyduj, co zrobić z wiedzą pustelnika'}],xp:900,gold:120},
 {id:'q11',chapter:'Cienie nad Doliną',name:'Pod ruinami',level:8,desc:'Wróć do ruin i znajdź więźnia.',steps:[{type:'dungeon',target:'oldCrypt',label:'Przeszukaj podziemia'}],xp:1200,gold:180},
 {id:'q12',chapter:'Cienie nad Doliną',name:'Nocny gość',level:8,desc:'Spotkanie odbywa się tylko po zmroku. W cieniu możesz zostać obserwatorem albo ruszyć za nieznajomym.',steps:[{type:'condition',target:'night',label:'Poczekaj do nocy'},{type:'discover',target:'nightGuest',label:'Dotrzyj do punktu obserwacji'},{type:'story',target:'q12',label:'Zdecyduj, jak zakończyć obserwację'}],xp:1350,gold:200},
 {id:'q13',chapter:'Cienie nad Doliną',name:'Atak na wioskę',level:9,desc:'Gobliny ruszyły na wioskę. Broń mieszkańców.',steps:[{type:'kill',target:'any',count:5,label:'Pokonaj napastników'}],xp:1600,gold:250},
 {id:'q14',chapter:'Cienie nad Doliną',name:'Czarny medalion',level:9,desc:'Zanieś tajemniczy medalion pustelnikowi.',steps:[{type:'discover',target:'hermit',label:'Zanieś Czarny medalion pustelnikowi'}],xp:1500,gold:220},
 {id:'q15',chapter:'Cienie nad Doliną',name:'Droga na północ',level:10,desc:'Pierwszy rozdział dobiega końca. Otwiera się nowy region.',steps:[{type:'move',target:350,label:'Oddal się 350 m od wioski'}],xp:2200,gold:350},
 {id:'q16',chapter:'Północne Rubieże',name:'Za granicą doliny',level:11,desc:'Droga prowadzi w chłodniejsze i znacznie bardziej niebezpieczne ziemie.',steps:[{type:'move',target:430,label:'Dotrzyj na północne rubieże'}],xp:2400,gold:380},
 {id:'q17',chapter:'Północne Rubieże',name:'Obóz bez ognia',level:11,desc:'Namioty stoją otwarte, jedzenie zamarzło na stołach, a ślady prowadzą w dwie strony.',steps:[{type:'discover',target:'northCamp',label:'Zbadaj Obóz Północny'},{type:'story',target:'q17',label:'Wybierz, czego szukać najpierw'}],xp:2550,gold:400},
 {id:'q18',chapter:'Północne Rubieże',name:'Ciężkie kroki',level:12,desc:'Ślady przy obozie są zbyt wielkie, by należały do człowieka.',steps:[{type:'kill',target:'ogre',count:2,label:'Pokonaj 2 ogry'}],xp:2800,gold:440},
 {id:'q19',chapter:'Północne Rubieże',name:'Wieża w śniegu',level:13,desc:'Stary trakt prowadzi do zapomnianej wieży zakonu.',steps:[{type:'dungeon',target:'forgottenTower',label:'Ukończ Zapomnianą Wieżę'}],xp:3300,gold:520},
 {id:'q20',chapter:'Północne Rubieże',name:'Znak mrozu',level:14,desc:'W ruinach znaleziono symbol, który odpowiada znakom ze starego sanktuarium.',steps:[{type:'discover',target:'coldShrine',label:'Odnajdź Mroźne Sanktuarium'},{type:'kill',target:'any',count:5,label:'Przetrwaj drogę przez północ'}],xp:3900,gold:650},
 {id:'q21',chapter:'Mokradła Echa',name:'Droga przez trzcinowiska',level:21,desc:'Za północnym traktem ziemia zapada się w wodę. Stary przewodnik oznaczył wejście na mokradła.',steps:[{type:'discover',target:'mireGate',label:'Odnajdź Bramę Trzcin'}],xp:4300,gold:680},
 {id:'q22',chapter:'Mokradła Echa',name:'Wioska bez głosów',level:21,desc:'Domy stoją otwarte, na stole stygnie czarna woda, a na placu nie ma ani jednego ciała.',steps:[{type:'discover',target:'drownedVillage',label:'Odkryj Zatopioną Wioskę'},{type:'story',target:'q22',label:'Zdecyduj, jak przeszukać wioskę'}],xp:4500,gold:700},
 {id:'q23',chapter:'Mokradła Echa',name:'Co porusza wodę',level:22,desc:'Pod powierzchnią coś śledzi każdy krok. Trzeba oczyścić drogę.',steps:[{type:'kill',target:'mireCrawler',count:4,label:'Pokonaj 4 Pełzacze Moczaru'}],xp:4700,gold:730},
 {id:'q24',chapter:'Mokradła Echa',name:'Dzwon spod powierzchni',level:23,desc:'Dzwon odzywa się nocą albo wtedy, gdy mgła schodzi nisko nad wodę.',steps:[{type:'condition',target:'nightOrFog',label:'Poczekaj na noc albo mgłę'},{type:'discover',target:'sunkenBell',label:'Odnajdź Zatopiony Dzwon'},{type:'story',target:'q24',label:'Zdecyduj, czy odpowiedzieć na wezwanie'}],xp:4900,gold:760},
 {id:'q25',chapter:'Mokradła Echa',name:'Zatopiona kaplica',level:23,desc:'Wejdź do kaplicy i sprawdź, kto nadal wprawia dzwon w ruch.',steps:[{type:'dungeon',target:'sunkenChapel',label:'Ukończ Zatopioną Kaplicę'}],xp:5400,gold:820},
 {id:'q26',chapter:'Mokradła Echa',name:'Szepty w trzcinach',level:24,desc:'Głosy prowadzą w głąb bagien. Nie wszystkie należą do żywych.',steps:[{type:'discover',target:'whisperMarsh',label:'Dotrzyj na Szeptane Rozlewisko'},{type:'kill',target:'bogWraith',count:2,label:'Pokonaj 2 Zjawy Topielców'}],xp:5600,gold:850},
 {id:'q27',chapter:'Mokradła Echa',name:'Totemy wiedźmy',level:25,desc:'Kościane znaki są świeże. Można je zniszczyć albo spróbować odczytać rytuał.',steps:[{type:'discover',target:'witchTotem',label:'Zbadaj Totemy Wiedźmy'},{type:'story',target:'q27',label:'Zdecyduj, co zrobić z totemami'}],xp:5800,gold:880},
 {id:'q28',chapter:'Mokradła Echa',name:'Łowcy pod sitowiem',level:25,desc:'Trzcinowi Łowcy patrolują ścieżki i nie pozwalają zbliżyć się do kopca.',steps:[{type:'kill',target:'fenStalker',count:3,label:'Pokonaj 3 Trzcinowych Łowców'}],xp:6100,gold:920},
 {id:'q29',chapter:'Mokradła Echa',name:'Czarny korzeń',level:26,desc:'W obozie kultystów znajdujesz więźnia i ślady rytuału prowadzące dalej w bagno.',steps:[{type:'discover',target:'blackrootCamp',label:'Odnajdź Obóz Czarnego Korzenia'},{type:'kill',target:'rotCultist',count:1,label:'Pokonaj strażnika obozu'},{type:'story',target:'q29',label:'Zdecyduj, co zrobić po walce'}],xp:6400,gold:960},
 {id:'q30',chapter:'Mokradła Echa',name:'Kopiec wiedźmy',level:27,desc:'Źródłem rytuałów jest kamienny kopiec pośrodku mokradeł.',steps:[{type:'dungeon',target:'witchBarrow',label:'Ukończ Kopiec Wiedźmy'}],xp:7000,gold:1050},
 {id:'q31',chapter:'Mokradła Echa',name:'Stary trakt',level:27,desc:'Za kopcem zachował się brukowany trakt prowadzący do miejsca, którego nie ma na mapach.',steps:[{type:'discover',target:'oldCauseway',label:'Odnajdź Stary Trakt'}],xp:6600,gold:980},
 {id:'q32',chapter:'Mokradła Echa',name:'Serce torfowiska',level:28,desc:'Golemy wyrywają się z ziemi w pobliżu najstarszych korzeni.',steps:[{type:'kill',target:'mossGolem',count:2,label:'Pokonaj 2 Golemy Torfowe'}],xp:7200,gold:1080},
 {id:'q33',chapter:'Mokradła Echa',name:'Ołtarz mgły',level:29,desc:'Ołtarz ujawnia prawdziwy kształt dopiero po zmroku albo w naturalnej mgle.',steps:[{type:'condition',target:'nightOrFog',label:'Poczekaj na noc albo mgłę'},{type:'discover',target:'fogAltar',label:'Odkryj Ołtarz Mgły'},{type:'story',target:'q33',label:'Wybierz sposób przełamania rytuału'}],xp:7500,gold:1120},
 {id:'q34',chapter:'Mokradła Echa',name:'Strażnik korzeni',level:29,desc:'Drogi do twierdzy broni istota z drewna, torfu i kości.',steps:[{type:'kill',target:'blackrootGuardian',count:1,label:'Pokonaj Strażnika Czarnego Korzenia'},{type:'discover',target:'blackrootGate',label:'Odnajdź Bramę Twierdzy'}],xp:7900,gold:1180},
 {id:'q35',chapter:'Mokradła Echa',name:'Matka Mgły',level:30,desc:'Po zwycięstwie nad Matką Mgły pozostaje decyzja: zniszczyć serce bagna czy je zapieczętować.',steps:[{type:'dungeon',target:'blackrootKeep',label:'Ukończ Twierdzę Czarnego Korzenia'},{type:'story',target:'q35',label:'Podejmij decyzję o losie serca bagna'}],xp:9800,gold:1500},
{id:'q36',chapter:'Popielne Pustkowia',name:'Droga w popiół',level:31,desc:'Za mokradłami ziemia robi się sucha, a wiatr niesie drobny czarny pył. Pierwszy kamień graniczny stoi przy Popielnej Bramie.',steps:[{type:'discover',target:'ashGate',label:'Odnajdź Popielną Bramę'}],xp:10400,gold:1580},
 {id:'q37',chapter:'Popielne Pustkowia',name:'Ogień pod stopami',level:32,desc:'Z pęknięć w ziemi wylatują roje rozgrzanych owadów.',steps:[{type:'kill',target:'fireWasp',count:3,label:'Pokonaj 3 Ogniste Osy'}],xp:11000,gold:1650},
 {id:'q38',chapter:'Popielne Pustkowia',name:'Kopalnia bez górników',level:33,desc:'Stary szyb wciąż świeci od środka. Nikt nie pracował tu od lat.',steps:[{type:'discover',target:'emberMineGate',label:'Odnajdź wejście do Kopalni Żaru'},{type:'dungeon',target:'emberMine',label:'Ukończ Kopalnię Żaru'}],xp:11800,gold:1740},
 {id:'q39',chapter:'Popielne Pustkowia',name:'Czarny dym',level:34,desc:'Na horyzoncie widać obóz kultystów. Dym nie rozprasza się nawet przy silnym wietrze.',steps:[{type:'discover',target:'cinderCamp',label:'Odkryj Obóz Żaru'},{type:'kill',target:'cinderCultist',count:3,label:'Pokonaj 3 Kultystów Żaru'}],xp:12400,gold:1820},
 {id:'q40',chapter:'Popielne Pustkowia',name:'Szept w popiele',level:35,desc:'Nocą popiół układa się w ślady prowadzące do starego sanktuarium.',steps:[{type:'condition',target:'nightOrFog',label:'Poczekaj na noc albo mgłę'},{type:'discover',target:'ashShrine',label:'Odnajdź Sanktuarium Popiołu'}],xp:13200,gold:1920},
 {id:'q41',chapter:'Popielne Pustkowia',name:'Żelazny deszcz',level:36,desc:'Golemy wynoszą z ziemi rozgrzane bryły metalu i zrzucają je na szlak.',steps:[{type:'kill',target:'slagGolem',count:2,label:'Pokonaj 2 Golemy Żużlowe'}],xp:14000,gold:2020},
 {id:'q42',chapter:'Popielne Pustkowia',name:'Spalony sztandar',level:37,desc:'Przy ruinach fortu wiszą sztandary dawnej straży. Ktoś wypalił na nich nowy symbol.',steps:[{type:'discover',target:'charredFort',label:'Odkryj Spalony Fort'}],xp:14700,gold:2120},
 {id:'q43',chapter:'Popielne Pustkowia',name:'Polowanie na draki',level:38,desc:'Popielne draki atakują karawany przechodzące przez pustkowia.',steps:[{type:'kill',target:'ashDrake',count:2,label:'Pokonaj 2 Popielne Draki'}],xp:15500,gold:2220},
 {id:'q44',chapter:'Popielne Pustkowia',name:'Rycerze stosu',level:39,desc:'Przed cytadelą stoją zbroje, które dawno powinny być puste.',steps:[{type:'discover',target:'ashenCitadelGate',label:'Odnajdź Bramę Popielnej Cytadeli'},{type:'kill',target:'pyreKnight',count:2,label:'Pokonaj 2 Rycerzy Stosu'}],xp:16400,gold:2340},
 {id:'q45',chapter:'Popielne Pustkowia',name:'Matka Żaru',level:40,desc:'W centrum cytadeli płonie serce pustkowi. Po walce zdecydujesz, czy zgasić je na zawsze, czy przejąć jego moc.',steps:[{type:'dungeon',target:'ashenCitadel',label:'Ukończ Popielną Cytadelę'},{type:'story',target:'q45',label:'Zdecyduj o losie Serca Żaru'}],xp:18400,gold:2700},
 {id:'q46',chapter:'Rozbite Szczyty',name:'Wysoka przełęcz',level:41,desc:'Droga wspina się ponad chmury. Pierwszy obóz kartografów leży przy Kamiennej Przełęczy.',steps:[{type:'discover',target:'peakGate',label:'Dotrzyj do Kamiennej Przełęczy'},{type:'story',target:'q46',label:'Zdecyduj, komu pomóc na przełęczy'}],xp:19000,gold:2800},
 {id:'q47',chapter:'Rozbite Szczyty',name:'Łowcy lodu',level:42,desc:'Mroźne drapieżniki polują między skałami i zepchnęły podróżnych z głównego traktu.',steps:[{type:'kill',target:'frostRaptor',count:3,label:'Pokonaj 3 Mroźne Raptory'}],xp:19800,gold:2920},
 {id:'q48',chapter:'Rozbite Szczyty',name:'Krypta ciszy',level:43,desc:'Pod lodowcem znajduje się wejście do starej krypty strażników.',steps:[{type:'discover',target:'frostVaultGate',label:'Odnajdź Kryptę Mrozu'},{type:'dungeon',target:'frostVault',label:'Ukończ Kryptę Mrozu'}],xp:20700,gold:3040},
 {id:'q49',chapter:'Rozbite Szczyty',name:'Wyznawcy burzy',level:44,desc:'Na skalnej półce kult odprawia rytuały przyciągające pioruny.',steps:[{type:'discover',target:'stormCamp',label:'Odkryj Obóz Burzy'},{type:'kill',target:'stormCultist',count:3,label:'Pokonaj 3 Kultystów Burzy'}],xp:21600,gold:3160},
 {id:'q50',chapter:'Rozbite Szczyty',name:'Zamarznięta przysięga',level:45,desc:'W lodzie tkwi posąg rycerza. Głos spod hełmu prosi o uwolnienie albo dokończenie dawnej przysięgi.',steps:[{type:'discover',target:'frozenMonument',label:'Odnajdź Zamarznięty Pomnik'},{type:'story',target:'q50',label:'Zdecyduj o losie strażnika'}],xp:22600,gold:3300},
 {id:'q51',chapter:'Rozbite Szczyty',name:'Kamienie piorunów',level:46,desc:'Żywiołaki gromadzą energię przy wysokich menhirach.',steps:[{type:'kill',target:'thunderGolem',count:2,label:'Pokonaj 2 Golemy Piorunów'}],xp:23600,gold:3440},
 {id:'q52',chapter:'Rozbite Szczyty',name:'Krawędź nieba',level:47,desc:'Kamienny most kończy się nad przepaścią, ale stare runy wskazują dalszą drogę.',steps:[{type:'discover',target:'skyBridge',label:'Odnajdź Most Niebios'}],xp:24600,gold:3580},
 {id:'q53',chapter:'Rozbite Szczyty',name:'Wąż nad chmurami',level:48,desc:'Węże Niebios przecinają szlak między mostem a iglicą.',steps:[{type:'kill',target:'skySerpent',count:2,label:'Pokonaj 2 Węże Niebios'}],xp:25700,gold:3720},
 {id:'q54',chapter:'Rozbite Szczyty',name:'Iglica w burzy',level:49,desc:'Wejście do iglicy ujawnia się najlepiej podczas złej pogody.',steps:[{type:'condition',target:'badWeather',label:'Poczekaj na mgłę, deszcz albo burzę'},{type:'discover',target:'tempestSpireGate',label:'Odnajdź Bramę Iglicy Nawałnicy'}],xp:26800,gold:3880},
 {id:'q55',chapter:'Rozbite Szczyty',name:'Władca Nawałnicy',level:50,desc:'Na szczycie iglicy czeka istota, która steruje burzami regionu. Po zwycięstwie zdecydujesz, co zrobić z Sercem Nawałnicy.',steps:[{type:'dungeon',target:'tempestSpire',label:'Ukończ Iglicę Nawałnicy'},{type:'story',target:'q55',label:'Zdecyduj o losie Serca Nawałnicy'}],xp:31000,gold:4600}
];

export const BUILDINGS = [
 {id:'tavern',name:'Karczma „Pod Krukiem”',icon:'🍺',tag:'Questy • odpoczynek'},
 {id:'shop',name:'Sklep kupiecki',icon:'🛒',tag:'Mikstury • materiały'},
 {id:'smith',name:'Kuźnia',icon:'⚒️',tag:'Ulepszanie • rozbiórka'},
 {id:'alchemist',name:'Alchemik',icon:'⚗️',tag:'Warzenie mikstur'},
 {id:'auction',name:'Dom aukcyjny',icon:'🏛️',tag:'Oferty dnia'},
 {id:'guild',name:'Sala gildii',icon:'🏰',tag:'Gildie • wyprawy'}
];
