import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const data=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(path.join(root,'data.js'))).toString('base64'));
const noop=()=>{};
const node=()=>({innerHTML:'',textContent:'',style:{setProperty:noop},classList:{add:noop,remove:noop,toggle:noop},dataset:{},addEventListener:noop,querySelector:()=>node(),querySelectorAll:()=>[],appendChild:noop,before:noop,prepend:noop,insertAdjacentHTML:noop,focus:noop,remove:noop,getAttribute:()=>null,setAttribute:noop,click:noop});
const nodes=new Map();
const storage=new Map();let callbacks=[],intervals=[];const writes=[];
const ctx=vm.createContext({...data,assert,console,Date,Math,JSON,Map,Set,Number,Object,Array,String,Infinity,URL,Blob,structuredClone,
 document:{querySelector:q=>{if(!nodes.has(q))nodes.set(q,node());return nodes.get(q)},querySelectorAll:()=>[],body:node(),addEventListener:noop,createElement:()=>node(),createTreeWalker:()=>({nextNode:()=>null}),hidden:false},
 navigator:{onLine:true,geolocation:{getCurrentPosition(fn){ctx.gpsCallback=fn},watchPosition(fn){ctx.gpsCallback=fn;return 1},clearWatch:noop}},
 window:{addEventListener:noop,matchMedia:()=>({matches:false}),navigator:{},location:{},innerWidth:390},location:{reload:noop},
 MutationObserver:class{observe(){}},NodeFilter:{SHOW_TEXT:4},performance:{now:()=>Date.now()},
 localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{storage.set(k,v);writes.push([k,v])},removeItem:k=>storage.delete(k)},
 setTimeout:(fn,delay)=>{callbacks.push({fn,delay});return callbacks.length},clearTimeout:noop,setInterval:(fn,delay)=>{intervals.push(fn);return intervals.length},clearInterval:noop,
 requestAnimationFrame:noop,cancelAnimationFrame:noop,confirm:()=>true});
let src=fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/^import[^\n]+\n/,'');
src=src.slice(0,src.lastIndexOf('state=load();restoreSession();'));
vm.runInContext(src,ctx);
const run=s=>vm.runInContext(`{${s}}`,ctx);
run(`globalThis.originalOpenCombat=openCombat;globalThis.originalRenderSocial=renderSocial;render=()=>{};renderShell=()=>{};openBuilding=()=>{};openCombat=()=>{};closeModal=()=>{};playSfx=()=>{};haptic=()=>{};setAmbient=()=>{};newGame('Tester','knight');state.tutorial.introSeen=true;state.settings.masterSound=false;state.settings.haptics=false;state.quests.active=[];`);
const base=run('JSON.stringify(state)');
let count=0;
function fresh(){run(`state=normalizeState(${base});state.quests.active=[];combat=null;dungeonRun=null;battleResult=null;saveDepth=0;SAVE_KEY=REAL_SAVE_KEY;lastAcceptedFix=null;lastGpsTick=0;gpsWatch=null;`);callbacks=[];writes.length=0;ctx.document.querySelectorAll=()=>[];}
function test(name,fn){fresh();fn();count++;console.log('PASS',name)}
test('full backpack purchase preserves gold and inventory',()=>run(`state.player.inventoryCapacity=inventoryUsedSlots();state.player.gold=100;const before=JSON.stringify(state.player);buyItem('shortSword','shop',20);assert.equal(JSON.stringify(state.player),before);`));
test('stackable purchase uses existing stack in full bag',()=>run(`state.player.inventoryCapacity=inventoryUsedSlots();state.player.gold=100;const q=countItem('potion');buyItem('potion','shop',20);assert.equal(countItem('potion'),q+1);assert.equal(state.player.gold,80);`));
test('craft rejects output when no slot will be freed',()=>run(`state.player.inventoryCapacity=inventoryUsedSlots();state.player.gold=10000;state.player.inventory.find(i=>i.id==='herb').qty=10;state.player.inventory.push({id:'crystal',qty:10});state.player.inventoryCapacity=inventoryUsedSlots();const before=JSON.stringify(state.player);craftRecipe('manaPotion');assert.equal(JSON.stringify(state.player),before);`));
test('craft accepts slot freed by consumed ingredient',()=>run(`state.player.gold=10000;state.player.inventory.find(i=>i.id==='herb').qty=1;state.player.inventory.push({id:'crystal',qty:1});state.player.inventoryCapacity=inventoryUsedSlots();craftRecipe('manaPotion');assert.equal(countItem('manaPotion'),1);assert.equal(countItem('herb'),0);assert.equal(countItem('crystal'),0);`));
test('unsocket does not charge or remove rune with full bag',()=>run(`const w=state.player.inventory.find(i=>i.uid);w.rune='runePower';state.player.gold=10000;state.player.inventoryCapacity=inventoryUsedSlots();const before=JSON.stringify(state.player);unsocketRune(w.uid);assert.equal(JSON.stringify(state.player),before);`));
test('invalid item is not added',()=>run(`const before=JSON.stringify(state.player.inventory);assert.equal(addItem(null),0);assert.equal(addItem('missing'),0);assert.equal(JSON.stringify(state.player.inventory),before);`));
test('mana potion restores actual deficit and consumes a turn',()=>run(`state.player.inventory.push({id:'manaPotion',qty:2});state.player.mana=0;startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combatPotion('manaPotion');assert.equal(state.player.mana,45);assert.equal(countItem('manaPotion'),1);assert.equal(combat.phase,'enemyDelay');`));
test('full health potion is not consumed and does not advance turn',()=>run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});const q=countItem('potion');combatPotion('potion');assert.equal(countItem('potion'),q);assert.equal(combat.phase,'player');`));
test('strong potion restores health',()=>run(`state.player.hp=10;state.player.inventory.push({id:'strongPotion',qty:1});startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combatPotion('strongPotion');assert.equal(state.player.hp,140);assert.equal(countItem('strongPotion'),0);`));
test('purchase stores only final transaction snapshot',()=>{run(`state.player.gold=100;buyItem('potion','shop',20);`);assert.equal(writes.length,1);const snap=JSON.parse(writes[0][1]);assert.equal(snap.player.gold,80);assert.equal(snap.player.inventory.find(i=>i.id==='potion').qty,4)});
test('combat snapshot retains phase and reconnects world entity',()=>run(`const e=state.world.entities.find(e=>e.type==='monster');startCombat(e);combat.hp=20;queueEnemyTurn();state=JSON.parse(localStorage.getItem(SAVE_KEY));combat=null;restoreSession();assert.equal(combat.hp,20);assert.equal(combat.phase,'enemyDelay');assert.equal(combat.entity,state.world.entities.find(e=>e.id===combat.entity.id));`));
test('resume after enemy result does not apply another hit',()=>{run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.phase='enemyResult';state.player.hp=80;save();state=JSON.parse(localStorage.getItem(SAVE_KEY));restoreSession();resumeSession();`);const cb=callbacks.filter(c=>c.delay===350).at(-1);assert.ok(cb);cb.fn();run(`assert.equal(state.player.hp,80);assert.equal(combat.phase,'player');`)});
test('dungeon grid and deadline survive reload',()=>run(`const d=DUNGEONS[0];state.player.level=d.min;const a=dungeonAccess(d.id);a.guardianDefeated=true;state.player.dungeons.push(d.id);openDungeonCrawler=()=>{};startDungeon(d);const grid=JSON.stringify(dungeonRun.grid),deadline=dungeonRun.deadline;state=JSON.parse(localStorage.getItem(SAVE_KEY));dungeonRun=null;restoreSession();assert.equal(JSON.stringify(dungeonRun.grid),grid);assert.equal(dungeonRun.deadline,deadline);assert.equal(dungeonAccess(d.id).attempts,1);`));
test('reward screen survives reload without awarding XP twice',()=>run(`showBattleVictory=()=>{};startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});winCombat();const xp=state.player.xp,gold=state.player.gold;assert.ok(battleResult);state=JSON.parse(localStorage.getItem(SAVE_KEY));restoreSession();resumeSession();assert.equal(state.player.xp,xp);assert.equal(state.player.gold,gold);assert.ok(battleResult);assert.equal(combat,null);`));
test('GPS rejects poor accuracy before moving player',()=>{run(`currentTab='hero';toggleGps();`);const before=run('JSON.stringify(state.player.position)');ctx.gpsCallback({coords:{latitude:51,longitude:22,accuracy:150},timestamp:Date.now()});assert.equal(run('JSON.stringify(state.player.position)'),before)});
test('GPS rejects stale fix before moving player',()=>{run(`currentTab='hero';toggleGps();`);const before=run('JSON.stringify(state.player.position)');ctx.gpsCallback({coords:{latitude:51,longitude:22,accuracy:10},timestamp:Date.now()-60000});assert.equal(run('JSON.stringify(state.player.position)'),before)});
test('GPS accepts current accurate fix and rejects sudden teleport',()=>{run(`currentTab='hero';toggleGps();`);ctx.gpsCallback({coords:{latitude:51,longitude:22,accuracy:10},timestamp:Date.now()});run(`assert.equal(state.player.position.lat,51);assert.equal(gpsInteractionReady(),true);lastGpsTick=0;`);ctx.gpsCallback({coords:{latitude:52,longitude:23,accuracy:10},timestamp:Date.now()});run(`assert.equal(state.player.position.lat,51);`)});
test('old position cannot authorize GPS interaction',()=>run(`state.player.position={gps:true,accuracy:5,receivedAt:Date.now()-60000};gpsWatch=1;assert.equal(gpsInteractionReady(),false);`));
test('demo movement is blocked in primary save',()=>run(`const pos=JSON.stringify(state.player.position);moveDemo(20,0);assert.equal(JSON.stringify(state.player.position),pos);`));
test('separate sandbox snapshot cannot overwrite primary',()=>{run(`state.player.gold=123;save();switchPlayMode();`);const real=JSON.parse(storage.get('time4heroes_build_390')),demo=JSON.parse(storage.get('time4heroes_build_390_sandbox'));assert.equal(real.playMode,'gps');assert.equal(demo.playMode,'sandbox');assert.equal(real.player.gold,demo.player.gold);run(`SAVE_KEY=DEMO_SAVE_KEY;state=JSON.parse(localStorage.getItem(DEMO_SAVE_KEY));state.player.gold=999;save();`);assert.equal(JSON.parse(storage.get('time4heroes_build_390')).player.gold,123)});
test('combat UI contains all potion buttons and visible costs',()=>run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});originalOpenCombat();assert.ok(app.innerHTML.includes('data-combat-potion="manaPotion"'));assert.ok(app.innerHTML.includes('data-combat-potion="strongPotion"'));assert.ok(app.innerHTML.includes('Dziennik walki'));`));
test('all item definitions have a vector asset',()=>{for(const id of Object.keys(data.ITEMS))assert.ok(fs.existsSync(path.join(root,'assets/icons/items',id+'.svg')),id)});

test('selected loot with no space stays pending',()=>{ctx.document.querySelectorAll=()=>[{dataset:{battleLoot:'0'}}];run(`state.player.inventoryCapacity=inventoryUsedSlots();battleResult={xp:5,gold:2,drops:[{id:'shortSword',qty:1}]};const before=JSON.stringify(state.player);finishBattleResult(battleResult,true);assert.ok(battleResult);assert.equal(JSON.stringify(state.player),before);`)});
test('loot can be collected only once',()=>{ctx.document.querySelectorAll=()=>[{dataset:{battleLoot:'0'}}];run(`battleResult={xp:5,gold:2,drops:[{id:'potion',qty:2}]};const result=battleResult,q=countItem('potion');finishBattleResult(result,true);finishBattleResult(result,true);assert.equal(countItem('potion'),q+2);assert.equal(battleResult,null);`)});
test('cannot unequip into full backpack',()=>run(`state.player.inventoryCapacity=inventoryUsedSlots();const w=equippedInstance('weapon');assert.equal(unequipItem(w.uid),false);assert.equal(equippedInstance('weapon').uid,w.uid);`));
test('cannot sell equipped item',()=>run(`const i=state.player.inventory.findIndex(x=>x.uid===state.player.equipped.weapon.uid),before=JSON.stringify(state.player);sellIndex(i);assert.equal(JSON.stringify(state.player),before);`));
test('salvage preserves gear when outputs do not fit',()=>run(`state.player.inventory=state.player.inventory.filter(i=>i.id!=='scrap');const i=createGearInstance('stormCrown');state.player.inventory.push(i);state.player.inventoryCapacity=inventoryUsedSlots();const before=JSON.stringify(state.player);salvageIndex(state.player.inventory.length-1);assert.equal(JSON.stringify(state.player),before);`));
test('legacy 3.8 save keeps gold, gear and quest history',()=>run(`const old=JSON.parse(JSON.stringify(state));old.version=380;old.player.gold=777;old.quests.done=['q1','q2'];old.settings.demo=true;const migrated=normalizeState(old);assert.equal(migrated.version,391);assert.equal(migrated.player.gold,777);assert.equal(migrated.quests.done.join(','),'q1,q2');assert.equal(migrated.settings.demo,false);assert.ok(migrated.player.equipped.weapon.uid);`));
test('damaged session is rejected by import validation',()=>run(`assert.throws(()=>validateSessionSave({session:{combat:{}}}));assert.throws(()=>validateSessionSave({session:{dungeonRun:{id:DUNGEONS[0].id,size:8,grid:[]}}}));`));
test('save storage error is reported without crashing',()=>{const set=ctx.localStorage.setItem;ctx.localStorage.setItem=()=>{throw new Error('quota')};run(`assert.doesNotThrow(()=>save());assert.equal(save.failed,true);`);ctx.localStorage.setItem=set});
test('old delayed callback cannot attack in a new fight',()=>{run(`startCombat({id:'old',template:'slime',type:'monster',synthetic:true,variant:'normal'});queueEnemyTurn(1100);`);const cb=callbacks.find(x=>x.delay===1100);run(`combat=null;startCombat({id:'new',template:'rat',type:'monster',synthetic:true,variant:'normal'});queueEnemyTurn(1100);`);cb.fn();run(`assert.equal(combat.phase,'enemyDelay');assert.equal(combat.enemyTurns,0);`)});
test('resumed pending enemy turn runs exactly once',()=>{run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal'});queueEnemyTurn();state=JSON.parse(localStorage.getItem(SAVE_KEY));restoreSession();resumeSession();`);const cb=callbacks.filter(x=>x.delay===350).at(-1);assert.ok(cb);cb.fn();const hp=run('state.player.hp');cb.fn();assert.equal(run('state.player.hp'),hp);run(`assert.equal(combat.phase,'enemyResult');`)});

test('all monsters have a valid map size and insects are smaller than wolves and demons',()=>run(`for(const m of MONSTERS){const size=monsterMapSize(m);assert.ok(size.width>=38&&size.height>=38&&size.width<=100&&size.height<=100)}assert.ok(monsterMapSize(MONSTERS.find(m=>m.id==='beetle')).height<monsterMapSize(MONSTERS.find(m=>m.id==='wolf')).height);assert.ok(monsterMapSize(MONSTERS.find(m=>m.id==='wolf')).height<monsterMapSize(MONSTERS.find(m=>m.id==='demon')).height);`));
test('map creature markup uses a free sprite and natural shadow',()=>run(`const html=mapMonsterHTML({id:'wolf-test',template:'wolf',variant:'normal'},20,false);assert.ok(html.includes('world-creature'));assert.ok(html.includes('creature-shadow'));assert.ok(!html.includes('ready-pip'));assert.ok(!html.includes('variant-map-badge'));`));
test('four movement quadrants select distinct directions',()=>run(`assert.equal(playerFacing(0),'up');assert.equal(playerFacing(90),'right');assert.equal(playerFacing(180),'down');assert.equal(playerFacing(270),'left');assert.equal(playerFacing(359),'up');`));
test('coordinate motion overrides inconsistent GPS heading',()=>run(`assert.equal(Math.round(movementBearing({lat:51,lng:22},{lat:51,lng:22.001,heading:0})),90);assert.equal(Math.round(movementBearing({lat:51,lng:22},{lat:50.999,lng:22,heading:0})),180);`));
test('facing updates even without a live Leaflet map',()=>run(`registerPlayerMovement({lat:51,lng:22},{lat:51,lng:22.001,testWalk:true});assert.equal(playerFacing(playerMotion.heading),'right');assert.equal(state.ui.mapHeading,90);assert.ok(playerMotion.moving);`));
test('standing still keeps the last facing despite sensor changes',()=>run(`playerMotion.heading=270;registerPlayerMovement({lat:51,lng:22},{lat:51,lng:22,heading:90,accuracy:5});assert.equal(playerMotion.heading,270);`));
test('all classes use the directional atlas on the map',()=>run(`for(const id of Object.keys(CLASSES)){state.player.class=id;const html=playerMarkerHTML();assert.ok(html.includes('directional-hero hero-'+id));assert.ok(!html.includes('mmo-player-sprite'))}`));
test('marker can be anchored at its feet',()=>{ctx.L={divIcon:options=>options};run(`const icon=makeLeafletIcon('test','player-leaflet-icon',[64,80],[32,74]);assert.equal(icon.iconAnchor.join(','),'32,74');assert.equal(makeLeafletIcon('test').iconAnchor.join(','),'24,24');`)});
test('drawer includes gear, bag grid, three tabs and character resources',()=>run(`const html=gearDrawerHTML();assert.ok(html.includes('drawer-equipment'));assert.ok(html.includes('drawer-bag-grid'));assert.ok(html.includes('data-drawer-tab="quests"'));assert.ok(html.includes('data-drawer-tab="stats"'));assert.ok(html.includes('data-drawer-tab="bag"'));assert.ok(html.includes('Mana'));`));
test('drawer filters consumables and materials without losing inventory',()=>run(`const before=JSON.stringify(state.player.inventory);const usable=drawerInventoryEntries('usable');assert.ok(usable.some(e=>e.item.id==='potion'));assert.ok(usable.every(e=>['consumable','ammo'].includes(itemDef(e.item.id).type)));assert.ok(drawerInventoryEntries('materials').some(e=>e.item.id==='herb'));assert.equal(JSON.stringify(state.player.inventory),before);`));
test('drawer toggle updates accessibility and open state',()=>run(`toggleGearDrawer(true);assert.equal(state.ui.gearDrawerOpen,true);assert.ok(gearDrawerHTML().includes('aria-expanded="true"'));toggleGearDrawer(false);assert.equal(state.ui.gearDrawerOpen,false);assert.ok(gearDrawerHTML().includes('inert aria-hidden="true"'));`));
test('potion can be used from the drawer without leaving the map',()=>run(`state.ui.gearDrawerOpen=true;state.player.hp=50;state.ui.gearDrawerSelection=state.player.inventory.findIndex(i=>i.id==='potion');const before=countItem('potion');handleGearDrawerClick({target:{closest:()=>({dataset:{use:'potion'}})}});assert.equal(countItem('potion'),before-1);assert.equal(state.player.hp,105);assert.equal(state.ui.gearDrawerOpen,true);assert.equal(state.ui.gearDrawerSelection,null);`));
console.log(`${count} regression checks passed.`);
