import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const data=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(path.join(root,'data.js'))).toString('base64'));
const noop=()=>{};
const node=()=>({innerHTML:'',textContent:'',style:{setProperty:noop},classList:{add:noop,remove:noop,toggle:noop},dataset:{},addEventListener:noop,querySelector:()=>node(),querySelectorAll:()=>[],appendChild:noop,before:noop,prepend:noop,insertAdjacentHTML:noop,focus:noop,remove:noop,getAttribute:()=>null,setAttribute:noop,click:noop});
const nodes=new Map();
const storage=new Map();let callbacks=[],intervals=[];const writes=[];
const ctx=vm.createContext({...data,assert,console,Date,Math,JSON,Map,Set,Number,Object,Array,String,Infinity,URL,Blob,structuredClone,
 document:{querySelector:q=>{if(!nodes.has(q))nodes.set(q,node());return nodes.get(q)},querySelectorAll:()=>[],body:node(),addEventListener:noop,createElement:()=>node(),createTreeWalker:()=>({nextNode:()=>null}),hidden:false},
 navigator:{onLine:true,geolocation:{getCurrentPosition(fn){ctx.gpsCallback=fn},watchPosition(fn){ctx.gpsCallback=fn;return 1},clearWatch:noop}},
 window:{addEventListener:noop,matchMedia:()=>({matches:false}),navigator:{},location:{},innerWidth:390},location:{reload:noop},
 MutationObserver:class{observe(){}},NodeFilter:{SHOW_TEXT:4},performance:{now:()=>Date.now()},
 localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{storage.set(k,v);writes.push([k,v])},removeItem:k=>storage.delete(k)},
 setTimeout:(fn,delay)=>{callbacks.push({fn,delay});return callbacks.length},clearTimeout:noop,setInterval:(fn,delay)=>{intervals.push(fn);return intervals.length},clearInterval:noop,
 requestAnimationFrame:noop,cancelAnimationFrame:noop,confirm:()=>true});
let src=fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/^import[^\n]+\n/,'');
src=src.slice(0,src.lastIndexOf('state=load();restoreSession();'));
vm.runInContext(src,ctx);
const run=s=>vm.runInContext(`{${s}}`,ctx);
run(`globalThis.originalOpenCombat=openCombat;globalThis.originalOpenBuilding=openBuilding;globalThis.originalRenderSocial=renderSocial;render=()=>{};renderShell=()=>{};openBuilding=()=>{};openCombat=()=>{};closeModal=()=>{};playSfx=()=>{};haptic=()=>{};setAmbient=()=>{};newGame('Tester','knight');state.tutorial.introSeen=true;state.settings.masterSound=false;state.settings.haptics=false;state.quests.active=[];`);
const base=run('JSON.stringify(state)');
let count=0;
function fresh(){run(`state=normalizeState(${base});state.quests.active=[];combat=null;dungeonRun=null;battleResult=null;saveDepth=0;SAVE_KEY=REAL_SAVE_KEY;lastAcceptedFix=null;lastGpsTick=0;gpsWatch=null;`);callbacks=[];writes.length=0;ctx.document.querySelectorAll=()=>[];}
function test(name,fn){fresh();fn();count++;console.log('PASS',name)}
test('illustrated city map routes its buildings to their interiors',()=>{
 assert.ok(fs.existsSync(path.join(root,'assets/backgrounds/city-map-3995.webp')));
 const el=node(),tavern={dataset:{building:'tavern'}};
 el.querySelectorAll=selector=>selector==='[data-building]:not(:disabled)'?[tavern]:[];
 run('globalThis.lastCityOpen=null;openBuilding=(id,view)=>{globalThis.lastCityOpen=[id,view]};');
 ctx.renderTown(el);
 assert.equal((el.innerHTML.match(/class="city-map-hotspot /g)||[]).length,6);
 for(const id of ['tavern','shop','smith','alchemist','auction','guild'])assert.ok(el.innerHTML.includes(`data-building="${id}"`),id);
 assert.ok(el.innerHTML.includes('city-map-3995.webp'));
 tavern.onclick();
 assert.equal(JSON.stringify(ctx.lastCityOpen),JSON.stringify(['tavern','scene']));
});
test('full backpack purchase preserves gold and inventory',()=>run(`state.player.inventoryCapacity=inventoryUsedSlots();state.player.gold=100;const before=JSON.stringify(state.player);buyItem('shortSword','shop',20);assert.equal(JSON.stringify(state.player),before);`));
test('stackable purchase uses existing stack in full bag',()=>run(`state.player.inventoryCapacity=inventoryUsedSlots();state.player.gold=100;const q=countItem('potion');buyItem('potion','shop',20);assert.equal(countItem('potion'),q+1);assert.equal(state.player.gold,80);`));
test('craft rejects output when no slot will be freed',()=>run(`ensureAlchemyState();state.alchemy.recipeUses.manaPotion=2;state.player.inventoryCapacity=inventoryUsedSlots();state.player.gold=10000;state.player.inventory.find(i=>i.id==='herb').qty=10;state.player.inventory.push({id:'crystal',qty:10});state.player.inventoryCapacity=inventoryUsedSlots();const before=JSON.stringify(state.player);craftRecipe('manaPotion');assert.equal(JSON.stringify(state.player),before);`));
test('craft accepts slot freed by consumed ingredient',()=>run(`ensureAlchemyState();state.alchemy.recipeUses.manaPotion=2;state.player.gold=10000;state.player.inventory.find(i=>i.id==='herb').qty=1;state.player.inventory.push({id:'crystal',qty:1});state.player.inventoryCapacity=inventoryUsedSlots();craftRecipe('manaPotion');assert.equal(countItem('manaPotion'),1);assert.equal(countItem('herb'),0);assert.equal(countItem('crystal'),0);assert.equal(state.alchemy.recipeUses.manaPotion,1);`));
test('unsocket does not charge or remove rune with full bag',()=>run(`const w=state.player.inventory.find(i=>i.uid);w.rune='runePower';state.player.gold=10000;state.player.inventoryCapacity=inventoryUsedSlots();const before=JSON.stringify(state.player);unsocketRune(w.uid);assert.equal(JSON.stringify(state.player),before);`));
test('invalid item is not added',()=>run(`const before=JSON.stringify(state.player.inventory);assert.equal(addItem(null),0);assert.equal(addItem('missing'),0);assert.equal(JSON.stringify(state.player.inventory),before);`));
test('mana potion restores actual deficit and consumes a turn',()=>run(`state.player.inventory.push({id:'manaPotion',qty:2});state.player.mana=0;startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combatPotion('manaPotion');assert.equal(state.player.mana,45);assert.equal(countItem('manaPotion'),1);assert.equal(combat.phase,'enemyDelay');`));
test('full health potion is not consumed and does not advance turn',()=>run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});const q=countItem('potion');combatPotion('potion');assert.equal(countItem('potion'),q);assert.equal(combat.phase,'player');`));
test('strong potion restores health',()=>run(`state.player.hp=10;state.player.inventory.push({id:'strongPotion',qty:1});startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combatPotion('strongPotion');assert.equal(state.player.hp,140);assert.equal(countItem('strongPotion'),0);`));
test('purchase stores only final transaction snapshot',()=>{run(`state.player.gold=100;buyItem('potion','shop',20);`);const mainWrites=writes.filter(([k])=>k==='time4heroes_build_390');assert.equal(mainWrites.length,1);const snap=JSON.parse(mainWrites[0][1]);assert.equal(snap.player.gold,80);assert.equal(snap.player.inventory.find(i=>i.id==='potion').qty,4)});
test('combat snapshot retains phase and reconnects world entity',()=>run(`const e=state.world.entities.find(e=>e.type==='monster');startCombat(e);combat.hp=20;queueEnemyTurn();state=JSON.parse(localStorage.getItem(SAVE_KEY));combat=null;restoreSession();assert.equal(combat.hp,20);assert.equal(combat.phase,'enemyDelay');assert.equal(combat.entity,state.world.entities.find(e=>e.id===combat.entity.id));`));
test('resume after enemy result does not apply another hit',()=>{run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.phase='enemyResult';state.player.hp=80;save();state=JSON.parse(localStorage.getItem(SAVE_KEY));restoreSession();resumeSession();`);const cb=callbacks.filter(c=>c.delay===350).at(-1);assert.ok(cb);cb.fn();run(`assert.equal(state.player.hp,80);assert.equal(combat.phase,'player');`)});
test('dungeon grid and deadline survive reload',()=>run(`const d=DUNGEONS[0];state.player.level=d.min;const a=dungeonAccess(d.id);a.guardianDefeated=true;state.player.dungeons.push(d.id);openDungeonCrawler=()=>{};startDungeon(d);const grid=JSON.stringify(dungeonRun.grid),deadline=dungeonRun.deadline;state=JSON.parse(localStorage.getItem(SAVE_KEY));dungeonRun=null;restoreSession();assert.equal(JSON.stringify(dungeonRun.grid),grid);assert.equal(dungeonRun.deadline,deadline);assert.equal(dungeonAccess(d.id).attempts,1);`));
test('reward screen survives reload without awarding XP twice',()=>run(`showBattleVictory=()=>{};startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});winCombat();const xp=state.player.xp,gold=state.player.gold;assert.ok(battleResult);state=JSON.parse(localStorage.getItem(SAVE_KEY));restoreSession();resumeSession();assert.equal(state.player.xp,xp);assert.equal(state.player.gold,gold);assert.ok(battleResult);assert.equal(combat,null);`));
test('GPS rejects poor accuracy before moving player',()=>{run(`currentTab='hero';toggleGps();`);const before=run('JSON.stringify(state.player.position)');ctx.gpsCallback({coords:{latitude:51,longitude:22,accuracy:150},timestamp:Date.now()});assert.equal(run('JSON.stringify(state.player.position)'),before)});
test('GPS rejects stale fix before moving player',()=>{run(`currentTab='hero';toggleGps();`);const before=run('JSON.stringify(state.player.position)');ctx.gpsCallback({coords:{latitude:51,longitude:22,accuracy:10},timestamp:Date.now()-60000});assert.equal(run('JSON.stringify(state.player.position)'),before)});
test('GPS accepts current accurate fix and rejects sudden teleport',()=>{run(`currentTab='hero';toggleGps();`);ctx.gpsCallback({coords:{latitude:51,longitude:22,accuracy:10},timestamp:Date.now()});run(`assert.equal(state.player.position.lat,51);assert.equal(gpsInteractionReady(),true);lastGpsTick=0;`);ctx.gpsCallback({coords:{latitude:52,longitude:23,accuracy:10},timestamp:Date.now()});run(`assert.equal(state.player.position.lat,51);`)});
test('old position cannot authorize GPS interaction',()=>run(`state.player.position={gps:true,accuracy:5,receivedAt:Date.now()-60000};gpsWatch=1;assert.equal(gpsInteractionReady(),false);`));
test('demo movement is blocked in primary save',()=>run(`const pos=JSON.stringify(state.player.position);moveDemo(20,0);assert.equal(JSON.stringify(state.player.position),pos);`));
test('separate sandbox snapshot cannot overwrite primary',()=>{run(`state.player.gold=123;save();switchPlayMode();`);const real=JSON.parse(storage.get('time4heroes_build_390')),demo=JSON.parse(storage.get('time4heroes_build_390_sandbox'));assert.equal(real.playMode,'gps');assert.equal(demo.playMode,'sandbox');assert.equal(real.player.gold,demo.player.gold);run(`SAVE_KEY=DEMO_SAVE_KEY;state=JSON.parse(localStorage.getItem(DEMO_SAVE_KEY));state.player.gold=999;save();`);assert.equal(JSON.parse(storage.get('time4heroes_build_390')).player.gold,123)});
test('combat UI groups potions under Healing command',()=>run(`state.player.inventory.push({id:'manaPotion',qty:1},{id:'strongPotion',qty:1});startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});originalOpenCombat();assert.ok(app.innerHTML.includes('data-command="heal"'));assert.ok(!app.innerHTML.includes('data-combat-potion="manaPotion"'));combat.menu='heal';originalOpenCombat();assert.ok(app.innerHTML.includes('data-combat-potion="manaPotion"'));assert.ok(app.innerHTML.includes('data-combat-potion="strongPotion"'));assert.ok(app.innerHTML.includes('Dziennik walki'));`));
test('combat loadout keeps at most four learned skills',()=>run(`state.player.skills=SKILLS.knight.slice(0,6).map(s=>s.id);delete state.player.activeSkills;ensureCombatSkillLoadout();assert.equal(state.player.activeSkills.length,4);const fifth=state.player.skills[4];toggleCombatSkill(fifth);assert.ok(!state.player.activeSkills.includes(fifth));toggleCombatSkill(state.player.activeSkills[0]);toggleCombatSkill(fifth);assert.ok(state.player.activeSkills.includes(fifth));assert.equal(state.player.activeSkills.length,4);`));
test('combat fight submenu renders only selected active skills',()=>run(`state.player.skills=SKILLS.knight.slice(0,6).map(s=>s.id);state.player.activeSkills=state.player.skills.slice(1,5);startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.menu='fight';originalOpenCombat();for(const id of state.player.activeSkills)assert.ok(app.innerHTML.includes('data-skill="'+id+'"'));assert.ok(!app.innerHTML.includes('data-skill="'+state.player.skills[0]+'"'));assert.ok(!app.innerHTML.includes('data-skill="'+state.player.skills[5]+'"'));`));
test('all item definitions have individual art',()=>{for(const id of vm.runInContext('Object.keys(ITEMS)',ctx))assert.ok(fs.existsSync(path.join(root,'assets/item-art',id+'.webp')),id)});
test('class gear provides four tiers for every class',()=>{for(const cls of Object.keys(data.CLASSES)){const gear=Object.values(data.ITEMS).filter(d=>d.classGear&&d.classes?.includes(cls));for(const lvl of [12,28,45,70])assert.ok(gear.some(d=>d.reqLevel===lvl),cls+' lvl '+lvl)}});
test('mage hunter and ranger can equip their generated offhands',()=>run(`for(const cls of ['mage','hunter','ranger']){state.player.class=cls;const d=Object.values(ITEMS).find(x=>x.classGear&&x.classes?.includes(cls)&&x.slot==='offhand'&&x.reqLevel===12);assert.ok(d);state.player.level=20;const inst=createGearInstance(d.id);state.player.inventory.push(inst);assert.equal(itemCanGoToSlot(inst,'offhand'),true)}`));
test('generated class gear perks are visible to combat perk system',()=>run(`state.player.class='ranger';state.player.level=20;const d=Object.values(ITEMS).find(x=>x.classGear&&x.classes?.includes('ranger')&&x.slot==='helmet'&&x.reqLevel===12);const inst=createGearInstance(d.id);state.player.inventory.push(inst);state.player.equipped.helmet=inst;assert.ok(itemCombatPerk(d.id));assert.ok(equippedCombatPerks().poisonAmp>0);`));


test('selected loot with no space stays pending',()=>{ctx.document.querySelectorAll=()=>[{dataset:{battleLoot:'0'}}];run(`state.player.inventoryCapacity=inventoryUsedSlots();battleResult={xp:5,gold:2,drops:[{id:'shortSword',qty:1}]};const before=JSON.stringify(state.player);finishBattleResult(battleResult,true);assert.ok(battleResult);assert.equal(JSON.stringify(state.player),before);`)});
test('loot can be collected only once',()=>{ctx.document.querySelectorAll=()=>[{dataset:{battleLoot:'0'}}];run(`battleResult={xp:5,gold:2,drops:[{id:'potion',qty:2}]};const result=battleResult,q=countItem('potion');finishBattleResult(result,true);finishBattleResult(result,true);assert.equal(countItem('potion'),q+2);assert.equal(battleResult,null);`)});
test('cannot unequip into full backpack',()=>run(`state.player.inventoryCapacity=inventoryUsedSlots();const w=equippedInstance('weapon');assert.equal(unequipItem(w.uid),false);assert.equal(equippedInstance('weapon').uid,w.uid);`));
test('cannot sell equipped item',()=>run(`const i=state.player.inventory.findIndex(x=>x.uid===state.player.equipped.weapon.uid),before=JSON.stringify(state.player);sellIndex(i);assert.equal(JSON.stringify(state.player),before);`));
test('salvage preserves gear when outputs do not fit',()=>run(`state.player.inventory=state.player.inventory.filter(i=>i.id!=='scrap');const i=createGearInstance('stormCrown');state.player.inventory.push(i);state.player.inventoryCapacity=inventoryUsedSlots();const before=JSON.stringify(state.player);salvageIndex(state.player.inventory.length-1);assert.equal(JSON.stringify(state.player),before);`));
test('legacy 3.8 save keeps gold, gear and quest history',()=>run(`const old=JSON.parse(JSON.stringify(state));old.version=380;old.player.gold=777;old.quests.done=['q1','q2'];old.settings.demo=true;const migrated=normalizeState(old);assert.equal(migrated.version,394);assert.equal(migrated.player.gold,777);assert.equal(migrated.quests.done.join(','),'q1,q2');assert.equal(migrated.settings.demo,false);assert.ok(migrated.player.equipped.weapon.uid);`));
test('damaged session is rejected by import validation',()=>run(`assert.throws(()=>validateSessionSave({session:{combat:{}}}));assert.throws(()=>validateSessionSave({session:{dungeonRun:{id:DUNGEONS[0].id,size:8,grid:[]}}}));`));
test('save storage error is reported without crashing',()=>{const set=ctx.localStorage.setItem;ctx.localStorage.setItem=()=>{throw new Error('quota')};run(`assert.doesNotThrow(()=>save());assert.equal(save.failed,true);`);ctx.localStorage.setItem=set});
test('old delayed callback cannot attack in a new fight',()=>{run(`startCombat({id:'old',template:'slime',type:'monster',synthetic:true,variant:'normal'});queueEnemyTurn(1100);`);const cb=callbacks.find(x=>x.delay===1100);run(`combat=null;startCombat({id:'new',template:'rat',type:'monster',synthetic:true,variant:'normal'});queueEnemyTurn(1100);`);cb.fn();run(`assert.equal(combat.phase,'enemyDelay');assert.equal(combat.enemyTurns,0);`)});
test('resumed pending enemy turn runs exactly once',()=>{run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal'});queueEnemyTurn();state=JSON.parse(localStorage.getItem(SAVE_KEY));restoreSession();resumeSession();`);const cb=callbacks.filter(x=>x.delay===350).at(-1);assert.ok(cb);cb.fn();const hp=run('state.player.hp');cb.fn();assert.equal(run('state.player.hp'),hp);run(`assert.equal(combat.phase,'enemyResult');`)});

test('all monsters have a valid map size and insects are smaller than wolves and demons',()=>run(`for(const m of MONSTERS){const size=monsterMapSize(m);assert.ok(size.width>=38&&size.height>=38&&size.width<=100&&size.height<=100)}assert.ok(monsterMapSize(MONSTERS.find(m=>m.id==='beetle')).height<monsterMapSize(MONSTERS.find(m=>m.id==='wolf')).height);assert.ok(monsterMapSize(MONSTERS.find(m=>m.id==='wolf')).height<monsterMapSize(MONSTERS.find(m=>m.id==='demon')).height);`));
test('map creature markup uses a free sprite and natural shadow',()=>run(`const html=mapMonsterHTML({id:'wolf-test',template:'wolf',variant:'normal'},20,false);assert.ok(html.includes('world-creature'));assert.ok(html.includes('creature-shadow'));assert.ok(!html.includes('ready-pip'));assert.ok(!html.includes('variant-map-badge'));`));
test('four movement quadrants select distinct directions',()=>run(`assert.equal(playerFacing(0),'up');assert.equal(playerFacing(90),'right');assert.equal(playerFacing(180),'down');assert.equal(playerFacing(270),'left');assert.equal(playerFacing(359),'up');`));
test('coordinate motion overrides inconsistent GPS heading',()=>run(`assert.equal(Math.round(movementBearing({lat:51,lng:22},{lat:51,lng:22.001,heading:0})),90);assert.equal(Math.round(movementBearing({lat:51,lng:22},{lat:50.999,lng:22,heading:0})),180);`));
test('facing updates even without a live Leaflet map',()=>run(`registerPlayerMovement({lat:51,lng:22},{lat:51,lng:22.001,testWalk:true});assert.equal(playerFacing(playerMotion.heading),'right');assert.equal(state.ui.mapHeading,90);assert.ok(playerMotion.moving);`));
test('standing still keeps the last facing despite sensor changes',()=>run(`playerMotion.heading=270;registerPlayerMovement({lat:51,lng:22},{lat:51,lng:22,heading:90,accuracy:5});assert.equal(playerMotion.heading,270);`));
test('all classes use the directional atlas on the map',()=>run(`for(const id of Object.keys(CLASSES)){state.player.class=id;const html=playerMarkerHTML();assert.ok(html.includes('directional-hero hero-'+id));assert.ok(!html.includes('mmo-player-sprite'))}`));
test('marker can be anchored at its feet',()=>{ctx.L={divIcon:options=>options};run(`const icon=makeLeafletIcon('test','player-leaflet-icon',[64,80],[32,74]);assert.equal(icon.iconAnchor.join(','),'32,74');assert.equal(makeLeafletIcon('test').iconAnchor.join(','),'24,24');`)});
test('drawer includes gear, bag grid, three tabs and character resources',()=>run(`const html=gearDrawerHTML();assert.ok(html.includes('drawer-equipment'));assert.ok(html.includes('drawer-bag-grid'));assert.ok(html.includes('data-drawer-tab="quests"'));assert.ok(html.includes('data-drawer-tab="stats"'));assert.ok(html.includes('data-drawer-tab="bag"'));assert.ok(html.includes('Mana'));`));
test('drawer filters consumables and materials without losing inventory',()=>run(`const before=JSON.stringify(state.player.inventory);const usable=drawerInventoryEntries('usable');assert.ok(usable.some(e=>e.item.id==='potion'));assert.ok(usable.every(e=>['consumable','ammo'].includes(itemDef(e.item.id).type)));assert.ok(drawerInventoryEntries('materials').some(e=>e.item.id==='herb'));assert.equal(JSON.stringify(state.player.inventory),before);`));
test('drawer toggle updates accessibility and open state',()=>run(`toggleGearDrawer(true);assert.equal(state.ui.gearDrawerOpen,true);assert.ok(gearDrawerHTML().includes('aria-expanded="true"'));toggleGearDrawer(false);assert.equal(state.ui.gearDrawerOpen,false);assert.ok(gearDrawerHTML().includes('inert aria-hidden="true"'));`));
test('potion can be used from the drawer without leaving the map',()=>run(`state.ui.gearDrawerOpen=true;state.player.hp=50;state.ui.gearDrawerSelection=state.player.inventory.findIndex(i=>i.id==='potion');const before=countItem('potion');handleGearDrawerClick({target:{closest:()=>({dataset:{use:'potion'}})}});assert.equal(countItem('potion'),before-1);assert.equal(state.player.hp,100);assert.equal(state.ui.gearDrawerOpen,true);assert.equal(state.ui.gearDrawerSelection,null);`));
test('backpack item can be moved into an empty slot and position persists',()=>run(`const first=backpackEntries()[0],item=first.item;assert.ok(moveBackpackItemToSlot(first.index,10));assert.equal(item.bagSlot,10);assert.equal(backpackEntries().find(e=>e.item===item).slot,10);`));
test('dropping onto an occupied backpack slot swaps the two items',()=>run(`const bag=backpackEntries(),a=bag[0],b=bag[1],as=a.slot,bs=b.slot;assert.ok(moveBackpackItemToSlot(a.index,bs));assert.equal(a.item.bagSlot,bs);assert.equal(b.item.bagSlot,as);`));
test('backpack sorting rearranges slots without deleting items',()=>run(`const before=state.player.inventory.length;assert.ok(sortBackpack('name'));const names=backpackEntries().map(e=>itemDef(e.item.id).name);assert.deepEqual(names,[...names].sort((a,b)=>a.localeCompare(b,'pl')));assert.equal(state.player.inventory.length,before);`));
test('selling controls exist in shop but not in backpack item details',()=>run(`const idx=backpackEntries().find(e=>itemDef(e.item.id).value>0).index;assert.ok(!inventoryCard(state.player.inventory[idx],idx).includes('data-sell='));assert.ok(shopHTML().includes('data-shop-sell='));`));
test('shop sale can sell multiple units from a stack',()=>run(`const idx=state.player.inventory.findIndex(i=>i.id==='potion'),unit=itemSellValue(state.player.inventory[idx]),q=countItem('potion'),gold=state.player.gold;const result=sellIndex(idx,2,false);assert.equal(result.amount,2);assert.equal(countItem('potion'),q-2);assert.equal(state.player.gold,gold+unit*2);`));
test('combat starts at medium distance with main command menu',()=>run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});assert.equal(combat.distance,1);assert.equal(combat.menu,'main');`));
test('combat has four-command menu',()=>run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});originalOpenCombat();assert.ok(app.innerHTML.includes('data-command="fight"'));assert.ok(app.innerHTML.includes('data-command="position"'));assert.ok(app.innerHTML.includes('data-command="heal"'));assert.ok(app.innerHTML.includes('data-flee'));`));
test('melee offensive actions require close range',()=>run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});assert.equal(combatNeedsClose(null),true);combat.distance=0;assert.equal(combatNeedsClose(null),false);`));
test('enemy closes distance before normal hit',()=>run(`startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.distance=2;state.player.hp=state.player.maxHp;enemyTurn();assert.equal(combat.distance,1);assert.equal(state.player.hp,state.player.maxHp);`));
test('ranged classes receive distance damage modifier',()=>run(`state.player.class='hunter';startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.distance=2;assert.equal(combatRangeDamageMultiplier(),1.1);combat.distance=0;assert.equal(combatRangeDamageMultiplier(),.88);`));
console.log(`${count} regression checks passed.`);
test('auction listing removes item and charges listing fee',()=>run(`ensureEconomyState();const row=auctionListableEntries().find(e=>e.item.id==='potion'),before=countItem('potion'),gold=state.player.gold=1000;const price=40,fee=auctionListingFee(price,1);openBuilding=()=>{};listAuctionItem(row.index,1,price,12);assert.equal(countItem('potion'),before-1);assert.equal(state.player.gold,gold-fee);assert.equal(state.economy.auctionListings.length,1);assert.equal(state.economy.auctionListings[0].status,'active');`));
test('cancelling auction returns exact item quantity',()=>run(`ensureEconomyState();state.player.gold=1000;const row=auctionListableEntries().find(e=>e.item.id==='potion'),before=countItem('potion');openBuilding=()=>{};listAuctionItem(row.index,2,40,12);const id=state.economy.auctionListings[0].id;cancelAuctionListing(id);assert.equal(countItem('potion'),before);assert.equal(state.economy.auctionListings.length,0);`));
test('sold auction claim uses the settled payout',()=>run(`ensureEconomyState();state.economy.auctionListings=[{id:'x',item:{id:'potion',qty:1},qty:2,unitPrice:100,durationHours:12,status:'sold',payout:190}];const gold=state.player.gold;openBuilding=()=>{};claimAuctionGold('x');assert.equal(state.player.gold,gold+190);assert.equal(state.economy.auctionListings.length,0);`));
test('legacy saves receive level-one city buildings',()=>run(`const old=normalizeState({version:390,player:JSON.parse(JSON.stringify(state.player)),quests:{active:[],done:[],progress:{}},world:JSON.parse(JSON.stringify(state.world)),settings:{},tutorial:{},ui:{},adventure:{},economy:{}});assert.equal(old.city.buildings.shop,1);assert.equal(old.city.buildings.tavern,1);`));
test('tavern level raises active task limit',()=>run(`state.city.buildings.tavern=1;assert.equal(activeTaskLimit(),4);state.city.buildings.tavern=3;assert.equal(activeTaskLimit(),6);`));
test('shop level discounts merchant prices',()=>run(`state.city.buildings.shop=1;const base=merchantBuyPrice('potion');state.city.buildings.shop=3;assert.ok(merchantBuyPrice('potion')<base);`));
test('city building upgrade consumes gold and scrap',()=>run(`state.player.gold=1000;state.player.inventory.push({id:'scrap',qty:20});state.city.buildings.shop=1;const gold=state.player.gold,scrap=countItem('scrap'),cost=cityUpgradeCost('shop');upgradeCityBuilding('shop');assert.equal(state.city.buildings.shop,2);assert.equal(state.player.gold,gold-cost.gold);assert.equal(countItem('scrap'),scrap-cost.scrap);`));
test('battle uses dedicated back-view class asset',()=>run(`state.player.class='hunter';assert.ok(battleBackVisual('hunter').includes('battle-backs/hunter-back.png'));`));
test('ranged bow perk adds far-distance damage multiplier',()=>run(`state.player.class='hunter';state.player.equipped.weapon={id:'wildBow'};startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.distance=2;assert.ok(combatGearDamageMultiplier()>1);`));
test('mage staff reduces mana cost at far range',()=>run(`state.player.class='mage';state.player.equipped.weapon={id:'stormStaff'};startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.distance=2;const s=SKILLS.mage.find(x=>x.mana>5);assert.ok(s);assert.equal(combatSkillManaCost(s),Math.max(0,s.mana-5));`));
test('enemy families expose distinct combat profiles',()=>run(`startCombat({id:'ghost-x',template:'ghost',type:'monster',synthetic:true,variant:'normal',elite:false});assert.equal(enemyCombatProfile().style,'ranged');combat=null;startCombat({id:'wyv-x',template:'wyvern',type:'monster',synthetic:true,variant:'normal',elite:false});assert.equal(enemyCombatProfile().style,'charge');`));
console.log(`${count} regression checks passed after 3.9.5 polishing tests.`);
test('backpack arrange mode exposes empty slots as selectable targets',()=>run(`state.ui.bagArrangeMode=true;const html=drawerBagHTML();assert.ok(html.includes('data-bag-arrange'));assert.ok(html.includes('data-drawer-bag-pos='));assert.ok(html.includes('Pusty slot'));`));
test('manual backpack move can place item in an empty distant slot',()=>run(`const e=backpackEntries()[0],target=inventoryCapacity()-1;assert.ok(!backpackEntries().some(x=>x.slot===target));assert.ok(moveBackpackItemToSlot(e.index,target));assert.equal(e.item.bagSlot,target);assert.ok(!backpackEntries().some(x=>x.item!==e.item&&x.slot===target));`));
test('stamina is capped at 100 for existing saves',()=>run(`state.player.maxStamina=60;state.player.stamina=95;state=normalizeState(state);assert.equal(state.player.maxStamina,100);assert.equal(state.player.stamina,95);`));
test('starting combat consumes exactly three stamina',()=>run(`state.player.stamina=100;startCombat({id:'stamina-test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});assert.equal(state.player.stamina,97);`));
test('combat cannot start below three stamina',()=>run(`state.player.stamina=2;const ok=startCombat({id:'stamina-low',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});assert.equal(ok,false);assert.equal(combat,null);assert.equal(state.player.stamina,2);`));
test('tavern meals are limited to two uses per day',()=>run(`state.player.stamina=0;state.player.gold=1000;ensureTavernDaily();buyTavernStamina(10,10,'Piwo');buyTavernStamina(10,10,'Piwo');const before=state.player.stamina;buyTavernStamina(10,10,'Piwo');assert.equal(state.player.tavernDaily.mealUses,2);assert.equal(state.player.stamina,before);`));
test('fireplace rest is limited to two uses per day and restores resources',()=>run(`state.player.hp=1;state.player.mana=0;state.player.stamina=0;state.player.gold=1000;ensureTavernDaily();restByFire();assert.equal(state.player.hp,state.player.maxHp);assert.equal(state.player.mana,state.player.maxMana);assert.equal(state.player.stamina,25);restByFire();const gold=state.player.gold,st=state.player.stamina;restByFire();assert.equal(state.player.tavernDaily.fireplaceUses,2);assert.equal(state.player.gold,gold);assert.equal(state.player.stamina,st);`));

test('quest combat receives anti-one-shot HP scaling and enemy mana',()=>run(`state.player.stamina=60;startCombat({id:'quest-hard',template:'goblin',type:'monster',synthetic:true,variant:'normal',elite:false},{level:state.player.level,storyConsequence:{qid:'q2',choiceId:'track'}});assert.equal(combat.questFight,true);assert.ok(combat.maxHp>=Math.floor(attackPower()*3.8));assert.ok(combat.maxEnemyMana>=52);assert.equal(combat.enemyMana,combat.maxEnemyMana);`));
test('elite regeneration spends mana and restores HP',()=>run(`state.player.stamina=60;startCombat({id:'elite-heal',template:'wolf',type:'monster',synthetic:true,variant:'normal',elite:true},{level:state.player.level,storyConsequence:{qid:'q2',choiceId:'stand'}});combat.hp=Math.floor(combat.maxHp*.4);const hp=combat.hp,mana=combat.enemyMana;assert.equal(tryEliteRegeneration(),true);assert.ok(combat.hp>hp);assert.ok(combat.enemyMana<mana);`));
test('elite special attack consumes its own mana',()=>run(`state.player.stamina=60;startCombat({id:'elite-special',template:'goblin',type:'monster',synthetic:true,variant:'normal',elite:true},{level:state.player.level,storyConsequence:{qid:'q2',choiceId:'track'}});combat.enemyTurns=2;combat.enemySpecialCooldown=0;const mana=combat.enemyMana;tryEnemySpecialAttack();assert.ok(combat.enemyMana<mana);`));
test('enemy mana bar is rendered for quest enemies',()=>run(`state.player.stamina=60;startCombat({id:'quest-ui',template:'goblin',type:'monster',synthetic:true,variant:'normal',elite:true},{level:state.player.level,storyConsequence:{qid:'q2',choiceId:'track'}});originalOpenCombat();assert.ok(app.innerHTML.includes('enemy-mana-bar'));assert.ok(app.innerHTML.includes('MANA '));`));


test('alchemy recipe purchase grants limited uses',()=>run(`ensureAlchemyState();state.player.gold=1000;openBuilding=()=>{};const price=alchemyRecipePrice('potion'),uses=alchemyRecipeOffer('potion').uses;buyAlchemyRecipe('potion');assert.equal(state.alchemy.recipeUses.potion,uses);assert.equal(state.player.gold,1000-price);`));
test('alchemy craft consumes one recipe use',()=>run(`ensureAlchemyState();state.alchemy.recipeUses.potion=2;state.player.gold=1000;state.player.inventory.find(i=>i.id==='herb').qty=10;openBuilding=()=>{};const before=countItem('potion');craftRecipe('potion');assert.equal(countItem('potion'),before+1);assert.equal(state.alchemy.recipeUses.potion,1);`));
test('guild Hero can be challenged solo without a party gate',()=>run(`ensureSocialState();state.social.party.members=[];state.player.stamina=100;combat=null;startGuildRaid('hero');assert.equal(combat.raidTier,'hero');assert.equal(combat.partyMembers.length,0);assert.ok(combat.maxHp>attackPower()*2);`));
test('guild Legend can also be challenged solo but keeps raid difficulty',()=>run(`ensureSocialState();state.social.party.members=[];state.player.stamina=100;combat=null;startGuildRaid('legend');assert.equal(combat.raidTier,'legend');assert.equal(combat.partyMembers.length,0);assert.ok(combat.maxHp>attackPower()*4);assert.ok(raidSoloRecommendedLevel('legend',combat.level)>combat.level);`));
test('raid party assist damages boss and records contribution',()=>run(`ensureSocialState();state.social.party.members=TEST_PARTY_CANDIDATES.map(x=>({...x,level:state.player.level,ai:true}));startGuildRaid('legend');const hp=combat.hp;raidPartyAssist();assert.ok(combat.hp<hp);assert.ok(combat.raidPartyDamage>0);`));

test('raid encounter level is independent from player level so it can be overleveled',()=>run(`const m=raidMonster('hero'),lvl=raidEncounterLevel('hero',m),old=state.player.level;state.player.level=Math.min(100,old+20);assert.equal(raidEncounterLevel('hero',m),lvl);assert.ok(lvl>=m.min&&lvl<=m.max);`));
console.log(`${count} regression checks passed including 3.9.6.4 open raid/alchemy tests.`);

test('Scout Tower expands monster attack radius from 60 to 80 metres',()=>run(`state.player.guild='Testowa';ensureSocialState();assert.equal(guildMonsterAttackRadius(),60);state.social.guild.buildings.scout=5;assert.equal(guildMonsterAttackRadius(),70);state.social.guild.buildings.scout=10;assert.equal(guildMonsterAttackRadius(),80);assert.equal(entityInteractionRadius({type:'monster'}),80);assert.equal(entityInteractionRadius({type:'event'}),60);`));
test('guild contribution moves player resources into shared treasury',()=>run(`state.player.guild='Testowa';ensureSocialState();state.player.gold=1000;state.player.inventory.push({id:'scrap',qty:3});contributeGuild('gold',500);contributeGuild('scrap',1);assert.equal(state.player.gold,500);assert.equal(state.social.guild.treasury.gold,500);assert.equal(state.social.guild.treasury.scrap,1);assert.equal(state.social.guild.contributions[state.player.name].gold,500);assert.equal(state.social.guild.contributions[state.player.name].materials,1);`));
test('guild building upgrades spend treasury and persist level',()=>run(`state.player.guild='Testowa';ensureSocialState();const cost=guildBuildingCost('scout');state.social.guild.treasury.gold=cost.gold;state.social.guild.treasury.scrap=cost.scrap;state.social.guild.treasury.crystal=cost.crystal;state.social.guild.treasury.runeShard=cost.runeShard;upgradeGuildBuilding('scout');assert.equal(guildBuildingLevel('scout'),1);assert.equal(guildMonsterAttackRadius(),62);assert.equal(state.social.guild.treasury.gold,0);`));
test('guild forge and alchemist development provide functional bonuses',()=>run(`state.player.guild='Testowa';ensureSocialState();state.social.guild.buildings.forge=5;assert.equal(guildForgeDiscount(),.10);state.social.guild.buildings.alchemist=4;assert.equal(guildAlchemyExtraUses(),2);`));
console.log(`${count} regression checks passed including 3.9.6.5 guild development tests.`);


test('guild member rank starts from zero when joining even with lifetime kills',()=>run(`state.player.kills=999;state.player.guild='Testowa';ensureSocialState();assert.equal(state.player.guildMembership.kills,0);assert.equal(guildMemberRankInfo().rank,'Nowicjusz');`));
test('guild member ranks advance from E to SS at configured kill thresholds',()=>run(`state.player.guild='Testowa';ensureSocialState();const checks=[[49,'Nowicjusz'],[50,'E'],[150,'D'],[400,'C'],[800,'B'],[1500,'A'],[3000,'S'],[6000,'SS']];for(const [kills,rank] of checks){state.player.guildMembership.kills=kills;assert.equal(guildMemberRankInfo().rank,rank)}`));
test('guild monster kill counter only advances while player belongs to a guild',()=>run(`state.player.guild=null;ensureSocialState();recordGuildMonsterKill();assert.equal(state.player.guildMembership.kills,0);state.player.guild='Testowa';ensureSocialState();recordGuildMonsterKill();recordGuildMonsterKill('hero');recordGuildMonsterKill('legend');assert.equal(state.player.guildMembership.kills,3);assert.equal(state.player.guildMembership.heroKills,1);assert.equal(state.player.guildMembership.legendKills,1);`));
test('guild rank kill tracking is integrated into combat victory',()=>run(`state.player.guild='Testowa';ensureSocialState();state.player.stamina=100;showBattleVictory=()=>{};startCombat({id:'guild-rank-kill',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.hp=0;winCombat();assert.equal(state.player.guildMembership.kills,1);`));
console.log(`${count} regression checks passed including 3.9.6.6 guild member rank tests.`);


test('every map monster shows its level and combat uses the same stored level',()=>run(`state.player.level=20;const e={id:'map-level-test',template:'wolf',type:'monster',variant:'normal',alive:true};const html=mapMonsterHTML(e,40,false),shown=e.level;assert.ok(html.includes('creature-level'));assert.ok(html.includes('Lv. '+shown));state.player.stamina=100;startCombat(e);assert.equal(combat.level,shown);`));
test('map monster level remains stable after repeated renders',()=>run(`state.player.level=22;const e={id:'stable-level-test',template:'goblin',type:'monster',variant:'normal',alive:true};mapMonsterHTML(e,50,false);const lvl=e.level;state.player.level=30;mapMonsterHTML(e,50,false);assert.equal(e.level,lvl);`));
console.log(`${count} regression checks passed including 3.9.6.7 map monster level labels.`);


test('enemy HP bar renders a delayed grey damage layer',()=>run(`state.player.stamina=100;combat=null;startCombat({id:'hp-ghost',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});const before=combat.hp;combat.hp=Math.max(0,before-7);markEnemyHpDamage(before);originalOpenCombat();assert.ok(app.innerHTML.includes('enemy-hp-loss'));assert.ok(app.innerHTML.includes('--ghost-start:'));assert.ok(app.innerHTML.includes('enemy-hp-current'));`));
test('lethal hit enters a short victory animation before rewards resolve',()=>run(`state.player.stamina=100;combat=null;startCombat({id:'victory-delay',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.hp=0;queueCombatVictory();assert.ok(combat);assert.equal(combat.phase,'victoryDelay');assert.equal(combat.victoryAnimating,true);assert.equal(combat.enemyVanishing,false);`));
console.log(`${count} regression checks passed including 3.9.6.8 battle HP/defeat animation tests.`);


test('character system exposes exactly five independent slots',()=>run(`localStorage.removeItem(CHARACTER_META_REAL);for(let i=1;i<=CHARACTER_LIMIT;i++)localStorage.removeItem(characterSlotKey(i,'gps'));assert.equal(CHARACTER_LIMIT,5);assert.equal(characterSlots().length,5);assert.equal(activeCharacterSlot(),1);`));
test('switching characters preserves current save and activates selected slot',()=>run(`localStorage.removeItem(CHARACTER_META_REAL);for(let i=1;i<=CHARACTER_LIMIT;i++)localStorage.removeItem(characterSlotKey(i,'gps'));state.player.name='Pierwszy';const second=JSON.parse(JSON.stringify(state));second.player.name='Drugi';second.player.class='mage';second.player.level=7;localStorage.setItem(characterSlotKey(2,'gps'),JSON.stringify(second));switchCharacterSlot(2);assert.equal(activeCharacterSlot(),2);assert.equal(JSON.parse(localStorage.getItem(characterSlotKey(1,'gps'))).player.name,'Pierwszy');assert.equal(JSON.parse(localStorage.getItem(REAL_SAVE_KEY)).player.name,'Drugi');`));
test('creating an empty slot keeps previous character and opens selected slot',()=>run(`SAVE_KEY=REAL_SAVE_KEY;localStorage.removeItem(CHARACTER_META_REAL);for(let i=1;i<=CHARACTER_LIMIT;i++)localStorage.removeItem(characterSlotKey(i,'gps'));state.player.name='Zachowany';createCharacterSlot(3);assert.equal(activeCharacterSlot(),3);assert.equal(JSON.parse(localStorage.getItem(characterSlotKey(1,'gps'))).player.name,'Zachowany');assert.equal(localStorage.getItem(REAL_SAVE_KEY),null);assert.equal(state,null);`));
console.log(`${count} regression checks passed including 3.9.7.1 five-character slots.`);


test('active character save is always mirrored into its own slot',()=>run(`SAVE_KEY=REAL_SAVE_KEY;for(let i=1;i<=CHARACTER_LIMIT;i++)localStorage.removeItem(characterSlotKey(i,'gps'));setActiveCharacterSlot(2);state=normalizeState(${base});state.player.name='SlotDrugi';state.player.gold=777;save();assert.equal(JSON.parse(localStorage.getItem(characterSlotKey(2,'gps'))).player.name,'SlotDrugi');assert.equal(JSON.parse(localStorage.getItem(characterSlotKey(2,'gps'))).player.gold,777);assert.equal(JSON.parse(localStorage.getItem(REAL_SAVE_KEY)).player.name,'SlotDrugi');`));
test('new character created in second slot does not overwrite first character',()=>run(`SAVE_KEY=REAL_SAVE_KEY;for(let i=1;i<=CHARACTER_LIMIT;i++)localStorage.removeItem(characterSlotKey(i,'gps'));localStorage.removeItem(CHARACTER_META_REAL);setActiveCharacterSlot(1);state=normalizeState(${base});state.player.name='PierwszyBohater';state.created=111;save();createCharacterSlot(2);newGame('DrugiBohater','mage');const one=JSON.parse(localStorage.getItem(characterSlotKey(1,'gps'))),two=JSON.parse(localStorage.getItem(characterSlotKey(2,'gps')));assert.equal(one.player.name,'PierwszyBohater');assert.equal(one.created,111);assert.equal(two.player.name,'DrugiBohater');assert.equal(two.player.class,'mage');assert.notEqual(two.created,one.created);`));
test('load prefers selected slot over stale canonical mirror',()=>run(`SAVE_KEY=REAL_SAVE_KEY;for(let i=1;i<=CHARACTER_LIMIT;i++)localStorage.removeItem(characterSlotKey(i,'gps'));const one=normalizeState(${base}),two=normalizeState(${base});one.player.name='SlotJeden';one.created=101;two.player.name='SlotDwa';two.created=202;localStorage.setItem(characterSlotKey(1,'gps'),JSON.stringify(one));localStorage.setItem(characterSlotKey(2,'gps'),JSON.stringify(two));setActiveCharacterSlot(1);localStorage.setItem(REAL_SAVE_KEY,JSON.stringify(two));state=load();assert.equal(state.player.name,'SlotJeden');assert.equal(JSON.parse(localStorage.getItem(REAL_SAVE_KEY)).player.name,'SlotJeden');`));
console.log(`${count} regression checks passed including 3.9.7.2 isolated character save fix.`);


test('first tutorial kill guarantees the correct class-specific loot',()=>run(`const expected={knight:'tutorialKnightShield',mage:'tutorialMageStaff',hunter:'tutorialHunterBow',berserker:'tutorialBerserkerAxe',ranger:'tutorialRangerHood'};for(const cls of Object.keys(expected)){newGame('Tester',cls);state.tutorial.introSeen=true;state.tutorial.rewardGiven=false;state.tutorial.complete=false;const loot=rollCombatLoot(MONSTERS[0],{elite:false},{isBoss:false,worldBoss:false});assert.equal(loot.drops[0].id,expected[cls]);assert.equal(loot.drops[0].tutorial,true);assert.equal(itemDef(expected[cls]).reqLevel,1);assert.equal(itemDef(expected[cls]).classes.length,1);assert.equal(itemDef(expected[cls]).classes[0],cls);assert.equal(state.tutorial.rewardGiven,true)}`));
console.log(`${count} regression checks passed including 3.9.7.3 guaranteed tutorial class loot.`);


test('higher-level enemies gain HP and attack pressure',()=>run(`state.player.level=6;const hpMult=enemyHpLevelGapMultiplier(14),atkMult=enemyAtkLevelGapMultiplier(14);assert.ok(hpMult>1.4);assert.ok(atkMult>1.5);assert.ok(hpMult<=1.72);assert.ok(atkMult<=1.84);`));
test('player damage is reduced against much higher-level enemies',()=>run(`state.player.level=6;combat={level:14};assert.ok(playerVsEnemyLevelMultiplier()<.8);combat={level:6};assert.equal(playerVsEnemyLevelMultiplier(),1);`));
test('ranger trap trial requires ten wolves and ignores level gate',()=>run(`newGame('Tropiciel','ranger');state.player.level=1;state.player.skillPoints=5;state.player.bestiary.wolf=9;const trap=SKILLS.ranger.find(s=>s.id==='trap');assert.equal(skillTrialProgress(trap).done,false);state.player.bestiary.wolf=10;assert.equal(skillTrialProgress(trap).done,true);learnSkill('trap');assert.ok(state.player.skills.includes('trap'));`));
console.log(`${count} regression checks passed including 3.9.7.4 level balance and class trials.`);


test('hero and legend HP scale nonlinearly with party size',()=>run(`assert.equal(raidPartyHpMultiplier('hero',1),1);assert.equal(raidPartyHpMultiplier('hero',2),1.65);assert.equal(raidPartyHpMultiplier('hero',4),2.7);assert.equal(raidPartyHpMultiplier('legend',2),1.8);assert.equal(raidPartyHpMultiplier('legend',4),3.2);`));
test('raid enemy keeps a fixed level while party size only changes HP',()=>run(`state.player.level=20;state.player.stamina=100;combat=null;const e={id:'raid-fixed',template:'goblinChampion',type:'monster',synthetic:true,elite:true};startCombat(e,{level:30,raid:{tier:'hero',party:[]}});const soloHp=combat.maxHp;assert.equal(combat.level,30);combat=null;state.player.stamina=100;startCombat({...e,id:'raid-party'},{level:30,raid:{tier:'hero',party:[{name:'A',level:20,class:'knight'},{name:'B',level:28,class:'mage'}]}});assert.equal(combat.level,30);assert.equal(combat.raidPartyHpMult,2.2);assert.ok(combat.maxHp>soloHp*2.1&&combat.maxHp<soloHp*2.3);`));
test('party members are penalized individually when under enemy level',()=>run(`assert.ok(partyMemberVsEnemyLevelMultiplier(20,30)<partyMemberVsEnemyLevelMultiplier(30,30));assert.ok(partyMemberVsEnemyLevelMultiplier(35,30)>1);`));
test('anti boost reward reduction applies only to grouped raids',()=>run(`state.player.level=10;let c={raidTier:'legend',level:30,partyMembers:[{name:'A'}],raidPlayerActions:1,raidPlayerDamage:10,raidPartyDamage:990};let r=raidRewardProfile(c);assert.ok(r.scale<.5);assert.equal(r.fullLoot,false);c.partyMembers=[];r=raidRewardProfile(c);assert.equal(r.scale,1);assert.equal(r.fullLoot,true);`));
console.log(`${count} regression checks passed including 3.9.7.5 party scaling and anti-boost rewards.`);

test('new character starts with tutorial and no story quest',()=>run(`newGame('TutorialTester','knight');assert.equal(state.tutorial.complete,false);assert.equal(state.quests.active.length,0);assert.equal(ensureStoryQuestContinuity(false),null);`));
test('story quest unlocks only after tutorial completion',()=>run(`newGame('TutorialTester','knight');state.tutorial.introSeen=true;state.tutorial.flags={move:true,kill:true,inventory:true,equip:true,skill:true,tavern:true};state.player.skills=['shieldBash'];state.tutorial.stage=0;advanceTutorial();assert.equal(state.tutorial.complete,true);assert.ok(state.quests.active.includes('q1'));`));
test('quest board is locked while tutorial is unfinished',()=>run(`newGame('TutorialTester','knight');state.tutorial.introSeen=true;const html=tavernBoardHTML();assert.ok(html.includes('Zadania jeszcze czekają'));assert.ok(html.includes('Najpierw ukończ samouczek'));`));
console.log(`${count} regression checks passed including 3.9.7.6 tutorial-first quest gating.`);

test('pagehide save cannot overwrite destination slot during character switch',()=>run(`SAVE_KEY=REAL_SAVE_KEY;characterSlotTransition=false;for(let i=1;i<=CHARACTER_LIMIT;i++)localStorage.removeItem(characterSlotKey(i,'gps'));localStorage.removeItem(CHARACTER_META_REAL);setActiveCharacterSlot(1);state=normalizeState(${base});state.player.name='Pierwszy';state.created=111;save();const two=normalizeState(${base});two.player.name='Drugi';two.player.class='mage';two.created=222;localStorage.setItem(characterSlotKey(2,'gps'),JSON.stringify(two));switchCharacterSlot(2);assert.equal(activeCharacterSlot(),2);assert.equal(state.player.name,'Drugi');save();assert.equal(JSON.parse(localStorage.getItem(characterSlotKey(1,'gps'))).player.name,'Pierwszy');assert.equal(JSON.parse(localStorage.getItem(characterSlotKey(2,'gps'))).player.name,'Drugi');characterSlotTransition=false;`));
test('registry cleanup frees duplicate slot created by old overwrite bug',()=>run(`SAVE_KEY=REAL_SAVE_KEY;characterSlotTransition=false;for(let i=1;i<=CHARACTER_LIMIT;i++)localStorage.removeItem(characterSlotKey(i,'gps'));const same=normalizeState(${base});same.player.name='Duplikat';same.created=999;localStorage.setItem(characterSlotKey(1,'gps'),JSON.stringify(same));localStorage.setItem(characterSlotKey(2,'gps'),JSON.stringify(same));setActiveCharacterSlot(2);repairCharacterRegistry();assert.equal(rawLoad(characterSlotKey(1,'gps')),null);assert.equal(rawLoad(characterSlotKey(2,'gps')).player.name,'Duplikat');`));
console.log(`${count} regression checks passed including 3.9.7.7 character switch race fix.`);

test('every skill has an explicit class-specific trial',()=>run(`for(const [cls,list] of Object.entries(SKILLS)){state.player.class=cls;for(const skill of list){const t=CLASS_SKILL_TRIALS[cls]?.[skill.id];assert.ok(t,cls+' '+skill.id);assert.ok(!/^Pokonaj \\d+ przeciwników$/.test(t.label),t.label)}}`));
test('knight trials reward defensive play instead of raw kill count',()=>run(`newGame('Tank','knight');state.player.trialStats.blocks=4;const fortress=SKILLS.knight.find(s=>s.id==='fortress');assert.equal(skillTrialProgress(fortress).done,false);trialStat('blocks');assert.equal(skillTrialProgress(fortress).done,true);`));
test('hunter marked critical trial tracks precision play',()=>run(`newGame('Hunter','hunter');state.player.trialStats.markedCrits=5;const skill=SKILLS.hunter.find(s=>s.id==='eagleEye');assert.equal(skillTrialProgress(skill).done,true);assert.ok(skillTrialText(skill).includes('oznaczonym'));`));
test('berserker trial can require low hp critical hits',()=>run(`newGame('Bers','berserker');state.player.trialStats.critLowHp=6;const skill=SKILLS.berserker.find(s=>s.id==='bloodRush');assert.equal(skillTrialProgress(skill).done,true);`));
test('ranger trap still requires ten wolves while other ranger trials use class mechanics',()=>run(`newGame('Trop','ranger');state.player.bestiary.wolf=10;state.player.trialStats.poisonApplied=8;assert.equal(skillTrialProgress(SKILLS.ranger.find(s=>s.id==='trap')).done,true);assert.equal(skillTrialProgress(SKILLS.ranger.find(s=>s.id==='destiny')).done,true);`));
console.log(`${count} regression checks passed including 3.9.7.8 specialized class trials.`);


test('equal-level combat has no hidden level modifier and uses parity floors',()=>run(`state.player.level=5;combat={level:5};assert.equal(playerVsEnemyLevelMultiplier(),1);assert.equal(enemyHpLevelGapMultiplier(5),1);assert.equal(enemyAtkLevelGapMultiplier(5),1);const m=monsterTemplate({id:'parity-wolf',template:'wolf',variant:'normal'});assert.ok(enemyLevelHpFloor(5,m)>=100);assert.ok(enemyLevelAtkFloor(5,m)>=18);`));
test('large level gap is substantially more dangerous than before',()=>run(`state.player.level=5;combat={level:13};assert.ok(playerVsEnemyLevelMultiplier()<=.6);assert.ok(enemyHpLevelGapMultiplier(13)>=1.45);assert.ok(enemyAtkLevelGapMultiplier(13)>=1.55);`));
test('collapsed task bar shows active story objective',()=>run(`state.tutorial.complete=true;state.quests.active=['q1'];state.quests.progress.q1=[0];const html=mobileMapSheetToggleHTML();assert.ok(html.includes('has-task'));assert.ok(html.includes(QUESTS.find(q=>q.id==='q1').name));`));
test('map task panel includes accepted tavern bounties',()=>run(`state.tutorial.complete=true;ensureAdventureState();const b=state.adventure.bounties[0];b.accepted=true;b.claimed=false;b.progress=0;const html=mapQuestPanelHTML();assert.ok(html.includes(b.name));assert.ok(html.includes('ZLECENIA Z KARCZMY'));`));
console.log(`${count} regression checks passed including 3.9.8.0 balance and task tracker.`);

// 3.9.8.1 tutorial onboarding regression checks
test('tutorial creates one dedicated level 1 starter monster after movement',()=>run(`newGame('Nowy','mage');state.tutorial.introSeen=true;state.tutorial.stage=0;state.tutorial.flags={};tutorialEvent('move',60);const e=state.world.entities.find(x=>x.id===TUTORIAL_FIRST_MONSTER_ID);assert.ok(e);assert.equal(e.level,1);assert.equal(entityMonsterLevel(e,monsterTemplate(e)),1);assert.equal(e.elite,false);`));
test('other monsters are hidden until tutorial starter is defeated',()=>run(`newGame('Nowy','knight');state.tutorial.introSeen=true;state.tutorial.flags.move=true;state.tutorial.stage=1;ensureTutorialStarterMonster(state,true);const starter=state.world.entities.find(x=>x.tutorialStarter),normal=state.world.entities.find(x=>x.type==='monster'&&!x.tutorialStarter);assert.equal(questWorldEntityVisible(starter),true);assert.equal(questWorldEntityVisible(normal),false);`));
test('first skill for every class unlocks after the first tutorial kill',()=>run(`for(const [cls,skillId] of Object.entries({knight:'shield',mage:'fire',hunter:'double',berserker:'rage',ranger:'poison'})){newGame('Nowy',cls);state.tutorial.introSeen=true;state.tutorial.flags.kill=true;const sk=SKILLS[cls].find(x=>x.id===skillId);assert.equal(skillTrialProgress(sk).done,true,cls);assert.equal(skillTrialProgress(sk).trial.count,1,cls);}`));
console.log(`${count} regression checks passed including 3.9.8.1 tutorial starter and first-skill unlock.`);


// 3.9.8.5 weapon build-choice regression checks
test('arsenal keeps at least ninety one build weapons after monster-drop expansion',()=>run(`assert.ok(Object.values(ITEMS).filter(d=>d.type==='weapon').length>=91);`));
test('every class has at least three exact-level weapon choices on core build tiers',()=>run(`for(const cls of Object.keys(CLASSES)){for(const lvl of [7,12,20,28,36,45]){const choices=Object.values(ITEMS).filter(d=>d.type==='weapon'&&d.classes?.includes(cls)&&d.reqLevel===lvl);assert.ok(choices.length>=3,cls+' lvl '+lvl+' has '+choices.length);}}`));
test('new weapons expose distinct build tags and combat perks',()=>run(`for(const id of ["steelSaber", "watchmanMace", "oathSword", "ironVowHammer", "bastionBlade", "guardianSpear", "mistBulwarkSword", "sentinelHammer", "ashOathSword", "ashSentinelHammer", "stormHalberd", "stormOathBlade", "raiderAxe", "cleaver", "bloodAxe", "skullHammer", "ravenAxe", "executionerBlade", "mistReaver", "breakerMaul", "ashReaver", "ashSkullMaul", "stormGreatAxe", "stormBloodBlade", "focusWand", "sparkRod", "frostStaff", "manaRod", "emberStaff", "voidWand", "runeStaff20", "mistWand", "frostScepter", "ashWand", "runicScepter", "tempestWand", "stormScepter", "scoutLongbow", "quickBow", "eagleBow", "piercingBow", "ravenLongbow", "beastmasterBow", "mistLongbow", "falconBow", "ashLongbow", "marksmanBow", "stormLongbow", "skyPiercer", "serpentBow", "trailBow", "venomBow", "trapperBow", "wildVenomBow", "beastBondBow", "mistVenomBow", "stalkerBow", "ashVenomBow", "shadowBow", "tempestTrackerBow", "stormSerpentBow"]){const d=itemDef(id);assert.ok(d.build,id);assert.ok(itemCombatPerk(id)?.label,id);}`));
test('shop keeps an ordinary class weapon at each merchant tier',()=>run(`state.player.class='ranger';state.ui={};for(const lvl of [1,12,25,40,55,70,85,100]){state.player.level=lvl;const gear=shopInventoryPages()[2];assert.ok(gear.some(id=>itemDef(id).slot==='weapon'&&itemDef(id).reqLevel===lvl),'weapon '+lvl);assert.ok(gear.every(id=>itemDef(id).rarity==='common'&&itemClassAllowed(itemDef(id))));}`));
console.log(`${count} regression checks passed including 3.9.8.5 build-oriented weapon choices.`);


// 3.9.8.7 — curated monster loot and level synchronization
const app3987=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
test('curated loot covers all 117 monsters',()=>{assert.ok(/const CURATED_MONSTER_LOOT=\{/.test(app3987));assert.ok((app3987.match(/\"chance\":/g)||[]).length>250)});
test('curated level table covers all monster definitions',()=>{assert.ok((app3987.match(/\":\[/g)||[]).length>=117)});
test('named Heros and Legends become boss encounters',()=>{assert.ok(app3987.includes("curatedBoss=['Elita','Heros','Legenda'].includes(m.rank)"))});
test('legendary named monsters use legendary loot tier',()=>{assert.ok(app3987.includes("m.rank==='Legenda'"))});
test('bestiary displays curated rank',()=>{assert.ok(app3987.includes("m.rank&&m.rank!=='Zwykły'"))});
console.log(`${count} regression checks passed including 3.9.8.7 curated 117-monster loot tables.`);


// 3.9.8.8 — endgame 80/90/100 + boss uniques
const data3988=fs.readFileSync(new URL('../data.js',import.meta.url),'utf8');
test('endgame class gear tiers include 80 90 and 100',()=>{for(const lvl of [80,90,100])assert.ok(data3988.includes(`{level:${lvl},rarity:'legendary'`),String(lvl))});
test('all five classes have named 100-level sets',()=>{for(const name of ['Wiecznego Bastionu','Ostatniej Furii','Szaty Eteru','Łowcy Horyzontu','Pradawnego Śladu'])assert.ok(data3988.includes(name),name)});
test('storm drake and basilisk are legends',()=>{assert.ok(app3987.includes('"stormDrake":"Legenda"'));assert.ok(app3987.includes('"bazyliszek":"Legenda"'))});
test('endgame weapons cover five classes and three tiers',()=>{for(const cls of ['knight','berserker','mage','hunter','ranger'])for(const lvl of [80,90,100])assert.ok(app3987.includes(`'end_${cls}_${lvl}'`),cls+' '+lvl)});
test('boss loot no longer uses kraken placeholder entry',()=>{const tail=app3987.slice(app3987.indexOf('const ENDGAME_BOSS_LOOT='));assert.ok(!/mlodyKraken:[\s\S]{0,1000}mat_dopisz_jeszcze_kilka/.test(tail))});
test('endgame crafting materials and recipes are registered',()=>{for(const id of ['gryphonSeal','stormSigil','eternalCore'])assert.ok(app3987.includes(id),id);assert.ok(app3987.includes('registerEndgameRecipe'))});
console.log(`${count} regression checks passed including 3.9.8.8 endgame sets and boss uniques.`);

// 3.9.8.9 — runes, enchant, upgrades and economy
test('thirteen runes expose authored build effects',()=>run(`assert.equal(ALL_RUNE_IDS.length,13);assert.equal(itemDef('runePower').runeValue,4);assert.ok(itemDef('runePoison').perk.poisonAmp>=.25);assert.ok(itemDef('runeWind').perk.dodgeBonus>=3);assert.ok(itemDef('runeLight').perk.blockBonus>=4);`));
test('runes respect equipment slot restrictions',()=>run(`assert.equal(runeFitsItem('runePower',{id:'shortBlade'}),true);assert.equal(runeFitsItem('runeGuard',{id:'shortBlade'}),false);assert.equal(runeFitsItem('runeGuard',{id:'stormCrown'}),true);`));
test('every rune has a smith recipe with valid ingredients',()=>run(`for(const id of ALL_RUNE_IDS){const r=RECIPES.find(x=>x.station==='smith'&&x.result===id);assert.ok(r,id);for(const ing of Object.keys(r.ingredients))assert.ok(ITEMS[ing],id+' ingredient '+ing);}`));
test('upgrade cap scales with rarity from five to ten',()=>run(`assert.equal(itemUpgradeCap({id:'shortBlade'}),5);assert.equal(itemUpgradeCap({id:'stormCrown'}),10);`));
test('high upgrades consume crystals and rune shards',()=>run(`const q5=upgradeQuote({id:'stormCrown',upgrade:4}),q8=upgradeQuote({id:'stormCrown',upgrade:7}),q9=upgradeQuote({id:'stormCrown',upgrade:8});assert.ok(q5.crystal>=1);assert.ok(q8.shard>=1);assert.ok(q9.crystal>=2);`));
test('enchant pool depends on equipment slot',()=>run(`const weapon=enchantPoolFor({id:'shortBlade'}).map(x=>x.name),helmet=enchantPoolFor({id:'stormCrown'}).map(x=>x.name);assert.ok(weapon.includes('Płomień'));assert.ok(!weapon.includes('Bastion'));assert.ok(helmet.includes('Bastion'));`));
test('enchant reroll uses twelve hour cooldown',()=>run(`const now=Date.now(),i={enchantRerollAt:now+ENCHANT_REROLL_COOLDOWN};assert.equal(ENCHANT_REROLL_COOLDOWN,12*60*60*1000);assert.ok(enchantRerollRemaining(i)>11*60*60*1000);`));
test('curated low chance labels keep decimal precision',()=>run(`assert.equal(lootChanceLabel(.008),'0.8%');assert.equal(lootChanceLabel(.045),'4.5%');`));
test('auction economy uses three percent listing fee and seven percent commission',()=>run(`assert.equal(auctionListingFee(100,2),6);assert.equal(auctionSalePayout({unitPrice:100,qty:2}),186);`));
test('active curated loot contains no remaining editorial placeholders',()=>run(`assert.ok(!MONSTER_LOOT.rusalka.some(x=>x.id==='mat_jakies_unikaty_dla_maga'));assert.ok(!MONSTER_LOOT.goblinMage.some(x=>x.id==='drop_goblinMage_pierscienie_i_naszyjnik_dla_kazdej_klasy'));assert.ok(MONSTER_LOOT.rusalka.some(x=>x.id==='drop_rusalka_diadem_topieli'));`));
console.log(`${count} regression checks passed including 3.9.8.9 runes, enchant, upgrades and economy.`);

// 3.9.9.0 — pełny crafting z materiałów potworów
test('crafting expansion registers eleven processed monster materials',()=>run(`for(const id of ['curedLeather','bonePlate','spiritDust','toxinConcentrate','demonAlloy','frostAlloy','stormAlloy','abyssThread','runicComposite','herbalExtract','arcaneResin'])assert.ok(ITEMS[id],id);`));
test('crafting expansion has at least thirty five authored recipes',()=>run(`assert.ok(CRAFTING_EXPANSION_RECIPES.length>=35);for(const r of CRAFTING_EXPANSION_RECIPES){assert.ok(ITEMS[r.result],r.id+' result');for(const ing of Object.keys(r.ingredients))assert.ok(ITEMS[ing],r.id+' '+ing);}`));
test('every class receives craft-only gear on levels 25 55 and 75',()=>run(`for(const cls of Object.keys(CLASSES))for(const lvl of [25,55,75]){const rows=Object.values(ITEMS).filter(d=>d.craftOnly&&d.classes?.includes(cls)&&d.reqLevel===lvl);assert.ok(rows.length>=1,cls+' '+lvl);}`));
test('craft-only equipment exposes build perks',()=>run(`for(const d of Object.values(ITEMS).filter(x=>x.craftOnly)){assert.ok(d.build,d.id);assert.ok(itemCombatPerk(d.id)?.label,d.id);}`));
test('monster loot materials feed a broad crafting ingredient pool',()=>run(`const used=new Set(CRAFTING_EXPANSION_RECIPES.flatMap(r=>Object.keys(r.ingredients)));assert.ok(used.size>=35);for(const id of ['hide','furBundle','bone','fang','ectoplasm','graveDust','venomGland','demonHorn','frostClaw','stormCore','mireSilk','shadowEssence'])assert.ok(used.has(id),id);`));
test('processing recipe consumes raw drops and creates the processed material',()=>run(`state.player.gold=9999;state.player.inventory.push({id:'hide',qty:2},{id:'furBundle',qty:2},{id:'roughCloth',qty:1});const before=countItem('curedLeather');craftRecipe('proc_curedLeather');assert.equal(countItem('curedLeather'),before+1);assert.equal(countItem('hide'),0);assert.equal(countItem('furBundle'),0);`));
test('smith catalogue is grouped into processing runes weapons and equipment',()=>run(`const html=smithHTML();for(const label of ['Przetwarzanie','Runy','Broń','Ekwipunek'])assert.ok(html.includes(label),label);`));
console.log(`${count} regression checks passed including 3.9.9.0 full monster-material crafting.`);


// 3.9.9.1 — chronione rarity tylko z dropu
test('unikatowe heroiczne i legendarne gear nie mają receptur kowala',()=>run(`for(const r of RECIPES.filter(x=>x.station==='smith')){const d=ITEMS[r.result];if(d?.slot)assert.ok(!['epic','heroic','legendary'].includes(d.rarity),r.id+' -> '+d.rarity);}`));
test('rzadki gear wymaga co najmniej jednego rzadkiego materialu',()=>run(`for(const r of RECIPES.filter(x=>x.station==='smith')){const d=ITEMS[r.result];if(d?.slot&&d.rarity==='rare'){assert.ok(Object.keys(r.ingredients).some(id=>['rare','epic','heroic','legendary'].includes(ITEMS[id]?.rarity)),r.id);}}`));
test('craft-only gear 25 55 75 pozostaje maksymalnie rzadki',()=>run(`for(const d of Object.values(ITEMS).filter(x=>x.craftOnly))assert.ok(['common','uncommon','rare'].includes(d.rarity),d.id+' '+d.rarity);`));
test('endgame legendary weapons are drop only',()=>run(`for(const [id] of ENDGAME_WEAPONS)assert.ok(!RECIPES.some(r=>r.station==='smith'&&r.result===id),id);`));
test('epic rarity is presented as Unikatowy',()=>run(`assert.equal(rarityName('epic'),'Unikatowy');`));
console.log(`${count} regression checks passed including 3.9.9.1 protected boss rarities.`);

// 3.9.9.2 — Szczęście i leczenie Maga
test('wszystkie klasy mają bazową statystykę Szczęścia',()=>run(`for(const c of Object.values(CLASSES))assert.equal(c.base.lck,3);newGame('Luck','knight');assert.equal(state.player.stats.lck,3);`));
test('10 Szczęścia daje 1 pp kryta i 2 procent względnej premii do rzadkiego łupu',()=>run(`state.player.stats.lck=10;state.player.equipped={};assert.equal(totalLuck(),10);assert.equal(luckCritBonus(),1);assert.ok(Math.abs(luckLootMultiplier()-1.02)<1e-9);assert.ok(Math.abs(luckLootBonusPct()-2)<1e-9);`));
test('Runa Szczęścia zwiększa LCK zamiast bezpośredniego krytyka',()=>run(`const r=itemDef('runeLuck');assert.equal(r.runeKey,'lck');assert.equal(r.runeValue,5);`));
test('Mag ma Uzdrowienie za manę skalowane Inteligencją',()=>run(`const heal=SKILLS.mage.find(s=>s.id==='heal');assert.ok(heal);assert.equal(heal.kind,'heal');assert.equal(heal.mana,18);assert.equal(heal.cooldown,2);assert.ok(heal.healInt>0);`));
test('sojusznicy rajdu otrzymują własne HP i mogą być celem leczenia',()=>run(`newGame('Mag','mage');combat={partyMembers:prepareCombatPartyMembers([{name:'Rycerz',class:'knight',level:20}]),log:[]};const ally=combat.partyMembers[0];assert.equal(ally.hp,ally.maxHp);ally.hp=Math.floor(ally.maxHp/2);const before=ally.hp,heal=SKILLS.mage.find(s=>s.id==='heal');const restored=castMageHeal(heal,ally._combatId);assert.ok(restored>0);assert.ok(ally.hp>before);assert.ok(ally.hp<=ally.maxHp);`));
test('Uzdrowienie Maga kosztuje manę i leczy siebie w walce',()=>run(`newGame('Mag','mage');state.tutorial.done=true;state.player.hp=20;state.player.stamina=100;const heal=SKILLS.mage.find(s=>s.id==='heal');startCombat({id:'heal-test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});const mana=state.player.mana;playerAction(heal,'self');assert.ok(state.player.hp>20);assert.equal(state.player.mana,mana-combatSkillManaCost(heal));assert.ok(combat.cooldowns.heal>0);assert.equal(combat.phase,'enemyDelay');`));
console.log(`${count} regression checks passed including 3.9.9.2 Luck and Mage healing.`);
test('wybór celu Uzdrowienia pokazuje Maga i żywych sojuszników',()=>run(`newGame('Mag','mage');combat={phase:'player',menu:'healTarget',pendingHealSkill:'heal',partyMembers:prepareCombatPartyMembers([{name:'Łowca',class:'hunter',level:12}]),cooldowns:{}};state.player.hp=Math.max(1,state.player.maxHp-10);const html=combatCommandMenuHTML(combat,state.player,[SKILLS.mage.find(s=>s.id==='heal')],[],0,false);assert.ok(html.includes('data-heal-target="self"'));assert.ok(html.includes('data-heal-target="ally-0"'));assert.ok(html.includes('Łowca'));`));
test('powalony sojusznik nie atakuje i nie może być leczony Uzdrowieniem',()=>run(`newGame('Mag','mage');combat={raidTier:'hero',level:20,hp:1000,maxHp:1000,isBoss:true,stagger:0,staggerMax:100,partyMembers:prepareCombatPartyMembers([{name:'Tank',class:'knight',level:20}]),raidPartyDamage:0,lastPlayerHit:0,log:[]};combat.partyMembers[0].hp=0;assert.equal(activeRaidAllies().length,0);assert.equal(raidPartyAssist(),0);assert.equal(castMageHeal(SKILLS.mage.find(s=>s.id==='heal'),'ally-0'),0);`));
console.log(`${count} regression checks passed after 3.9.9.2 UI and downed-ally checks.`);

test('new and migrated backpacks offer thirty six usable spaces',()=>run(`assert.equal(inventoryCapacity(),36);const old=normalizeState(JSON.parse(JSON.stringify(state)));old.player.inventoryCapacity=32;assert.equal(normalizeState(old).player.inventoryCapacity,36);assert.equal(drawerBagHTML().match(/data-drawer-bag-pos=/g).length,36);`));
test('dragging gear onto an occupied weapon slot swaps equipped items',()=>run(`state.player.level=20;const former=equippedInstance('weapon');const replacement=createGearInstance('shortSword');state.player.inventory.push(replacement);ensureBackpackSlots();const idx=state.player.inventory.indexOf(replacement),oldSlot=replacement.bagSlot;assert.ok(equipIndexToSlot(idx,'weapon'));assert.equal(equippedInstance('weapon').uid,replacement.uid);assert.equal(former.bagSlot,oldSlot);assert.ok(backpackEntries().some(x=>x.item.uid===former.uid));assert.ok(gearDrawerHTML().includes('data-drawer-slot="weapon"'));`));
test('merchant comparison names the worn and offered weapon with numerical differences',()=>run(`const html=equipmentCompareHTML('shortSword');assert.ok(html.includes(itemDef(equippedInstance('weapon').id).name));assert.ok(html.includes(itemDef('shortSword').name));assert.ok(html.includes('Obrażenia'));state.player.level=12;state.ui.shopPage='2';state.ui.shopSelectedBuy='shortSword';assert.ok(shopHTML().includes('equipment-compare'));`));
test('shop stock follows the class and excludes boss equipment',()=>run(`state.player.class='mage';state.player.level=30;const gear=shopInventoryPages()[2];assert.ok(gear.some(id=>itemDef(id).type==='weapon'));assert.ok(gear.every(id=>itemClassAllowed(itemDef(id))&&['common','uncommon','rare'].includes(itemDef(id).rarity)));assert.ok(gear.every(id=>!/^boss_|^drop_/.test(id)));`));
test('alchemist and blacksmith offer an explicit sale action',()=>run(`assert.ok(smithHTML().includes('data-merchant-select-sell'));assert.ok(alchemistHTML().includes('data-merchant-select-sell'));assert.ok(shopSellSheetHTML(state.player.inventory.findIndex(i=>i.id==='potion')).includes('Sprzedaj'));`));
test('all potion tiers are available in combat and recipe licenses are finite',()=>run(`for(const amount of [50,100,150,200]){assert.ok(ALCHEMY_READY_STOCK.some(x=>itemDef(x.id).heal===amount));assert.ok(ALCHEMY_READY_STOCK.some(x=>itemDef(x.id).mana===amount))}state.player.inventory.push({id:'potion200',qty:1},{id:'manaPotion200',qty:1});startCombat({id:'test',template:'slime',type:'monster',synthetic:true,variant:'normal',elite:false});combat.menu='heal';originalOpenCombat();assert.ok(app.innerHTML.includes('data-combat-potion="potion200"'));assert.ok(app.innerHTML.includes('data-combat-potion="manaPotion200"'));combat=null;state.player.gold=1000;buyAlchemyRecipe('potion200');assert.equal(alchemyRecipeUses('potion200'),ALCHEMY_RECIPE_OFFERS.potion200.uses+guildAlchemyExtraUses());`));
test('offline regeneration restores health mana and stamina once after an hour',()=>run(`state.player.hp=1;state.player.mana=0;state.player.stamina=0;state.regen={lastAt:Date.now()-3600000,hpCarry:0,manaCarry:0,staminaCarry:0};const now=Date.now();assert.equal(applyPassiveRegen(now),true);assert.ok(state.player.hp>1);assert.equal(state.player.mana,state.player.maxMana);assert.equal(state.player.stamina,20);const old=state.player.hp;assert.equal(applyPassiveRegen(now),false);assert.equal(state.player.hp,old);`));
test('every named monster has a loot table and gear does not exceed its rank',()=>run(`const caps={'Zwykły':2,'Elita':3,'Heros':4,'Legenda':5},ranks=['common','uncommon','rare','epic','heroic','legendary'];for(const m of MONSTERS){const rows=monsterLootTable(m.id);assert.ok(rows.length,m.id);for(const r of rows){assert.ok(ITEMS[r.id],r.id);if(ITEMS[r.id].slot)assert.ok(ranks.indexOf(ITEMS[r.id].rarity)<=caps[m.rank],m.id+' '+r.id)}}`));
test('legendary boss bonus gear comes from its visible named loot table',()=>run(`state.player.level=100;state.player.class='knight';state.tutorial.complete=true;state.tutorial.rewardGiven=true;const m=MONSTERS.find(x=>x.id==='stormDrake');for(let n=0;n<30;n++){const result=rollCombatLoot(m,{elite:false},{isBoss:true});for(const d of result.drops.filter(x=>ITEMS[x.id].slot))assert.ok(monsterLootTable(m.id).some(r=>r.id===d.id),d.id)}`));
test('equipment attributes affect combat calculations while ordinary items remain plain',()=>run(`const plain=Object.values(ITEMS).find(d=>d.slot&&!['str','agi','int','vit','lck'].some(k=>d[k]));assert.ok(plain);state.player.class='knight';state.player.level=100;const boosted=Object.values(ITEMS).find(d=>d.slot==='weapon'&&itemClassAllowed(d)&&d.str>0);assert.ok(boosted);const old=primaryCombatStat();const inst=createGearInstance(boosted.id);state.player.inventory.push(inst);assert.ok(equipIndexToSlot(state.player.inventory.length-1,'weapon'));assert.ok(primaryCombatStat()>old);`));
test('reopening a merchant service retains its scroll position',()=>run(`state.city.placed=true;state.player.position={x:0,y:0,gps:true,accuracy:5,receivedAt:Date.now()};gpsWatch=1;const modal=document.querySelector('.modal');modal.scrollTop=264;openModal=()=>{modal.scrollTop=0};originalOpenBuilding('alchemist','service');assert.equal(modal.scrollTop,264);`));
console.log('186 regression checks passed after 3.9.9.3 gameplay and loot changes.');

test('biome shapes have varied edges and weights are not fixed area quotas',()=>run(`const s=biomeSite(-1,0),pts=biomeOutline(s);assert.equal(pts.length,64);assert.ok(biomeContains(s,s.x,s.y));assert.ok(new Set(pts.map(p=>Math.round(Math.hypot((p.x-s.x)/s.rx,(p.y-s.y)/s.ry)*100))).size>5);assert.equal(Object.values(BIOMES).reduce((n,b)=>n+b.weight,0),100);assert.equal(BIOMES.ruins.weight,5);assert.equal(biomeAt(0,0),'meadow');`));
test('monster habitats follow the biome at their actual spawn point',()=>run(`for(const e of generateLivingMonsters(daySeed(),{x:0,y:0},state).slice(0,30)){assert.equal(e.biome,biomeAt(e.x,e.y));assert.ok(HABITATS_BY_BIOME[e.biome].includes(e.habitat))}`));
test('city has a mapped 180 metre radius and mobile services need current GPS',()=>run(`assert.equal(CITY_RADIUS,180);state.city.placed=true;state.player.position={x:181,y:0,gps:true,accuracy:5,receivedAt:Date.now()};gpsWatch=1;assert.equal(insideCity(),false);assert.equal(cityServiceAccess(),false);state.player.position.x=179;assert.equal(cityServiceAccess(),true);state.player.position.receivedAt=Date.now()-60000;assert.equal(cityServiceAccess(),false);`));
test('player chooses city placement and cannot relocate before 30 days',()=>run(`assert.equal(state.city.placed,false);state.player.position={x:340,y:120,gps:true,accuracy:5,receivedAt:Date.now()};gpsWatch=1;placeCityHere();assert.equal(state.city.x,340);assert.equal(state.city.y,120);assert.equal(state.city.placed,true);state.player.position.x=500;placeCityHere();assert.equal(state.city.x,340);state.city.placedAt=Date.now()-CITY_MOVE_COOLDOWN-1000;placeCityHere();assert.equal(state.city.x,500);`));
test('placed city keeps local monster spawns outside the city zone',()=>run(`state.city.placed=true;state.city.x=350;state.city.y=350;const monsters=generateLivingMonsters(daySeed(),{x:350,y:350},state);assert.ok(monsters.length);assert.ok(monsters.every(e=>dist(e,state.city)>CITY_RADIUS));`));
test('old saves refresh local shrines without losing player progress',()=>run(`const old=JSON.parse(JSON.stringify(state));old.version=392;old.player.gold=177;old.world.entities=old.world.entities.filter(e=>e.type!=='shrine');const migrated=normalizeState(old);assert.equal(migrated.player.gold,177);assert.ok(migrated.world.entities.some(e=>e.type==='shrine'));`));
test('heads heals fully and consumes one coin and the daily attempt across reload',()=>run(`const e=state.world.entities.find(e=>e.type==='shrine');assert.ok(e);state.player.position={x:e.x,y:e.y,gps:true,accuracy:5,receivedAt:Date.now()};gpsWatch=1;state.player.hp=4;const gold=state.player.gold;flipShrineCoin(e.id,.2);assert.equal(state.player.hp,state.player.maxHp);assert.equal(state.player.gold,gold-1);assert.equal(shrineVisit(e.id).result,'heads');flipShrineCoin(e.id,.8);assert.equal(state.player.gold,gold-1);state=normalizeState(JSON.parse(JSON.stringify(state)));assert.equal(shrineVisit(e.id).result,'heads');`));
test('tails never heals and each shrine has its own daily attempt',()=>run(`const e=state.world.entities.find(e=>e.type==='shrine');state.player.position={x:e.x,y:e.y,gps:true,accuracy:5,receivedAt:Date.now()};gpsWatch=1;state.player.hp=7;const gold=state.player.gold;flipShrineCoin(e.id,.8);assert.equal(state.player.hp,7);assert.equal(state.player.gold,gold-1);assert.equal(shrineVisit(e.id).result,'tails');const second={...e,id:'shrine_second'};state.world.entities.push(second);flipShrineCoin(second.id,.2);assert.equal(state.player.hp,state.player.maxHp);assert.equal(state.player.gold,gold-2);assert.equal(shrineVisit(second.id).result,'heads');`));
console.log(`${count} regression checks passed after 3.9.9.4 biome, city and shrine changes.`);

test('guild contracts can be accepted progressed claimed once and resumed from save',()=>run(`state.player.guild='Bractwo';ensureSocialState();const g=guildState(),c=g.contracts[0];assert.ok(c);acceptGuildContract(c.id);for(let i=0;i<c.need;i++)progressGuildContracts(c.target);assert.equal(c.progress,c.need);const gold=state.player.gold,rep=state.adventure.reputation;claimGuildContract(c.id);assert.equal(state.player.gold,gold+c.gold);assert.equal(state.adventure.reputation,rep+c.rep);claimGuildContract(c.id);assert.equal(state.player.gold,gold+c.gold);state=normalizeState(JSON.parse(localStorage.getItem(SAVE_KEY)));assert.equal(guildState().contracts.find(x=>x.id===c.id).claimed,true);`));
test('accepted guild contracts remain after daily proposals refresh',()=>run(`state.player.guild='Bractwo';ensureSocialState();const g=guildState(),c=g.contracts[0];acceptGuildContract(c.id);progressGuildContracts(c.target);g.contractDay=daySeed()-1;ensureSocialState();const carried=g.contracts.find(x=>x.id===c.id);assert.ok(carried);assert.equal(carried.progress,1);assert.equal(carried.accepted,true);`));
test('guild material board moves delivered loot into a local warehouse exactly once',()=>run(`state.player.guild='Bractwo';ensureSocialState();postGuildRequest('wolfPelt',3);const g=guildState(),r=g.requests[0];assert.equal(r.goal,3);acceptGuildRequest(r.id);addItem('wolfPelt',3);const before=countItem('wolfPelt');deliverGuildRequest(r.id);assert.equal(countItem('wolfPelt'),before-3);assert.equal(r.delivered,3);assert.equal(g.warehouse.wolfPelt,3);deliverGuildRequest(r.id);assert.equal(g.warehouse.wolfPelt,3);assert.equal(r.completed,true);state=normalizeState(JSON.parse(localStorage.getItem(SAVE_KEY)));assert.equal(guildState().warehouse.wolfPelt,3);`));
test('plain class stock and blacksmith stock cover every class at the regular tier',()=>run(`for(const cls of Object.keys(CLASSES)){state.player.class=cls;state.player.level=40;const basics=shopInventoryPages()[2].map(itemDef);assert.ok(basics.some(d=>d.slot==='weapon'&&d.merchantPlain&&d.classes.includes(cls)),cls);assert.ok(basics.some(d=>d.slot==='armor'&&d.merchantPlain&&d.classes.includes(cls)),cls);assert.ok(basics.filter(d=>d.merchantPlain).every(d=>!['str','agi','int','vit','lck'].some(k=>d[k])),cls);const smith=smithStockIds().map(itemDef);assert.ok(smith.some(d=>d.slot==='weapon'&&d.classes.includes(cls)),cls);assert.ok(smith.every(d=>['common','uncommon','rare'].includes(d.rarity)&&!d.bossUnique),cls)}`));
test('one smith gear purchase depletes stock until the next six hour cycle',()=>run(`state.player.level=40;state.player.gold=10000;const id=smithStockIds()[0],price=smithOfferPrice(id),before=state.player.inventory.filter(i=>i.id===id).length;assert.ok(id);buyItem(id,'smith',1);assert.equal(state.player.gold,10000-price);assert.equal(state.player.inventory.filter(i=>i.id===id).length,before+1);assert.equal(merchantSoldOut(id,'smith'),true);buyItem(id,'smith',1);assert.equal(state.player.inventory.filter(i=>i.id===id).length,before+1);state.economy.merchantCycle=merchantCycle()-1;ensureMerchantStockState();assert.equal(merchantSoldOut(id,'smith'),false);`));
test('shop gear sells once per delivery while ordinary potions remain repeatable',()=>run(`state.player.level=40;state.player.gold=10000;const id=shopInventoryPages()[2].find(x=>itemDef(x).merchantPlain),before=state.player.inventory.filter(i=>i.id===id).length;assert.ok(id);buyItem(id,'shop',merchantBuyPrice(id));assert.equal(merchantSoldOut(id,'shop'),true);buyItem(id,'shop',merchantBuyPrice(id));assert.equal(state.player.inventory.filter(i=>i.id===id).length,before+1);const q=countItem('potion');buyItem('potion','shop',merchantBuyPrice('potion'));buyItem('potion','shop',merchantBuyPrice('potion'));assert.equal(countItem('potion'),q+2);`));
test('auction vendor offers daily class gear without unique boss loot and limits purchase',()=>run(`state.player.level=40;state.player.gold=10000;const ids=auctionOfferIds();assert.ok(ids.length);assert.ok(ids.length<=8);for(const id of ids){const d=itemDef(id);assert.ok(['uncommon','rare'].includes(d.rarity));assert.ok(itemClassAllowed(d)&&!d.bossUnique&&!d.classGear)}const id=ids[0],before=state.player.inventory.filter(i=>i.id===id).length;buyItem(id,'auction',1);assert.ok(ensureAuctionVendorState().includes(id));buyItem(id,'auction',1);assert.equal(state.player.inventory.filter(i=>i.id===id).length,before+1);const html=auctionHTML();assert.ok(html.includes('data-auction-search'));assert.ok(html.includes('data-auction-slot'));assert.ok(html.includes('Wyprzedane'));`));
test('alchemy and smith recipes explain where their ingredients can be found',()=>run(`const alchemy=RECIPES.find(r=>r.station==='alchemist'&&Object.keys(r.ingredients).length);const smith=RECIPES.find(r=>r.station==='smith'&&Object.keys(r.ingredients).length);assert.ok(ingredientSourcesHTML(alchemy).includes('Gdzie zdobyć składniki'));assert.ok(recipeCardHTML(smith,'Wykuj').includes('Gdzie zdobyć składniki'));assert.ok(materialSourceLabel('wolfPelt').includes('Łup:'));`));
test('every recipe ingredient has a reachable drop, merchant stock or ingredient recipe',()=>run(`const accessible=new Set(['runeShard','ancientRelic']);for(const m of MONSTERS)for(const row of monsterLootTable(m.id))accessible.add(row.id);for(const cls of Object.keys(CLASSES)){state.player.class=cls;for(const id of shopInventoryPages()[3])accessible.add(id)}for(const row of ALCHEMY_READY_STOCK)accessible.add(row.id);let changed=true;while(changed){changed=false;for(const r of RECIPES)if(Object.keys(r.ingredients).every(id=>accessible.has(id))&&!accessible.has(r.result)){accessible.add(r.result);changed=true}}for(const r of RECIPES)for(const id of Object.keys(r.ingredients))assert.ok(accessible.has(id),r.id+' requires unreachable '+id);`));
console.log(`${count} regression checks passed after 3.9.9.6 guild and merchant changes.`);

test('five city services render integrated NPC scenes without a floating sprite',()=>run(`for(const id of ['shop','smith','alchemist','auction','guild']){const art='interior-'+id+'-'+(id==='guild'?'3998':'3997')+'.webp',html=buildingSceneHTML(id);assert.ok(html.includes(art),id);assert.ok(!html.includes('clean-room-scene-npc'),id);assert.ok(html.includes('clean-room-hotspot-npc')&&html.includes('clean-room-hotspot-service'),id);const c=CITY_INTERIORS[id];assert.ok(npcVisual(c.npc,c.classId,'sprite-npc').includes(art),id)}`));
test('new room artwork exists and tavern retains its integrated Dorian scene',()=>{for(const id of ['shop','smith','alchemist','auction','guild']){const art=path.join(root,'assets/backgrounds/interior-'+id+'-'+(id==='guild'?'3998':'3997')+'.webp');assert.ok(fs.statSync(art).size>0,id)}run(`assert.ok(tavernSceneHTML().includes('assets/tavern-scene-desktop.png'));assert.ok(npcVisual('Dorian','knight').includes('assets/tavern-scene-desktop.png'))`)});
console.log(`${count} regression checks passed after 3.9.9.7 interior and NPC art changes.`);

test('first chapter builds a connected investigation without a forced night walk',()=>run(`
 for(const id of ['q4','q8','q13','q14','q15']){const q=QUESTS.find(x=>x.id===id);assert.equal(q.steps.at(-1).type,'story');assert.ok(storyScene(id)?.choices.length>=2,id)}
 assert.ok(storyScene('q8').portrait==='taren');
 assert.ok(storyScene('q12').choices.find(x=>x.id==='follow').consequence.monster==='goblinWarrior');
 state.story.choices.q4='decode';state.story.flags.routeDecoded=true;assert.equal(conditionSatisfied('nightOrClue'),true);
 assert.ok(storyEchoLine('q6').includes('patroli'));
`));
test('quest combat does not award story rewards before victory, including a failed attempt',()=>run(`
 state.player.level=6;state.player.stamina=100;state.player.gold=250;state.quests.active=['q8'];state.quests.progress.q8=[1,0];
 const beforeGold=state.player.gold,beforeXp=state.player.xp;
 applyStoryChoice('q8','protect');assert.equal(combat.storyMission.type,'escort');assert.equal(combat.level,6);
 assert.equal(state.story.choices.q8,undefined);assert.equal(state.story.traits.mercy,0);assert.equal(state.player.gold,beforeGold);assert.equal(state.player.xp,beforeXp);
 showBattleDefeat=()=>{};loseCombat();assert.equal(state.story.choices.q8,undefined);assert.equal(state.story.traits.mercy,0);assert.equal(state.story.flags.tarenRescued,undefined);
`));
test('protecting the hunter changes the later story and grants rewards once',()=>run(`
 state.player.level=6;state.player.stamina=100;state.quests.active=['q8'];state.quests.progress.q8=[1,0];
 applyStoryChoice('q8','protect');combat.enemyTurns=1;enemyTurn();assert.equal(combat.intent.type,'storyStrike');
 combat.phase='player';defendAction();enemyTurn();assert.equal(combat.storyMission.hits,0);assert.equal(combat.storyMission.protected,true);
 showBattleVictory=()=>{};winCombat();assert.equal(state.story.choices.q8,'protect');assert.equal(state.story.flags.tarenSafe,true);assert.equal(state.story.flags.tarenWounded,undefined);assert.ok(state.quests.done.includes('q8'));assert.ok(storyEchoLine('q12').includes('Taren'));
 assert.equal(commitStoryChoice('q8',storyScene('q8').choices[0]),false);
`));
test('alarm can be stopped in a fight and the outcome persists in the narrative',()=>run(`
 state.player.level=6;state.player.stamina=100;state.quests.active=['q8'];state.quests.progress.q8=[1,0];
 applyStoryChoice('q8','pursue');combat.enemyTurns=1;enemyTurn();assert.equal(combat.intent.type,'storySignal');
 combat.phase='player';originalOpenCombat();assert.ok(app.innerHTML.includes('data-story-disrupt'));disruptStorySignal();
 assert.equal(combat.storyMission.signalStopped,true);assert.equal(combat.intent,null);
 showBattleVictory=()=>{};winCombat();assert.equal(state.story.choices.q8,'pursue');assert.equal(state.story.flags.signalStopped_q8,true);assert.equal(state.story.flags.signalRaised_q8,undefined);
`));
test('missed quest objectives change the recorded result',()=>run(`
 state.player.level=6;state.player.stamina=100;state.quests.active=['q8'];state.quests.progress.q8=[1,0];applyStoryChoice('q8','protect');
 combat.enemyTurns=1;enemyTurn();assert.equal(combat.intent.type,'storyStrike');combat.phase='player';enemyTurn();assert.equal(combat.storyMission.hits,1);
 showBattleVictory=()=>{};winCombat();assert.equal(state.story.flags.tarenWounded,true);assert.ok(storyResultText('q8',storyScene('q8').choices[0]).includes('ranny'));
`));
test('story visuals and all biome battle backgrounds are nonempty and referenced by the game',()=>run(`
 for(const name of ['nessa','eldran','taren','toren']){assert.ok(storyPortraitHTML({npc:name,portrait:name}).includes('assets/story/'+name+'-3998.webp'))}
 for(const biome of ['meadow','forest','ruins','marsh','highlands'])assert.ok(BATTLE_BACKDROPS[biome].endsWith('-3998.webp'));
 assert.ok(CITY_INTERIORS.guild.bg.endsWith('interior-guild-3998.webp'));
`));
for(const file of ['assets/backgrounds/interior-guild-3998.webp',...['meadow','forest','ruins','marsh','highlands'].map(x=>`assets/backgrounds/battle-${x}-3998.webp`),...['nessa','eldran','taren','toren'].map(x=>`assets/story/${x}-3998.webp`)])assert.ok(fs.statSync(path.join(root,file)).size>10000,file);
test('the northern investigation bridges the tower and marsh level gates',()=>run(`
 const ids=['q18','q18a','q18b','q18c','q18d','q19','q20','q20a','q20b','q21'];assert.equal(QUESTS.filter(q=>ids.includes(q.id)).map(q=>q.id).join(','),ids.join(','));
 for(const id of ['q18a','q18b','q18c','q18d','q20a','q20b']){assert.equal(QUESTS.find(q=>q.id===id).steps.at(-1).type,'story');assert.ok(storyScene(id)?.choices.length>=2,id)}
 assert.equal(QUESTS.find(q=>q.id==='q19').level,DUNGEONS.find(d=>d.id==='forgottenTower').min);
 for(const q of QUESTS){const dungeon=q.steps.find(s=>s.type==='dungeon');if(dungeon)assert.ok(q.level>=DUNGEONS.find(d=>d.id===dungeon.target).min,q.id)}
 for(const [id,level] of [['goblin',9],['goblinWarrior',6],['ogre',12],['cultist',17]])assert.ok(MONSTERS.find(m=>m.id===id).min<=level,id);
`));
test('northern clue and combat targets appear as reachable quest entities',()=>run(`
 state.tutorial.complete=true;state.quests.active=['q18a'];state.quests.progress.q18a=[0,0];syncQuestWorld();const clue=questEntityById('north_courier_order');assert.ok(clue&&questWorldEntityVisible(clue));
 checkQuestProgress('questInteract',clue.id);assert.equal(currentQuestStepIndex('q18a'),1);assert.equal(questWorldEntityVisible(clue),false);
 state.quests.active=['q18b'];state.quests.progress.q18b=[0,0];syncQuestWorld();const guards=state.world.entities.filter(e=>e.questId==='q18b');assert.equal(guards.length,2);assert.ok(guards.every(e=>questWorldEntityVisible(e)&&e.type==='monster'));
 guards[0].alive=false;checkQuestProgress('kill','goblinWarrior');assert.equal(questWorldEntityVisible(guards[0]),false);assert.equal(questWorldEntityVisible(guards[1]),true);
`));
test('a distance objective waits for the full route before its scene unlocks',()=>run(`
 state.tutorial.complete=true;state.quests.active=['q20b'];state.quests.progress.q20b=[0,0];
 checkQuestProgress('move',null,120);assert.equal(currentQuestStepIndex('q20b'),0);assert.equal(storyCanChoose('q20b'),false);assert.equal(questStepState(QUESTS.find(q=>q.id==='q20b'),QUESTS.find(q=>q.id==='q20b').steps[0],0).target,520);
 checkQuestProgress('move',null,520);assert.equal(currentQuestStepIndex('q20b'),1);assert.equal(storyCanChoose('q20b'),true);
`));
test('decoding the seal affects tower combat and the marsh dialogue',()=>run(`
 state.quests.active=['q18c'];state.quests.progress.q18c=[1,0];applyStoryChoice('q18c','read');assert.equal(state.story.flags.towerWard,true);assert.ok(state.quests.done.includes('q18c'));
 state.player.level=17;state.player.stamina=100;dungeonRun={id:'forgottenTower'};startCombat({id:'tower-test',template:'cultist',type:'monster',synthetic:true,variant:'normal',elite:false},{level:17,dungeon:{type:'room'}});
 assert.equal(combat.stagger,25);assert.ok(combat.log.some(line=>line.includes('Odczytana pieczęć')));
 assert.ok(storyEchoLine('q20a').includes('wzorowi'));
`));
test('daytime and clear weather do not block the later story trail',()=>run(`
 for(const qid of ['q24','q33','q40','q54'])assert.ok(QUESTS.find(q=>q.id===qid).steps.every(s=>s.type!=='condition'),qid);
 assert.equal(storyScene('q24').requiresSteps,1);assert.equal(storyScene('q33').requiresSteps,1);
`));
test('older saves keep completed trail steps and unfinished tower gets its bridge',()=>run(`
 const old=JSON.parse(JSON.stringify(state));old.version=393;old.quests.active=['q19'];old.quests.done=['q18'];old.quests.progress.q24=[1,1,0];old.quests.progress.q40=[1,0];const migrated=normalizeState(old);
 assert.ok(migrated.quests.active.includes('q18a'));assert.ok(!migrated.quests.active.includes('q19'));assert.equal(migrated.quests.progress.q24.join(','),'1,0');assert.equal(migrated.quests.progress.q40.join(','),'0');
 const late=JSON.parse(JSON.stringify(state));late.version=393;late.quests.active=['q22'];late.quests.done=['q19','q20','q21'];const resumed=normalizeState(late);assert.ok(['q18a','q18b','q18c','q18d','q20a','q20b'].every(id=>resumed.quests.done.includes(id)));
`));
console.log(`${count} regression checks passed after 3.9.9.8 story, mission combat, progression and art updates.`);
